### ISSUE TITLE
Document usage of attributes for Opendata.swiss and Visualize.

### ISSUE THREAD

**Issue by herrstucki** [zazuko/cube-creator#1001]
Purely informational cube metadata that will just be displayed somewhere as text.

These should cover most of the needs for BAFU datasets, taken from https://docs.google.com/spreadsheets/d/1CewrDzTHfwnkAgFXhx_xAQzefYkmUYUY_1nay9KK-_E/edit#gid=0

Required (tbd)
- Titel (des Datensatzes)
- Letzte Aktualisierung

Optional
- Kontakt (Name und Email)
- Quelle
- Beschreibung
- Schlagwort (Thema, Tags)
- Erhebung
- Datenbank
- Erstellungsdatum
- Letzte Änderungen
- Verfügbare Sprachen
- Erhebungsperiode
- Raumbezug
- Link zu Opendata.swiss (für RAW-Daten Download)
- Lizenz

**Comment by l00mi** [comment]
See https://schema.ld.admin.ch/LindasDataset
