### ISSUE TITLE
Add eu-themes as new metadata field

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1005]
A cube can have the eu-category optionally added based on https://s.zazuko.com/2hffre .

predicate: <https://schema.ld.admin.ch/euDataTheme>

Description: The Data Theme Category for the classification in the European Data Catalogs.

**Comment by martinmaillard** [comment]
@tpluscode I'll take this over, as it's one of the last things I feel able to do in a reasonable amount of time ;)
