### ISSUE TITLE
Link to visualize from the "Publish" tab doesn't work

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1007]
The link to Visualize from the "Publish" tab doesn't open the visualization (data loading error). Direct access from test.visualize via the search allows access to the cube data. 

to reproduce
- Open the cube kk_mfm-u_luft_y_v1 in int.cube-creator
- Go to tap "Publish" and activate Link "Visualize.admin.ch"

To find the dataset in test.visualize :
- search "Jahresmittelwerte" (Entwürfe einschliessen)

![image](https://user-images.githubusercontent.com/79834090/144817610-4a852a52-2050-4667-a2a3-3a66167172f0.png)

![image](https://user-images.githubusercontent.com/79834090/144818011-f36d0b4d-7d99-4837-9008-982cb3170d20.png)

**Comment by l00mi** [comment]
This problem came with the change of new category inteface, it is fixed with https://github.com/zazuko/cube-creator/issues/997 which will be online in the next release.
