### ISSUE TITLE
Create interface to define hierarchy. 

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1025]
Per SharedDimension we need to define hierarchies (_forests_), where the SharedDimensions items are the _leaves_ of this _forest_.

A hierarchy is defined by a name and list of _roots_ which are items of a SharedDimension.
A list (ordered) of one or multiple hierarchy levels defined by a predicate link between SharedDimension Items.

Note: This description is valid for the case of the Shared Dimension Interface defined hierarchies. Some details can change for hierarchies build outside of the cube-creator.

**Comment by l00mi** [comment]
https://visualize.admin.ch/en/v/r7-vm0XFrfoh

**Comment by l00mi** [comment]
Current example:

```
PREFIX meta: <https://cube.link/meta/>
PREFIX shacl: <http://www.w3.org/ns/shacl#>

  meta:inHierarchy [
    rdf:type meta:Hierarchy ;
    meta:root <https://ld.admin.ch/country/CHE>;    
    schema:name "CH - Canton - District - Municipality" ;
    shacl:path [
      shacl:inversePath <http://schema.org/containedInPlace> ;
    ] ;
    meta:nextInHierachy [
      shacl:path [
        shacl:inversePath <http://schema.org/containedInPlace> ;
      ] ;      
      meta:nextInHierachy [
        shacl:path [
          shacl:inversePath <http://schema.org/containedInPlace> ;
        ] ;      
      ]
    ]
  ] 
```

**Comment by tpluscode** [comment]
@l00mi please confirm I correctly put 2 and 2 together. 

> Per SharedDimension we need to define hierarchies

Thus `meta:inHierarchy` is property of a shared dimension, right?

> [...] and list of roots which are items of a SharedDimension

The roots would be terms from **any** shared dimension but also not any other type?

**Comment by l00mi** [comment]
Hm, no the meta:inHierarchy shall be used on a Dimension inside a cube. (It can also be used on dimensions which are not "Shared Dimensions" potentially. Currently we will out of UX thinking only allow it on shared dimensions.)

That does say that a Shared Dimension has a `meta:Hierarchy` attached to be applied on any dimension. Therefore we might use a new `meta:hasHierarchy` on the Shared Dimension itself.

**Comment by tpluscode** [comment]
Are we don here for now @l00mi ?

**Comment by l00mi** [comment]
Yes, anything missing will be bugs imo.
