### ISSUE TITLE
Cube Designer message about data validation seems to mix-up after 2 transforms

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1032]
I tried this implementation: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/197
For me it works.
"Warning should be issued if data is missing (cube:Undefined) at least for key dimensions" displays a message on the cube Designer.
"Warning duplicates (the generated or defined Observation IDs with the key dimensions are not unique)" displays a message on the cube Designer.

But doing my tests, I was first working in a same projet, replacing the csv file with either one of those errors, or the others.
What happened is that after the second transform, with the second error instead of the first one, the 2 messages are displayed but the first one should be removed:
![image](https://user-images.githubusercontent.com/6167669/146188791-905e0e82-0647-41b3-a153-9966ddb98d64.png)
Test project: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabtestvalidationmsg3-rkz9xzp0z1q/metadata

**Comment by l00mi** [comment]
With missing `abriidcanton` are you sure the Observation Identifiers are still unique?
![Screenshot 2022-01-17 at 13 42 25](https://user-images.githubusercontent.com/502518/149771558-a6d8fe3b-582f-4524-b0ce-725c82622373.png)

**Comment by FabianCretton** [comment]
Thank you @l00mi for pointing this out.
I made one more test, and I would say that we might need some clarification for the error messages:
"Observation identifiers are not unique" -> I was thinking that this was related to the generated URL for an observation, but it is actually a message about the "key dimensions", right ?

Then, as you point out here above, this message appears in my example when one key dimension is missing only one time (on one line). But in that case the message is not really clear, no ? shouldn't it be something like "Key dimensions values are missing" ? Is that the meaning of "There are observation values missing for some dimensions" ?

I don't want to be "picky" here, but my concern is: how does a user who transformed a 50'000 lines CSV find out what is going wrong and where.

**Comment by l00mi** [comment]
> Thank you @l00mi for pointing this out. I made one more test, and I would say that we might need some clarification for the error messages: "Observation identifiers are not unique" -> I was thinking that this was related to the generated URL for an observation, but it is actually a message about the "key dimensions", right ?

It would be the URL but if the URL is based on **abriidcanton** that could have this effect.

> Then, as you point out here above, this message appears in my example when one key dimension is missing only one time (on one line). But in that case the message is not really clear, no ? shouldn't it be something like "Key dimensions values are missing" ? Is that the meaning of "There are observation values missing for some dimensions" ?

The meaning is that at least one time a value for a "keydimension" is missing. Therefore we can't access it anymore by only restricting / filtering with key dimensions. All key dimension together needs to have a unique value for each entry. And therefore a missing value on any key dimension is a warning sign.

> I don't want to be "picky" here, but my concern is: how does a user who transformed a 50'000 lines CSV find out what is going wrong and where.

That might be the next improvement to actually also state on which line this happens. (Paging did just land this week btw.)

Can you please double check, and then open an new issue with the concern of pointing to the problematic line?
