### ISSUE TITLE
Spaces in project name are not supported

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#105]
When I try to create a project with a space in its name, the API responds with 200, but the project is not created.

**Comment by lucafurrer** [comment]
I just tried it, and it seems to work fine... :question:

**Comment by martinmaillard** [comment]
Really? You don't get redirected to the projects list? Weird

**Comment by martinmaillard** [comment]
Crap, you're right, it works. I don't know what happened yesterday. Sorry 😄
