### ISSUE TITLE
Rework Mapping

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1051]
- [x] Keep original strings in mapped dimensions (to be able to change later on) and distinguish them from mapped concepts. (By using a new temporary predicate.)
- [x] On publish only publish the temporary predicate attached values with the original predicate.
- [x] Allow multiple Shared Dimensions to be connect to one dimension.

**Comment by martinmaillard** [comment]
We considered 3 solutions to store the original value:
1. RDF*:
    - Example: `<<observation1> <country> <switzerland>> cc:originalValue "CH"`
    - May cause support issue in the stores and the different libs
2. Reification: 
    - Example: 
       ```
        [ 
           rdf:subject <observation1> ;
           rdf:predicate <country> ; 
           <rdf:value> <switzerland> ; 
           cc:originalValue "CH" ; 
        ]
       ```
    - Will result in a lot more data
3. A new property: 
    - Example:
      ```
      <observation> <country#original> "CH" . 
      <country#original> a cc:OriginalValueProperty .
       ```
    - We'll need to filter out these values when publishing the cube

No decision yet, but leaning towards 3. Do you have an opinion @l00mi ?

**Comment by l00mi** [comment]
Yes, I think solution 3 is the current best way to go.
