### ISSUE TITLE
Publication UBD010701 MFM-U is pending since yesterday 3pm

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1059]
The publication of the cube UBD010701 MFM-U Luft Jahr NO NO2 is not successful.
Launched twice, yesterday around 3pm.
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd010701-mfm-u-luft-jahr-no-no2-4ppgj566986/publication

**Comment by l00mi** [comment]
We were exactly then doing some work on the pipelining overall. I tried just now and it worked directly. Sorry for the bad timing.
