### ISSUE TITLE
Error : execution took longer than 2h30m0s seconds

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1064]
Related to #1063 

The publication [job](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/20841) starts now but it fails because it take too much time.
The same job works fine in INT.

**Comment by PDumasBAR** [comment]
@tpluscode any news about this job ?

**Comment by tpluscode** [comment]
I cannot see the traces any more but I expect its cause is related to that of #756 

I think that the changes which are already running on INT should help. We will be deploying the latest changes soon

**Comment by PDumasBAR** [comment]
The PROD is down ! Not sure, but maybe an eIAM related problem.
Are the changes deployed ?

**Comment by l00mi** [comment]
@PDumasBAR nothing from our side. Please check with VSHN for more details.

**Comment by PDumasBAR** [comment]
Stardog is running. No problem on Lindas.
The cube-creator PROD works for you ?

**Comment by l00mi** [comment]
No Stardog is not running.. there are spilling problems currently.

**Comment by PDumasBAR** [comment]
OK, I've just tried your updated query for the zefix and it works.  I ask VSHN

**Comment by l00mi** [comment]
The cube was now published multiple times. Closing meanwhile.
