### ISSUE TITLE
Cube cannot be published in INT

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1083]
I tried several times to publish a cube in CC INT this afternoon, but the publication failed.

![image](https://user-images.githubusercontent.com/79834090/153446478-212754d0-ede4-44d2-a0c1-322515715660.png)

**Comment by tpluscode** [comment]
Is this a project imported from TEST?

**Comment by ortnever** [comment]
I don't remember. I exported the project in decembre 2021 and imported it again today, I think from INT but not sure.

**Comment by ortnever** [comment]
Tell me if I have to do the manipulation again..export and import.

**Comment by tpluscode** [comment]
Not yet. We'll look into the export/import first to rule out a pre-existing bug which now surfaced since we added metadata validation

**Comment by ortnever** [comment]
Hello @tpluscode, Something new about that? I would like publish the cube for a discussion with Dataowner.

**Comment by tpluscode** [comment]
@ortnever yes, sorry. I found the actual issue in export. It would add an unwanted value for the identifier. I removed it from your project's metadata. Please try publishing now.

I will create a dedicated issue for fixing the export.

**Comment by ortnever** [comment]
Thank you Tomasz ! Perfect. It's published. I have exactly the same problem with following cube. Could you clean the project's metadata for this cube too?
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd003002-red-list-latest-survey-mvda8dlp22w/csv-mapping

![image](https://user-images.githubusercontent.com/79834090/154067319-4d919137-a826-49e0-8aaf-c1124a17ecce.png)

**Comment by tpluscode** [comment]
Of course. It is done

**Comment by ortnever** [comment]
Thanks @tpluscode

**Comment by tpluscode** [comment]
Closing as I don't think this issue has occurred since. 

@ortnever please reopen if you feel necessary
