### ISSUE TITLE
Cube's metadata : data refresh Interval

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1084]
In CC PROD -> Cube Designer -> Cube Metadata : no value available in the drop down List for the field 
- data refresh Interval

![image](https://user-images.githubusercontent.com/79834090/153573544-8c6f631f-ecc6-4eaa-b82e-d6ac4a17fc2a.png)

**Comment by l00mi** [comment]
I know the problem, we did change the way to import this data from the EU source. Should be fixed soon.

**Comment by l00mi** [comment]
Works again. https://github.com/zazuko/cube-creator/pull/1087
