### ISSUE TITLE
Publication locked in PROD

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1093]
Project : [Stapfer-Enquête 1799](https://cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!stapfer-enquete-1799-ydqqxlladok/publication)
I have updated the tags. Thanks for the new feature which helps me a lot.
But I can't publish the new version.

**Comment by l00mi** [comment]
I did push once more (very hard), and then it worked. I guess just a fluke in the infra.
