### ISSUE TITLE
Create a new cube project

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#11]
Users need to be able to create a new cube project. When doing so, they have to decide if they start **from CSV files** or **from an existing cube**.

- When starting from CSV, users will have access to the [CSV mapper](https://zazuko.github.io/bafu-datacube-workshop2-mockups/#/cubes/quality-of-air-ch/mapper)
- When starting from an existing cube, users will only have access to the [metadata editor](https://zazuko.github.io/bafu-datacube-workshop2-mockups/#/cubes/quality-of-air-ch/designer) (= "Cube designer" in the mockups)

**Comment by tpluscode** [comment]
Here's my understanding

### Cube Project

Ok, so in both cases we create a CubeProject resource. What else does it need besides a label?

_using prefix cc for **C**ube **C**reator_

```turtle
<project/X> a cc:CubeProject ;
  rdfs:label "Example project" .
```

### From existing cube

I think this is the more base scenario. As discussed yesterday, the csv sources would be used to create a raw cube, from which point the workflow is the same.

Here's what I understood:

1. User provides a reference to a cube
2. A link to the cube is created in the project
3. The cube is analyzed to discover dimensions and populate the designer resources

The created resource would reference the source cube

```turtle
<project/X> cc:sourceCube <cube/X> .
```

I guess that the cube itself would also have to be a resource itself but don't know the details yet

Questions:

1. How do we reference that input cube ❓ 
   * is it a graph/resource in the same triple store?
   * if not, then I suppose we import the cube/make a copy?
2. Do we need to handle changes in the source cube to?
   * in fact, do cubes ever change, or is a new cube always created?

### From CSV files

In the case of csv files, I assume that we would not take upload immediately, right? A Project created this way would have a link to a collection of sources

```turtle
<project/X> cc:csvSources <project/csv-sources> .
```

* The linked `<project/csv-sources>` would be used to upload the csv (#13).
* Absence of this link should hint the UI to hide the mapper tab

At this point there is no

**Comment by martinmaillard** [comment]
Most of what you said also matches my understanding. I'll try to address your questions:

## Existing cubes

> 1. How do we reference that input cube ❓
>     - is it a graph/resource in the same triple store?
>     - if not, then I suppose we import the cube/make a copy?

That's something we need to figure out with the people creating cubes. My feeling is that it could be in another endpoint. And it would probably be better if we fetch it when running the pipeline, rather than making a copy of it upfront. But I'm really not sure of that.

> 2. Do we need to handle changes in the source cube to?
>   - in fact, do cubes ever change, or is a new cube always created?

Yes. We need to be able to re-run the pipeline with the new version of a raw cube.

> I think this is the more base scenario

For the pipeline itself it is more basic than CSV (one less step), but there's still a lot of things we need to figure out for this use case. That's why I would concentrate on the CSV mapping at first, as we know how to do it.

## From CSV files

You're assumption is correct: users don't upload CSVs when creating the project. After creating a project, they are redirected to the mapper where they can upload CSV files (sources).

> Absence of this link should hint the UI to hide the mapper tab

In the data model (#10), I put a `CSVMapping` resource for this purpose (absence = no mapper). But if we don't need it, I guess we can do what you proposed.

 > At this point there is no cube yet

I think this is not exactly true. The cube will be empty, but it should already be there. Running the CSVW mapping is required to get data in the cube (observations, etc.), but when defining the mapping itself, we are already creating the cube metadata.

What I mean is that when you create a dimension property in the Observation resource, you are already creating a dimension in the cube metadata.

Now that I think about it, we could even create the `Observation` resource when creating the project, as it will be mandatory for all cubes...
