### ISSUE TITLE
Problem to publish a cube on INT and on PROD

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1110]
I would like to publish follwing cube on INT bit it doesn't work.

Project name : UBD003001 Red List, latest survey, included %
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd003001rotelistelastevaluation-vpgagpgv5ov/csv-mapping

![image](https://user-images.githubusercontent.com/79834090/155510899-7bd844de-74b4-444d-b543-5065d52e37ec.png)

**Comment by ortnever** [comment]
Same Problem on PROD

![image](https://user-images.githubusercontent.com/79834090/155553942-ac829126-dbb7-4c54-9d78-9eab454f2177.png)

**Comment by tpluscode** [comment]
We found the mistake. Publishing should be working again now

**Comment by ortnever** [comment]
@tpluscode Thank you Tomasz. It's ok on INT but not on PROD.

![image](https://user-images.githubusercontent.com/79834090/155566703-1af399cf-3900-4e66-87f7-7c1069c3d9a2.png)

**Comment by ptbrowne** [comment]
When can we expect a prod publication ? Is this going to happen today or next week ?

**Comment by l00mi** [comment]
Its online.
