### ISSUE TITLE
Create short Videos for the README

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1114]
Create short Videos for the README similar to https://github.com/zazuko/cube-viewer

Showing:
* Upload and Mapping of a simple example and starting Transformation
* Presentation of the Cube-Designer View and adding/changing Metadata on the Cube and Dimension
* Publishing a Cube and short Glimps of presentation in Visualize

**Comment by l00mi** [comment]
@martinmaillard as I like the videos on cube-viewer a lot, is it okay for you to give this a try? If not please feel free to unassign.

**Comment by martinmaillard** [comment]
@ktk created the cube-viewer video, but I can try

**Comment by l00mi** [comment]
Okay up to you!

**Comment by martinmaillard** [comment]
Here's a first draft of the first video. Let me know what you think.

I'm not sure the captions are actually useful?

https://user-images.githubusercontent.com/1334124/159272386-66ea45d9-99c8-4bea-8e03-4793a8afde56.mp4

**Comment by l00mi** [comment]
I like it a lot. Please keep going. No need to redo anything, but in general it would be better for such videos to use any use case e.g. "Temperatures in Switzerland", then an abstract "demo".

**Comment by martinmaillard** [comment]
@l00mi Good point, do you have a use case in mind (or a sample file?). Otherwise I'll adjust my demo slightly to use your temperatures idea.

**Comment by FabianCretton** [comment]
@l00mi do you already have the video that will be displayed during the lecture ?

**Comment by l00mi** [comment]
@ktk is on that if I understand correctl.y
