### ISSUE TITLE
Publish Cube does'nt work on PROD

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1116]
Impossible to publish following cube on PROD.
UBD003701 Lärmbelastung durch Verkehr (Duplicata of UBD003701 because I had to change the structure of UBD0037 and I don't want to break the grafik on Home page. The first cube (UBD0037) will be deleted on Monday)

![image](https://user-images.githubusercontent.com/79834090/155689556-4a15bf3b-cbb8-4238-bee4-4499919b275c.png)

**Comment by l00mi** [comment]
@ortnever that is still the same error we have in some projects. The fix for this is not yet ready, but we can easily fix it manually, so if you encounter the message       

```
Error: [{"message":["schema:Dataset needs a schema:identifier"],"path":"http://purl.org/dc/terms/identifier","sourceShape":"b81","focusNode":"https://environment.ld.admin.ch/foen/ubd003701/1","severity":"http://www.w3.org/ns/shacl#Violation","sourceConstraintComponent":"http://www.w3.org/ns/shacl#MaxCountConstraintComponent"}]
```

Just write us. The pipeline should be published soon.

**Comment by l00mi** [comment]
A small remark, I would not start adding years in the Dataset title. It is okay if it has the same title. We should then show the metadata about the "dataPeriod" accordingly to distinguish such cases.

**Comment by ortnever** [comment]
Thanks a lot for your promptly reaction.
