### ISSUE TITLE
Keywords (Tags) not exported for the DCAT harvester

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1127]
I don't know when it happens, but the keywords (tags) are no more exported in the DCAT export for opendata.swiss.
I've made a test to add a lot of keywords in this project [Staatsrechnungen - Amt](https://cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-amt-lanw3m5kxq/metadata/edit).
Keywords are visible in [Lindas](https://lindas.admin.ch/sparql#query=PREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%0ADESCRIBE+%3Fcube%0A%0AFROM+%3Chttps%3A%2F%2Flindas.admin.ch%2Fsfa%2Fcube%3E%0AWHERE+%7B%0A%0A++++++%3Chttps%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Office%3E+schema%3AhasPart+%3Fcube+.%0A++++++%3Fcube+schema%3Aversion+5+.%0A++++%0A%7D%0A&endpoint=https%3A%2F%2Flindas.admin.ch%2Fquery) but not in the [DCAT export](https://lindas.admin.ch/ckan?organization=https://register.ld.admin.ch/opendataswiss/org/schweizerisches-bundesarchiv-bar)

**Comment by martinmaillard** [comment]
There was a bug in the CKAN endpoint. Should be fixed now, will be deployed in a few minutes.

**Comment by PDumasBAR** [comment]
Salut Martin,

Les tags sont bien exportés, mais il y a une erreur dans le fichier.
Le harvester DCAT signale : 
Error parsing the RDF file: <unknown>:2:0: reserved prefix (xml) must not be undeclared or bound to another namespace name

Si je fais une validation du fichier, j'obtiens ce message : 
The namespace for 'xmlns:xml" is reserved and it can only be declared as 'http://www.w3.org/XML/1998/namespace'

Il semble que tu as mis un slash de trop a la fin : 'http://www.w3.org/XML/1998/namespace/'

**Comment by PDumasBAR** [comment]
@martinmaillard 
Le harvester fonctionne correctement et les tags sont importés dans opendata.swiss.

**Comment by martinmaillard** [comment]
Merci pour le retour !
