### ISSUE TITLE
Login problem in INT not resolved

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1164]
Related to #1148 

J'ai demandé à Rebekka de réessayer de s'enregistrer dans le cube-creator INT .

Réponse de Rebekka :

Es funktioniert leider immer noch nicht. Aber immerhin erscheint jetzt "Authentification" und dann irgendwann "Error occured during authentification"...

**Comment by PDumasBAR** [comment]
C'est bon, Rebekka a fait un nouvel essai et ça marche !!!
Je ferme ce ticket

**Comment by l00mi** [comment]
shortest lifetime of ticket ever (-:
