### ISSUE TITLE
CSV Mapping - Edit column mapping - Dimension type no more displayed on Literal value, but present on link to another table

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1167]
see title: maybe it was decided to remove "dimension type" from CSV mapping, in which case it should be removed from both ?

![image](https://user-images.githubusercontent.com/6167669/162703141-f6fb6748-bec9-4e16-9a8f-13b24b6217b0.png)

![image](https://user-images.githubusercontent.com/6167669/162703081-544c4596-b2dd-45f6-9680-ba2e2db55f92.png)

**Comment by l00mi** [comment]
Good catch @FabianCretton, @tpluscode could you please remove it also from the other side please.

**Comment by FabianCretton** [comment]
@l00mi if the Dimension Type is removed from the CSV Mapping, I guess the User Guide has to be updated here:
https://github.com/zazuko/cube-creator/wiki/1.-CSV-Mapping#dimension-type
