### ISSUE TITLE
Shared Dimension download-> Payload Too Large (413)

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1184]
When clicking "download" button for Shared Dimension: https://test.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!fabcofogtest3

I get this error:
![image](https://user-images.githubusercontent.com/6167669/163551347-33772d4b-8e80-4b98-b4bf-e6564dacbe9c.png)

**Comment by tpluscode** [comment]
Fix is now live on TEST @FabianCretton

**Comment by FabianCretton** [comment]
Thank you @tpluscode, I was able to download the shared dimension

**Comment by FabianCretton** [comment]
Hi, today I tried to download a Shared Dimension on INT, and it seems the same bug appeared. Was it corrected on TEST but not INT ?
