### ISSUE TITLE
import csv from url no longer retains the url

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#1188]
steps to reproduce:
- when importing a csv from url i.e. see https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!issue003-repro-dod5okbykg6/csv-mapping

actual result:
- the url is no longer remembered (blank URL field) nor contained in the project.trig as it was the case a while ago i.e. in this trig described here: https://github.com/zazuko/cube-creator/issues/843

expected result: 
- [x] the url should be rememered in the project to easily reupload by just pressing the upload button again
- [x] the url should be exported in the project.trig file

**Comment by tpluscode** [comment]
Do you mean the URL field here?

<img width="383" alt="image" src="https://user-images.githubusercontent.com/588128/164396805-ab0cbfb4-abc8-43ef-abe7-b0cd22dd0368.png">

Are you sure that it was ever stored with the project?

**Comment by tpluscode** [comment]
Ok, please disregard my earlier comment. Obviously, we keep the URL because one can still download directly from its location.

Will look into this
