### ISSUE TITLE
INT - Create Shared Dimension from import -> error with no explanation and .trig file should be good

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1196]
Today I tried to create a Shared Dimension on INT, from an import.
Here is the error - but no explanation is given:
![image](https://user-images.githubusercontent.com/6167669/166195618-07894cfb-0776-49d5-8165-5260f2588d30.png)

The .trig file is a copy of a file that I uploaded successfully as a Shared Dimension on TEST.
I did modify a few things in that file, so there could be an error, but the .trig does validate with the W3C validator.

I tried with 2 versions of the file, one with full URLs, one with relative URLs, same problem.

As It seems that I can't attach the file with a .trig extension, I rename it with a .txt extension.
[Classification of the functions of government (COFOG) INT_copy of TEST fab 4_download02052022.txt](https://github.com/zazuko/cube-creator/files/8601257/Classification.of.the.functions.of.government.COFOG.INT_copy.of.TEST.fab.4_download02052022.txt)
[Classification of the functions of government (COFOG) INT fab 1 - full hierarchy - full URLs - no root for tot.txt](https://github.com/zazuko/cube-creator/files/8601258/Classification.of.the.functions.of.government.COFOG.INT.fab.1.-.full.hierarchy.-.full.URLs.-.no.root.for.tot.txt)

**Comment by FabianCretton** [comment]
Today I tried to import the same file once again, this time an error shows up:
![image](https://user-images.githubusercontent.com/6167669/167401059-1942cf9e-0323-40f8-808a-386ea2333846.png)

but I do not really understand the problem.

Any clue of what is happening ?
You have the files in my former post if you want to try.

Thanks

**Comment by FabianCretton** [comment]
Today, the import did work.
The Cube Creator version did change in the meanwhile, from 1.11.0 to 1.11.1
I do not know if a fix was  applied, as Tomasz did say on Zulip: "The import if a bit unstable. I have been unable to reproduce in development environment. It also appears to sometimes work and I know that the issue is limited to the UI somehow"

I hope there was a fix, otherwise this should be debugged.

**Comment by l00mi** [comment]
Closing for now, please re-open if the error still persists.
