### ISSUE TITLE
INT - Replace CSV + Question Datatype Month

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1199]
I have tried several times to replace the csv in the project ubd010705-mfm-u-luft-monat-no-no2 (CC INT) but the old file remains. 
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd010705-mfm-u-luft-monat-no-no2-pjaad2relwe/csv-mapping
Another question: how do I have to I specify the datatype "Month" in the csv. I put --mm (see attached sample file).
Is this correct?
@l00mi , could you add this information in the documentation under 
https://github.com/zazuko/cube-creator/wiki/CSV-Preparation#formats
Thanks
 See Column "Monat" in [Datenkiosk_Luft_m_2011_2017_NO_NO2_Monat.csv](https://github.com/zazuko/cube-creator/files/8652535/Datenkiosk_Luft_m_2011_2017_NO_NO2_Monat.csv)

**Comment by ortnever** [comment]
The csv problem is solved, it was a mistake on my part.
I have concatenated the month and year in the csv file. Could you tell me how to format a date with year + month (precision: month), type xsd:gMonth.

**Comment by tpluscode** [comment]
Glad to hear you found the mistake 👌 

Do you want to use [`xsd:gYearMonth`](http://books.xmlschemata.org/relaxng/ch19-77135.html) then? That would be formatted as `YYYY-MM`

**Comment by ortnever** [comment]
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd010705-mfm-u-luft-monat-no-no2-pjaad2relwe/csv-mapping

**Comment by ortnever** [comment]
Just to be sure: In my source file the month and year are in 2 separate columns. I have to concatenate them if I want to use this time reference in Visualize? Is that right?

**Comment by l00mi** [comment]
@tpluscode yes please

**Comment by tpluscode** [comment]
Ok, I opened a PR to enable `gYearMonth`

Since we don't have a way to define a dimension/column from multiple CSV values, you would indeed have to prepare a column before uploading

**Comment by ortnever** [comment]
Thank you Tomasz. Let me know as soons as gYearMonth is implemented, so that i could continue with my cube.

**Comment by tpluscode** [comment]
It should be available in a few minutes on INT
