### ISSUE TITLE
List cube projects

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#12]
Users need to be able to list existing cube projects

**Comment by tpluscode** [comment]
Right now every user will see all projects?

**Comment by martinmaillard** [comment]
At first, yes 👍

**Comment by lucafurrer** [comment]
This is done, no?

**Comment by vhf** [comment]
Kinda, it still needs quite some work. For instance @tpluscode mentioned we will probably only show your own projects (or the projects you have access to).
