### ISSUE TITLE
Disappearing UI Elements after Auto Mapping

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1215]
After successfull auto mapping some edge case makes the UI elements disappear.
<img width="386" alt="Screenshot 2022-05-18 at 09 26 07" src="https://user-images.githubusercontent.com/502518/168982000-a87aa7de-1d80-4eb5-bc2e-8a4e89f0856f.png">

Console:
<img width="614" alt="Screenshot 2022-05-18 at 09 28 17" src="https://user-images.githubusercontent.com/502518/168982187-6d1a7cb2-8a07-4238-abc7-900b93993165.png">

**Comment by tpluscode** [comment]
Can we still reproduce this? I have not seen this in a while
