### ISSUE TITLE
Publish of red_lists fails, after cleaning of last friday: error: [{"message":["schema:Dataset needs a schema:identifier"]

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1224]
Last friday, the environnements where cleaned up.
I have this "red list" dataset on INT: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabredlists-pdnoobynkzn/publication

This project was exported (.tri + csv), then deleted. 
After the clean-up, the project was recreated from the export and the .csv updated.
The transform worked.
But the publications failed (see log)

**Comment by l00mi** [comment]
After removing on the `dcterms:identifier` on the cube metadata it does publish again. We keep this issue open to understand why this triple was added wrongly here.

@FabianCretton the cube did deploy correctly.

**Comment by l00mi** [comment]
@FabianCretton from where did you export this dataset? Just to understand better how the problem could happen.

**Comment by l00mi** [comment]
See also: https://github.com/zazuko/cube-creator/issues/1227

**Comment by tpluscode** [comment]
FYI, I fixed this in all current projects in INT and TEST. Should be working now

**Comment by FabianCretton** [comment]
> @FabianCretton from where did you export this dataset? Just to understand better how the problem could happen.

@l00mi The project was on INT, I did export .trig+csv from there, and then, after your clean-up, re-created the project there.

**Comment by FabianCretton** [comment]
Here is the exported .trig (renamed .txt to allow upload here.
[Fabian Red List Test 1.trig.txt](https://github.com/zazuko/cube-creator/files/8768161/Fabian.Red.List.Test.1.trig.txt)
