### ISSUE TITLE
Cube Designer (INT): for some projects nothing displays

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1230]
On Cube-Creator INT, version 1.12.1
For some projects, the Cube Designer just turns without hand.
It happens during the first operation, even before displaying the table and starting loading the data (which is normally the slower step)
Some projects with that issue:
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabforestrynormalized-5ljx6a5axdk/metadata
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-forestry-3xrvo6r60jo/metadata
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd010703-mfm-u-luft-russ-yqpwjmqm67/metadata

For others, it works fine.

![image](https://user-images.githubusercontent.com/6167669/170188662-6d3a9038-1fa0-494e-985c-ee6c7a617665.png)

**Comment by tpluscode** [comment]
This appeared to a small fluke in the project data files which appeared as maintenance of the database was undertaken. I corrected it and it should be working now
