### ISSUE TITLE
(Header with) whitespace should be trimmed

### ISSUE THREAD

**Issue by ktk** [zazuko/cube-creator#1232]
I have a CSV which I exported from a SPARQL query I did, the content looks like this:

```csv
"municipalityName ","municipalityId ","cantonName ","cantonId ","population ","date "
"Aeugst am Albis ","1 ","Zürich ","1 ","1700 ","2010-12-31 "
"Aeugst am Albis ","1 ","Zürich ","1 ","1740 ","2011-12-31 "
"Aeugst am Albis ","1 ","Zürich ","1 ","1824 ","2012-12-31 "
"Aeugst am Albis ","1 ","Zürich ","1 ","1910 ","2013-12-31 "
```

Note the whitespace added in there.

Because of the whitespace I get mappings like this for templates: `{municipalityId }/{population }/{date }`

And that fails directly in the conversion job:

```
        Error: Quad object has invalid datatype:
	<https://culture.ld.admin.ch/sfa/statpop/municipality/1%20> <https://culture.ld.admin.ch/sfa/statpop/municipalityid> 1  .
    at Object.validate (/app/cli/lib/validation.js:8:15)
    at file:///app/node_modules/barnard59-base/map.js:8:21
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processTimers (internal/timers.js:497:9)
      
```

**Comment by ktk** [comment]
I deleted the whitespaces and then I couldn't update the mapping because it's not what it sees. Crappy CSV for sure but maybe a warning might be a good idea then.

**Comment by tpluscode** [comment]
Are there cases when whitespace is desirable? Maybe a per-column option to trim. Enabled by defaut?

**Comment by tpluscode** [comment]
@ktk what would you like to do about this issue?
