### ISSUE TITLE
INT - New shared dimension cannot be created

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1233]
Cube creator INT, version 1.12.1 (425565a) browser : edge
As I try to save a new shared dimension I get following Error message 
![image](https://user-images.githubusercontent.com/79834090/171125269-6f21f695-874e-40e9-bf93-ecef62050858.png)

Question : 
How can I delete a shared dimension that I created for testing and that is not used? You can delete them for me if i cannot  

- kingdom
- species group

**Comment by l00mi** [comment]
@ortnever this sometimes happens, closing and reopening the dialog often solves this as a workaround for now.

**Comment by ortnever** [comment]
@l00mi thank you for the trick, but it did not help.
