### ISSUE TITLE
[urgent] Cube Creator INT for today 6.06 and7 June class - Disk space issue

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1234]
I am editing an observation in the Cube Designer, on INT, and I get a "disk space" error
I would need this problem to be fixed ASAP to prepare tomorrows class and of course for tomorrows teaching class as well..
![image](https://user-images.githubusercontent.com/6167669/172102029-7020ec4a-c97f-4276-afe3-84f6df029776.png)

**Comment by l00mi** [comment]
We can't do much here, a ticket for problems on INT at VSHN is open since saturday.

**Comment by l00mi** [comment]
https://control.vshn.net/tickets/SBAR-674
