### ISSUE TITLE
Cube Creator slowness that needs to be clarified (why is it slow during basic operations ?)

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1235]
I take the opportunity of the class that we gave yesterday, were we just couldn't use the Cube Creator.
I guess this will be discussed with Pierre, but here I give my first impression.

I was expecting to have slowness during lengthy operations as transformation/publication, but the problems raised much earlier as soon as 40 people got connected: anything in the interface was slow: every window opening (new project, table edition on the CSV Mapping, meta-data edition on the cube-designer).

And I would thus like to clarify why the interface is slow when nothing "time-consuming" seems to happen.

I made a kick and dirty recording of the INT Cube Creator this morning (no more in the situation with 40 users), when clicking the "new project" button. As can be seen on the video, it takes 15 seconds to open this "simple" window. 
The hourglass turns at two points, which I do not fully understand:
- 8 seconds just to display the basic interface
- 7 seconds to retrieve a list of 4 publishing profiles

Is it possible to identify the cause of those slowness ?
Is the javascript library used for the interface which is slow ? 
or are there SPARQL queries in the background that, even simple, take time ?

To be noted that this is different from that issue that I raised: https://github.com/zazuko/cube-creator/issues/1212
(where I proposed how to improve a sparql performance from 40 seconds to 10)

The Interface speed is crucial for end-users and product adoption, of course. 

https://user-images.githubusercontent.com/6167669/172541778-61a48fcc-9023-4483-99cf-f92d29bb5dcf.mp4

**Comment by l00mi** [comment]
As already explained this to Pierre, we can have a look on performance improvements at some point. But the yesterday the main problem with 40 participants yesterday is mostly the problem of an overloaded DB not running in a cluster. I warned upfront that the transformations are not problematic as they are done outside of the DB. 

<img width="725" alt="Screenshot 2022-06-07 at 15 54 56" src="https://user-images.githubusercontent.com/502518/172546510-74f5028f-5ae2-4303-920a-1a4e4f9935b6.png">

**Comment by FabianCretton** [comment]
I think we need to pin-point what the problem is here, is it on the SPARQL queries side, on VSHN side, Stardog version, etc.

This was asked in the WTO for Los 1:
- Minimale Performance Basiskonfiguration "Explore"	
Der Triplestore in der Basiskonfiguration (5 Milliarden Triples) erreicht bei 64 Concurrent Clients 1000 query mixes pro Stunde.
- Benchmark BSMS nach Spezifikation v3.1 im UseCase "Explore" (http://wifo5-03.informatik.uni-mannheim.de/bizer/berlinsparqlbenchmark/spec/index.html)

- Minimale Performance Basiskonfiguration "Explore & Update"	
Der Triplestore in der Basiskonfiguration (5 Milliarden Triples) erreicht bei 64 Concurrent Clients 700 query mixes pro Stunde.
- Benchmark BSMS nach Spezifikation v3.1 im UseCase "Explore & Update" (http://wifo5-03.informatik.uni-mannheim.de/bizer/berlinsparqlbenchmark/spec/index.html)

This BSBM test was performed on LINDAS by Trivadis if I am not mistaken, should this test be run every time a new Stardog version is installed ?
Was this test runned on all Stardog DBs ? Because here we do talk about a specific DB used by the Cube Creator, right, which is different from the open SPARQL end-point ? Is it correctly indexed, etc. ?

**Comment by l00mi** [comment]
That would be good, at least once the architecture is switched from cluster mode to single node.
