### ISSUE TITLE
Also add http://xmlns.com/foaf/0.1/topic

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1240]
When publishing a new cube also add:

```<https://*.ld.admin.ch/.well-known/void>
   <http://xmlns.com/foaf/0.1/topic> <https://*.ld.admin.ch/*> ;
```
A side the already existing
   <http://schema.org/dataset>

**Comment by tpluscode** [comment]
This should be property of the cube itself? Which is the `<https://*.ld.admin.ch/*>`?

**Comment by l00mi** [comment]
No it should connect the /void with the cube.. exactly the same as schema.org/dataset does already.
