### ISSUE TITLE
OIDC secret for tests/evaluation

### ISSUE THREAD

**Issue by nikolatulechki** [zazuko/cube-creator#1244]
Hello,

We are trying to run cube-creator as part of a student project. Reading the documentation it is not clear if we can do this and how to obtain a OIDC secret. The [doc](https://github.com/zazuko/cube-creator#preparing-the-environment) says that it is done vi keycloak, but keycloak ha no registration options, just a login and trying to log in using the GH account does not work

Can someone please hep us on this one.
Thanks

**Comment by tpluscode** [comment]
Keykloak is self-hosted OIDC provider which we use in our setup (also in development, using a separate instance). Hence, there is no registration. You would typically provide your own authentication provider

**Comment by l00mi** [comment]
I hope this answer helped you in solving the problem. Please contact us again if you have other problems.
