### ISSUE TITLE
Publishing Jobs wrongfully displayed as pending

### ISSUE THREAD

**Issue by kronmar** [zazuko/cube-creator#1250]
![image](https://user-images.githubusercontent.com/95312586/176125367-48a5bb1a-9473-40a9-b702-41dbd5f9e91c.png)

I wanted to publish a cube last week. Presumeably due to missing english labels, the publication failed as we (me and Thomas) could gather from the logs. These failed jobs (second and third in the list) are still shown as pending, eventhough they should be marked as failed like the first entry in the list.

**Comment by l00mi** [comment]
Normally there is a clean-up job taking care of these every so many hours. @tpluscode is this job stuck potentially?

**Comment by tpluscode** [comment]
Ah, we're only marking jobs which actually have turned to active. If for whatever reason a job does not start on GitLab, that will not be marked as failed after the timeout
