### ISSUE TITLE
Publication fails if missing labels in default (english) language?

### ISSUE THREAD

**Issue by kronmar** [zazuko/cube-creator#1251]
Also see issue#1250.

Presumably, a publication failed due to only having labels in German and no other language. This is not clear from the user interface. Maybe it would be best, if the user is informed of such a behaviour with some warning labels at the top of the Cube Creator tab?

**Comment by kronmar** [comment]
Found the issue on my end. The underlying csv was faulty/wrongly configurated. Issue#1250, the wrong display of publication status still persists.

**Comment by l00mi** [comment]
@kronmar can you share the miss configuration? Just to understand if there still could be a use full feedback in such a case. Thank you.

**Comment by kronmar** [comment]
The csv was not in a proper format, with rows not identifying one measurement point with all its properties (region, species, observation etc etc) but with rows being indexed by one key dimension and columns by the other.
