### ISSUE TITLE
Publication does not work on cc INT

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1252]
![image](https://user-images.githubusercontent.com/79834090/176680533-2635f902-3223-4e9c-91aa-0ac5ba4b11f3.png)

**Comment by l00mi** [comment]
@tpluscode it seems on first sight to be a regression on the Validation, https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/30588

**Comment by Rdataflow** [comment]
@tpluscode unfortunately multiple people are blocked by this issue. currently publication doesn't work.

cc @kronmar @sam-e-ch

**Comment by l00mi** [comment]
It seems to be a specific problem to some cubes. It does not block all cubes.. E.g. https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/30622 just was able to publish successfully.

**Comment by sam-e-ch** [comment]
One problem I could identify is with linked shared dimensions.
After removing the link to a shared dimension from my cube the publication worked.
