### ISSUE TITLE
"Dynamic properties" tab keep jumping to "Term" tab

### ISSUE THREAD

**Issue by sam-e-ch** [zazuko/cube-creator#1253]
When editing a term in a shared dimension, the "Dynamic properties" tab always keep jumping to the "Term" tab.
This makes it impossible to edit the dynamic properties.

To reproduce
1. open a shared dimension and edit an existing term (e.g. https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!zolltarifnummer/terms/dimension!!zolltarifnummer!!440121/edit)
2. click the "Dynamic properties" tab
3. wait for a short (random) time
4. the "Term" tab is active again

I tested this on both Edge 101 and Firefox 91.

**Comment by Rdataflow** [comment]
[screencast.webm](https://user-images.githubusercontent.com/26090254/176887805-67de81e1-d5c8-48a8-9dfc-0e985e033d4a.webm)

**Comment by PDumasBAR** [comment]
I see this bug only with existing terms.
With a new term, not yet saved, it is possible to display the dynamic property tab and fill it.
Hope it help to solve the bug

**Comment by tpluscode** [comment]
Closing in favor of https://github.com/zazuko/cube-creator/issues/1272
