### ISSUE TITLE
publish fails due to missing `{schema,dcterms}:identifier`

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#1258]
followup of #1252 - nb: thanks for fixing that one 🚀 

on behalf of @ortnever reporting
publish still fails 
- message: missing `schema:identifier`
- actual check: `dcterms:identifier`

see https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/30743#L145

**Comment by tpluscode** [comment]
To clarify, the check is indeed looking at `dcterms`. The validation message is misleading, which I will correct right away.

Regarding this very cube, it still has the `<http://purl.org/dc/terms/identifier> "ubd0104" ;` property in cube metadata. Once removed, it should publish without issues.

**Comment by ortnever** [comment]
Thank you @tpluscode . I removed the property and could save the metadata. The same happened in PROD but I could solve it by the same way.

**Comment by tpluscode** [comment]
By the way. Where did you export the `udb104prod` project from?

**Comment by tpluscode** [comment]
Ok. Let me close this issue the and I will have another look at import/export
