### ISSUE TITLE
Use cube.link shapes for validation

### ISSUE THREAD

**Issue by semanticfire** [zazuko/cube-creator#1262]
As per notice from @Rdataflow the shape used by the CLI:

https://github.com/zazuko/cube-creator/blob/2f0ee4dfc8c7c2352772bf415cac0515a877a092/cli/shapes.ttl

Is not in sync with the shapes from the cube.link validation shapes.
Ideally, this shape is imported from cube.link instead of separately maintained.

**Comment by l00mi** [comment]
We will refrain from including from the external source, as this will introduce unexpected, or uncontrolled behaviour (in regard of deployments) to the cube-creator. (Also are the shapes potentially in key parts slightly different for implementation details.)

The goal should be to have more regular and versioned cube.link publications, and state also in cube-creator which of the cube.link version is currently in action.

**Comment by tpluscode** [comment]
What is the point of maintaining and publishing cube shapes in the spec if we duplicate the effort and risk a different result. IIUC discrepancies have already been found between our shapes and the "official". 

We'd better work together to have only one source for cube validation, no?

**Comment by l00mi** [comment]
Yes, I absolutely agree that it should be based on this shapes, and ideally automatically can be kept in sync, e.g. through automated pull-requests, which allow to move to a specific version, or through a npm package include, but which needs to be manually updated to new versions. (A upgrade can not happen unattended).

But we need to assure that changes are always extremely transparent and also clearly documented, and announced.
