### ISSUE TITLE
Shared Dimension - Term edition - Dynamic properties tab is inaccessible

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1272]
Cube Creator INT version: 1.12.6
I think this bug was there in the past, and was either corrected or is still there now.
When clicking on Dynamic properties -> the display comes back to the Term tab:
![image](https://user-images.githubusercontent.com/6167669/185182548-e76cd614-db0f-43e8-af58-5979278593dc.png)

From this page:
https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!warenkorbzoll/terms/dimension!!warenkorbzoll!!jq11c/edit

**Comment by FabianCretton** [comment]
@tpluscode @l00mi any time frame to get those tabs working ? as we are working on those these days to create shared dimensions and hierarchies.
Thanks

**Comment by tpluscode** [comment]
It’s in progress already and well advanced. Should be possible to finalise on Monday


On 26 August 2022 at 11:41:31, Fabian Cretton ***@***.***) wrote:

@tpluscode @l00mi any time frame to get those tabs working ? as we are working on those these days to create shared dimensions and hierarchies.
Thanks
