### ISSUE TITLE
Shared Dimension - Term edition - Only the URL of the term displays in the edition window

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1276]
I did create a Shared Dimension from a .trig file: TEST environment, [Greenhouse gas emission sectors according to the CO2 Ordinance test1_gen_fab](https://test.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!gas_emission_sectors_test1_gen_fab)

When editing a term, only the URL is displayed, but nothing else:  
![image](https://user-images.githubusercontent.com/6167669/186161621-60f0961a-8763-41a4-8ca3-ba572353d7dc.png)

Could it come from the fact that the term has no schema:validFrom triple ?   

I did upload a new version of my .trig file, with schema:validFrom this time, and there, it works: [Greenhouse gas emission sectors according to the CO2 Ordinance test1_gen_fab](https://test.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!gas_emission_sectors_test2_gen_fab)

The 2 trig files:
[Shared Dimension Greenhouse gas emission sectors - 08.22.zip](https://github.com/zazuko/cube-creator/files/9402637/Shared.Dimension.Greenhouse.gas.emission.sectors.-.08.22.zip)

**Comment by FabianCretton** [comment]
More information as the problem came up today on INT as well:  
I had that problem describe here above, on TEST, with the given version of the dimension.
I thought I solved that by adding the schema:validFrom to the dimension itself and all terms, and the  term edition was working propertly on INT, for that dimension for instance:
https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test3_gen_fab

But just now, I saw that only the URL of a term is displayed:
![image](https://user-images.githubusercontent.com/6167669/186912400-a0ad148b-0334-4173-8189-a49c091e91a1.png)

As it was working properly this morning, and no more now, I can just say that in the meanwhile I have edited the shared dimension to add its name in 4 languages.

**Comment by ortnever** [comment]
I see also only the URI in the cube Designer (INT). Should I publish the shared Dimension on PROD to see the labels?

![image](https://user-images.githubusercontent.com/79834090/186935020-73b1138f-c621-4af9-9cbb-53ec5e1a6fd5.png)

**Comment by FabianCretton** [comment]
@l00mi It would be great to get a clear explanation about why a Shared Dimension (and maybe its hierarchy if it exists) must be published on PROD even if we are working on a cube on INT. I mean, what is needed on PROD for the Cube Creator and Visualize regarding those Shared Dimensions/Hierarchies. Thanks

**Comment by FabianCretton** [comment]
@l00mi do you have any timeframe for solving this ? 
As we need to make a correction on one term and we can not access the edition window for the shared dimension on INT as described [here above](https://github.com/zazuko/cube-creator/issues/1276#issuecomment-1228478055).
Thank you.

**Comment by l00mi** [comment]
These terms get "dereferenced", which means they get checked out at the URL for a label. As long as the URL is not on Prod it can not be dereferenced. What speaks agains putting the shared dimensions to PROD already?

**Comment by l00mi** [comment]
Btw. currently we did not prioritize this.

**Comment by FabianCretton** [comment]
Thank you Michael
Then I think that this whole Shared Dimension feature needs some clear explanation.
Especially that we are using it a lot these days and get blocked at some points.
I am not talking about new things to prioritize, but about how do I use the feature, right ?
I actually do not understand the link between the Shared Dimensions on the different environments.
Could you clarify this and explain how we use it, and the same for the hierarchies I guess ?
Thank you

**Comment by l00mi** [comment]
Lets a have call for it, might be easier?

**Comment by FabianCretton** [comment]
Yes, do you want to send me a link ?

**Comment by FabianCretton** [comment]
Here is a recap of the situation after a call with Michael.
The current problem is that I can not edit some terms as the edition window only display the URL of the term and not the other fields. See the examples given here above.
Michael think that this could be related to the fact that the dimension is not published on PROD, but this seems not the case as for other dimensions, not on PROD, it works. Take "Pollutant" for instance:
https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!pol01air

Michael says that a shared dimension URL should not be linked to a plateform (as https://int....)
But as we can see here, the current terms have an URL based on the plateform:
![image](https://user-images.githubusercontent.com/6167669/189824688-fd028e16-2edc-4df3-8c1f-35c80ffc6941.png)

However, I do think that the shared dimension feature should not require the shared dimension to be on PROD for that feature to work -> we should talk about this.
Especially that the functionnality currently works in some case, not in others -> there is certainly a bug here.

I propose that Zazuko has a quick look at why the edition of the term do not work ?
Thank you

**Comment by FabianCretton** [comment]
I have two more questions about Shared Dimension, as this feature needs to be "correctly" finalized:
- how is the list of Shared Dimension ordered ? shouldn't there be an Order By the name (as the list on INT becomes longer it becomes hard to find the dimension we want to edit)
- I understand the "Term properties" of a dimension meta-data, to define the properties that can be added to the terms. When a Shared Dimension has some "Term properties", than those properties will appear on the "Dynamic properties" tab when editing a term. Is that correct ?
If that is correct, there is a strange behavior for the "Heavy Metal":
https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!el01
as that dimension has no term properties, but the terms have a few "strange" properties on the "Dynamic properties" tab:
![image](https://user-images.githubusercontent.com/6167669/189829621-eed1c089-2686-4439-a05d-3b52a7db7f19.png)

**Comment by FabianCretton** [comment]
@l00mi @tpluscode 
Any update about the edition of terms that do not work (only the label is displayed - see here above) ?
As you know, BAFU is currently working on adding many datasets as this is the only way to prove that the platform is "useful".
(@ortnever for Info)
I need to modify some Shared Dimensions and I guess I can currently only:
- either ask for read/write rights in Stardog to correct them via SPARQL updates
- mark them as deprecated, export them, correct the trig, create a new one -> and then recreate the mapping in the cubes

**Comment by FabianCretton** [comment]
Another information from today, for your "debugging": 
A term was added manually, the 38: https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab/terms/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab!!38/edit

For that term, the edition window does display correctly.
But for the other terms, only the URL is displayed as described here above.
It thus seems that the problem is "term-specific" ?

Please @l00mi @tpluscode let us know when you will work on this

**Comment by tpluscode** [comment]
@FabianCretton I identified the problem and I just completed a fix. Will try to get it deployed as soon as possible

**Comment by FabianCretton** [comment]
@tpluscode today I saw that a new version was deployed: 1.12.8,
But the behavior seems the same.
Dimension: https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab
Editing any term just displays the URL and loops without any result (except term 38 that displays correctly as explained here above)
![image](https://user-images.githubusercontent.com/6167669/194467663-9ca9f51e-d7b6-4d44-a516-073544dff052.png)

**Comment by FabianCretton** [comment]
Still same behavior with 1.12.9:
Dimension: https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab
