### ISSUE TITLE
[TEST env - INT also maybe] Download of a Shared Dimension super-slow or even time-out

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1277]
The download of a shared dimension is super slow (even for one shared dimension with only one term), 

https://test.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!test

Just pressing the "download" button.

A printscreen of the download operation that is running since 2 minutes on another shared dimension:
![image](https://user-images.githubusercontent.com/6167669/186164223-a4fb613a-521c-41ff-9416-b4d673b0c296.png)
The result:
![image](https://user-images.githubusercontent.com/6167669/186164425-5918f974-1846-45d2-9cbb-f5a1c7515f71.png)

I did a quick trial on INT, the download was super slow but finally worked.

**Comment by l00mi** [comment]
This seems a problem which is introduced with Stardog 8.x.x. We will need to schedule this later.

**Comment by l00mi** [comment]
@FabianCretton is this blocking on your side for concrete tasks?

**Comment by FabianCretton** [comment]
@l00mi this is not blocking, thank you for taking care of this when possible :-)

**Comment by l00mi** [comment]
@FabianCretton can you please test again now wit the updated store on TEST and INT?

**Comment by FabianCretton** [comment]
@l00mi it seems fine now, thanks
