### ISSUE TITLE
Mapping to shared dimension problem/bug (and also a how-to question)

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1288]
First a how-to question, then the errors I encountered with the Cube Creator on INT; version 1.12.6

Thomas is [asking me](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/367#note_8457) to create an example cube with a switzerland-canton-municipality hierarchy.
He proposes to create a dataset about inhabitants for municipality, canton, country.

What is the correct way to design such a dataset so that the cube creator and visualize will handle the hierarchy properly ?
I see that the 3 Shared Dimensions already exist for  municipality, canton, country.
And I see that a hierarchy already exists: "Switzerland - Canton - Municipality"
My question is about how to design one ore 3 dimensions for the the "region" ?

Maybe there could be a simple answer: as the shared dimension and the hierarchy exist, is there a working cube example of this ?
(but if so, why would Thomas ask me to create one...)

I tried an approach with [this cube](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-hierarchy-test-switzerland-canton-municipality-wkeerq8rxn6/metadata?creator=me): as I saw that one single dimension could be linked to more than one shared dimension, it seemed to be the way to go.
I did create the joined .csv file: 
[SuisseCantonMunicipality_population.csv](https://github.com/zazuko/cube-creator/files/9477560/SuisseCantonMunicipality_population.csv)
In that .csv, each line is a population value for either Switzerland, a canton or a municipality.
I have one BFSIdentifier column  which contains the identifier that does match the identifiers of those 3 shared dimensions:
- CHE for Switzerland in the [Countries shared dimension](https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/https:!!!!ld.admin.ch!!dimension!!country)  
- bfs number for cantons in the Canton shared dimension
- bfs number for municipalities in the Municipalities shared dimension
This is thus a mix of string (CHE) and integer, I was not sure about how to handle that and I gave the columns a string datatype.

The problem: on the Cube Designer, I edited the BFSIdentifier dimension, gave it a nominal scale of measure.
Then I edited the mapping to shared dimension, and here i was not sure about how to proceed to perform the auto-fill mapping.
I had a few errors, that I describe here under, and now the link to shared dimension window stays blank:
![image](https://user-images.githubusercontent.com/6167669/188135857-a29a85df-38f9-4ffc-9159-eb53829b4efb.png)

I did:
- add the 3 shared dimensions on top of the window
- then click on the Autofill button at the bottom of the screen
- there, I had to choose ONE shared dimension, so I thought I would have to do it 3 times, one for each shared dimension.
But I did launch it for the "municipalities first", and I got this "Unknown error":
![image](https://user-images.githubusercontent.com/6167669/188137405-43b8d81f-fe74-47aa-93f9-9390f3aa2096.png)

I am thus describing two problems here:
- why did the "Map terms from a shared dimension" action result in a "Unknown error"
- why does the link to shared dimension window stay blank currently -> I can no more work on that cube.

If my approach is wrong (having a country, cantons and municipalities identifiers in a same dimension - also mixing one string identifier with numerical identifiers) -> please let me know how to do it properly

If my approach is correct, then I guess the fill "Auto-fill from Shared Dimension" is buggy ? or does it not work when 3 shared dimensions are concerns ?

Anyway, thank you for your help, and hoping we can solve this "quickly"

**Comment by FabianCretton** [comment]
As a complement: it seems that the auto-fill function is buggy, even when only one Shared Dimension is concerned.
Today I tried a dataset with only municipalities.
The auto-fill gave an error: Unkown error as on the printscreen here above.
It means that the autofill is having a problem that is not related to the fact that I wanted to map to three different dimensions.

Can the problem come from the number of municipalities ?
After that, the mapping edition is a blank window as described above
Can be seen here:
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-hierarchy-test-8-switzerland-canton-municipality-padp57gyygl/metadata/dimension/cube-project!!fab-hierarchy-test-8-switzerland-canton-municipality-padp57gyygl!!dataset!!dimension-metadata!!bfsidentifier/map

I need to work on a few datasets, and this mapping is becoming a real blocker.
Thank you for your help

**Comment by FabianCretton** [comment]
@tpluscode here is a new simple cube, with only municipalities
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-1-shared-dimension-mapping-l6wmkznepxn/metadata

It allows to easily reproduce the bug, here is what I did:
- create the project, upload that .csv
- do a simple observation table, transform
- municipalities identifier are in the "bfsidentifier" column.
- in Cube Designer: just edit the bfsidentifier column to set a "nominal" scale of measure
- click the "link to shared dimension" icon, launch a auto-fill on the Municipalities shared dimension
- this gave the same "unknown error" as in the print-screen here above.
- and now, one opening the "link to share dimension" window, it is blank as in the print-screen here above

**Comment by FabianCretton** [comment]
@tpluscode I see your "eyes" emoji, what is the meaning, you can not reproduce it ?

**Comment by tpluscode** [comment]
Is this still an issue @FabianCretton?

I just tried this dataset in TEST and also found another incarnation of this cube successfully mapped to the dimensions on INT.

**Comment by FabianCretton** [comment]
@tpluscode yes, I tried a new project following the steps I mentionned here above, and same problem
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-2-shared-dimension-mapping-b6qnnk1zor2/metadata/dimension/cube-project!!fab-test-2-shared-dimension-mapping-b6qnnk1zor2!!dataset!!dimension-metadata!!bfsidentifier/map-import
