### ISSUE TITLE
Cube Designer - 2 messages need clarification

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1290]
We have a cube with two messages that we do not understand in the Cube Designer:
Cube: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!tobiasbesch1116institutionellde-7xyqxydao50/metadata

This cube is created by Tobias who is learning the Cube Creator, it is not "perfect", but still, we do not understand the 2 displayed messages:
![image](https://user-images.githubusercontent.com/6167669/188887364-10137e07-a0d4-4c36-8880-f5d087595bf9.png)

- Observation identifiers are not unique
Is this message related to the identifier of the Observation table (on the CSV Mapping tab), or related to the meta-data of the dimensions and the 'dimension type' -> key dimension ?
There could be a problem as the key dimensions should be unique, but they are currently a lot of strings, so there might be something not correct.
Anyway, the cube will not stay "as is", but knowing where the "Observation identifiers are not unique" message come from is someting i would need to understand

- value missing
This is strange, as if you display the 33 observations, all cells have values
So what is the reason ?

Thanks for the clarification

**Comment by l00mi** [comment]
Observation identifiers are not unique: This is an important one, this means that two lines will generate the same identifier, effectively merging two observations.
Value missing

**Comment by FabianCretton** [comment]
@l00mi could someone have a closer look, because I looked once again and i do not see any reason for those 2 message to appear:
- the csv has 33 lines, the Cube Designer has 33 observations, a table in visualize has 33 lines
https://test.visualize.admin.ch/en/create/DMEExrDWZCAG?dataSource=Int
So why the "Observation identifiers are not unique"
- Cube Designer: display all 33 lines -> all values are given

We need to know if it is a bug of the tool that displays warnings when there is no reason for that, or if there is a problem but I do not see it.
Especially that different people are now using the tool, and ask questions.

**Comment by tpluscode** [comment]
This is in fact a bug where existing errors are not cleared when they no longer apply.
