### ISSUE TITLE
Dates are not correctly interpreted by the harvester Opendata

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1293]
It seems that some dates are not correctly interpreted by the harvester opendata for Lindas. The following sample are from cube "The Stapfer-Enquête" in Production:

<dcterms:issued xml:datatype="http://www.w3.org/2001/XMLSchema#date">
  2016-06-30
</dcterms:issued>

<dcterms:PeriodOfTime>
  <schema:endDate xml:datatype="http://www.w3.org/2001/XMLSchema#date">
    1799-12-31
  </schema:endDate>
  <schema:startDate xml:datatype="http://www.w3.org/2001/XMLSchema#date">
    1799-01-01
  </schema:startDate>
</dcterms:PeriodOfTime>

The only date that is correctly interpreted by the harvester is :
<dcterms:modified xml:datatype="http://www.w3.org/2001/XMLSchema#dateTime">
  2022-05-23T08:17:21.556Z
</dcterms:modified>

We must export dates as XMLSchema#dateTime, not as XMLSchemaDate.

**Comment by l00mi** [comment]
@PDumasBAR what is the state here? Still any action from our side necessary?
