### ISSUE TITLE
Shared Dimension "Heavy Metal" - strange behavior to clarify

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1298]
I understand the "Term properties" of a dimension meta-data, to define the properties that can be added to the terms. 
When a Shared Dimension has some "Term properties", than those properties will appear on the "Dynamic properties" tab when editing a term. Is that correct ?

If that is correct, there is a strange behavior for the "Heavy Metal":
https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!el01
as that dimension has no term properties, but the terms have a few "strange" properties on the "Dynamic properties" tab:
image
![image](https://user-images.githubusercontent.com/6167669/191897748-e58a08ca-51b4-4c0a-873b-82d00b9140e5.png)

**Comment by l00mi** [comment]
This was a hiccup in the data. We just create a new Dynamic Term, which then made show up the once before not shown, which in turn allowed us to delete all (accidentally hidden) Dynamic Term Properties and so could solve the problem.
