### ISSUE TITLE
Edit shared Dimension - Error  when modifying Term properties

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1299]
I want to modify the term property "Alternate Name" for the shared Dimension "Pollutant groups" but I get an error when I try to change the "Value Type". I first entered "Literal" and would like to remplace by multilingual "Lang string" but I get an error.

![image](https://user-images.githubusercontent.com/79834090/191967704-a293c933-c1bb-49ae-888b-6f3e57e98aa4.png)

**Comment by FabianCretton** [comment]
@ortnever est-ce l'erreur ne vient pas du fait que tu n'as sélectionné aucune langue ?
@l00mi Le manque de clareté de certains messages d'erreur est vraiment un problème pour le end-user

**Comment by l00mi** [comment]
@FabianCretton I agree.

**Comment by ortnever** [comment]
Until now we could not enter different languages (see #1311). But this issue has just been closed. I hope that will solve this problem too. I will test as soon as the fix is also on INT.

Mais des messages plus clairs seraient les bienvenus !
