### ISSUE TITLE
Mapping to shared dimension: issue when adding a term manually

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1300]
A first version of a project and a Shared dimension was created and published.
Project:  [UBD000502 Treibhausgasemissionen nach Sektoren und Gasen (CO2-Verordnung)](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd000502-treibhausgasemissionen-nach-sektoren-und-gase-co2-verordnung-oxwgjodd83e/edit)
Shared Dimension [Greenhouse gas emission sectors according to the CO2 Ordinance](https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab)
With the mapping from the 'Sector' dimension to that shared dimension.

The visualization was working fine.

Then, a term was missing (both in the data and in the shared dimension)
It is the term[ with id 38](https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab/terms/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab!!38/edit), that was added manually to the shared dimension.
To be noted in regard of that issue [Only the URL of the term displays](https://github.com/zazuko/cube-creator/issues/1276): it is the only term in the list that can be edited (this term added manually can be edited, the others imported from a .trig are buggy).

After that, the new csv was uploaded. Dataset transformed.
And the mapping was done manually for that term:
![image](https://user-images.githubusercontent.com/6167669/191987849-8e4ccc68-25ce-486f-a0df-06b266f728e6.png)

A first strange thing, maybe an hint about the bug: we see on that screen that the term that **is not** working does display a label, whereas the terms **that do work** display an url.

A new transformed was performed.
The mapping seemed to work:
![image](https://user-images.githubusercontent.com/6167669/191988277-4f60a49f-270d-4af2-a440-37edfc5d2cde.png)

However, in visualize, that term 38 do not appear!

What was observed:
- when exporting the project, all terms have this kind of triple except the 38:
`https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test4_gen_fab/37> a prov:Entity .`
But I did add the triple manually and create [another test project](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-ubd000502-debug-bnxdqgamkq5/csv-mapping) -> Visualize still doesn't display 38.

Other strange observation:
- the exported project, .trig file, contain rests of a former mapping:
a bunch of prov:Entity that are no more actual:
`<https://ld.admin.ch/cube/dimension/ghg_emission_sectors_co2_ordinance_test3_gen_fab/3> a prov:Entity .	`

**Comment by ortnever** [comment]
For the example Fabian gave, that was my mistake. I had simply forgotten to indicate the "Parent" of this term under the dynamic properties. 

Project: [UBD000502 Treibhausgasemissionen nach Sektoren und Gasen (CO2-Verordnung)](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd000502-treibhausgasemissionen-nach-sektoren-und-gase-co2-verordnung-oxwgjodd83e/edit)
Shared Dimension [Greenhouse gas emission sectors according to the CO2 Ordinance](https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!ghg_emission_sectors_co2_ordinance_test4_gen_fab)

I don't know if other problems have been raised via this issue so I'll let you decide whether it can be closed or not.

**Comment by FabianCretton** [comment]
As explained by Veronique, the problem was on our side.
I open another issue about the comments here above, about triples  prov:Entity that remain strangely in the cube
