### ISSUE TITLE
Cannot delete cube

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1320]
I'm trying to delete cubes in Stardog Studio with the [ad hoc query],(https://github.com/zazuko/cube-creator/wiki/Manually-removing-published-cube)

Even for small cubes (<1000 observations, <10'000 triples) Stardog fails with the error :

QEQOE2: com.complexible.stardog.plan.eval.ExecutionException: Query execution cancelled: Execution time exceeded query timeout 120000

Tested so far:
<https://environment.ld.admin.ch/foen/ubd000501/1>
<https://environment.ld.admin.ch/foen/ubd000501/10>
<https://environment.ld.admin.ch/foen/ubd000502/1>
<https://environment.ld.admin.ch/foen/ubd000502/10>
<https://environment.ld.admin.ch/foen/ubd000502test/1>
<https://environment.ld.admin.ch/foen/ubd000502test/3>
<https://environment.ld.admin.ch/foen/fab_ubd000502_debug/1>

**Comment by l00mi** [comment]
Can you try to add "LIMIT 10000" to the end, and see if that works? If so, we would need to delete in Badges.

**Comment by PDumasBAR** [comment]
Salut Michael,

Désolé ça ne marche pas. Il manque peut-être quelque chose :

    ?set cube:observation ?observationS .
    ?observationS ?observationP ?observationO .
  }
}
LIMIT 10000


QE0PE2: com.complexible.stardog.plan.eval.ExecutionException: Encountered " "limit" "LIMIT "" at line 61, column 1.
Was expecting one of:
    <EOF>
    ";" ...
    ";" ...

A+
Pierre

**Comment by tpluscode** [comment]
Do I recall @l00mi that you improved the documented query to remove cubes?

**Comment by PDumasBAR** [comment]
Salut Tomasz,



Michael wrote a new version of the delete query and updated the doc.

I think everything is ok.



Kind regards and happy new year

Pierre

**Comment by tpluscode** [comment]
Glad to hear. Happy New Year to you too 🎆
