### ISSUE TITLE
Add LD independent resources, like CSV for opendata.swiss

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#1332]
Currently two "Resource" are added per dataset in opendata.swiss through the harvester, pointing to visualize and to the SPARQL endpoint.

Often data providers have other Resource they like to share. The goal is to be able to add these additional Resources in Cube-Creator to be harvested by opendata.swiss.

**Comment by tpluscode** [comment]
Could you add some more detail @l00mi ?

How do we prioritise this?

**Comment by l00mi** [comment]
That is a request from Pierre, please check with @dabo505.

I added some details at the top.

**Comment by MartinaElsawy** [comment]
Dieses Thema wird im Issue: https://gitlab.ldbar.ch/zazuko/misc/-/issues/170 behandelt im Rahmen des Cube Creator BAFU Vertrags. Abgesprochen mit Claudio und Pierre.
