### ISSUE TITLE
Metadata edition of an exported/imported Cube Project

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1338]
I did export this project: https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-foreign-trade-test-2-mg1d36d4vwv/metadata
And imported it without modifying the .trig: 
https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-foreign-trade-test-3-a1jebdgd4vn/metadata

And when clicking on the metadata, there is this error: "failed to load editor"

I often export/import projects, never had this problem.
This is a very new version of Cube Creator I guess, version 1.12.9

Also note the small size of the string field and the big size for the language tag

![image](https://user-images.githubusercontent.com/6167669/203797135-27522d55-3aae-4454-8378-5cae78001fec.png)

**Comment by tpluscode** [comment]
The failure must have been something temporary. I opened this just now and it loaded correctly.

Will look into the sizing change.
