### ISSUE TITLE
No publishing profiles available

### ISSUE THREAD

**Issue by CDiGallo** [zazuko/cube-creator#1347]
Hi,
when creating a new cube-project on INT, one cannot choose a publishing profile. So we are not able to create a new cube.

Thanks

**Comment by tpluscode** [comment]
Sorry about that. I'm already looking into this, and why it worked on the TEST environment but not the others

**Comment by CDiGallo** [comment]
Wow, that was fast :)
Thank you for looking into it. We have a student which make some kind of practical work. And he needs cube-creator for his project. So let me know, when you fixed it.

**Comment by tpluscode** [comment]
A problem which affected multiple functionalities. Luckily the fix was also simple. Working again in 1.13.2

**Comment by CDiGallo** [comment]
Thank you very much for the fast response Tomasz!
