### ISSUE TITLE
Cannot publish a cube : cube:Cube must point to a valid cube:Constraint

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1365]
Project : [BAZL_Verkehrsleistungen_Karten_1_Fichier](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bazlverkehrsleistungenkarten1fichier-p1pwzv465lr)

Cannot publish the cube in INT !
Error message :

![image](https://user-images.githubusercontent.com/35593772/215546102-61bdcf8e-d45b-4cf4-a29f-7ea9cc5ff116.png)

Save project setting give another error :
![image](https://user-images.githubusercontent.com/35593772/215545850-b403675f-4573-4407-8099-8b5a6614d06f.png)

**Comment by tpluscode** [comment]
The two errors appear unrelated. I found and fixed the second (project settings).

Will continue troubleshooting the second

**Comment by tpluscode** [comment]
I found the problem, related to the non-alphanumeric characters representing the mathematical inequality operators (`>=` and `<`). When a Cube table is created with the `Create table from selected columns` button, the same target property `bewegungen-lfz-86-to` is used for both columns. This caused the mapping to malfunction down the line. 

When adding a single column such ends state is prevented with an error `Target property already mapped` but apparently not above apparently. I will proceed with an appropriate safeguard

Regarding the cube project in question, you will be able to delete these two columns and create them again with the desired target property name to make the generated cube functional.

**Comment by PDumasBAR** [comment]
Hi Tomasz,

Yes, I have the problem in Test and the Cube-Creator duplicate the observations, once for each column linked to the same property. And the publication was possible ???

In INT we have seen the problem and try to update the properties, but we didn't see our modifications were not really applied.
I just delete the bad properties and recreate them manually and it works fine, transformation, publication, etc.

Thank for your help
Pierre
