### ISSUE TITLE
Auto-fill Shared Dimension Mapping fails - unknown error

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1372]
Véronique and myself tried a few 'auto-fill' today, with municipalities, without success:
![image](https://user-images.githubusercontent.com/6167669/217772275-b603d39b-6798-40a7-b439-c88a41264a38.png)

Cube Creator version 1.13.3 (4325eba)
Last trial - Project: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabdemosdmunicipalityfrom-scratch-1vn3pg03mly/metadata

Can you identify what is happening as we do not get any useful information ?

**Comment by tpluscode** [comment]
The problem is with the query which attempts to match and insert the new mapping entries in one go. Given large enough datasets (in this case 1600 unmapped values and 2100 municipalities) the query times out

Separating the query which finds municipalities appears to help. Will have a fix soon
