### ISSUE TITLE
Changing the name of a project?

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1375]
I wanted to change the name of mine project but I get an error message. Is this normal? I thought that only the project ID could not be changed once the project was created.

![image](https://user-images.githubusercontent.com/79834090/218405197-4dbe0f4d-df09-4ba0-867a-f77c03d7205c.png)

**Comment by tpluscode** [comment]
I believe that is the same problem which has been reported in #1365 

The fix is ready and we should publish soon

**Comment by tpluscode** [comment]
I just deployed a new version with the fix
