### ISSUE TITLE
Publication fails in different project from BFE

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1382]
**Describe the bug**
Several projects of Ms Jana Stojanovic cannot be published.
I can't interpret the log which shows an error I don't understand.

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [x] Publishing
* [ ] Other

**Relevant links**
Project [OGD101](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bfeogd101gasimportexport-qr7pov4nxqv/publication)
Log [47677](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/47677)

**To Reproduce**
1. Select the project OGD101 and start a publication

**Expected behavior**
Publication failed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Edge

**Comment by tboeni** [comment]
I experience the same issue since yesterday as well, each of my publications fails regardless if they are new projects or old ones that worked fine before.
![failedjob](https://user-images.githubusercontent.com/111350367/222084037-c9e9ad61-6346-4e3d-94a0-66e523f6efef.PNG)
