### ISSUE TITLE
Relax the shared dimension identifier restriction

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#1386]
**Is your feature request related to a problem? Please describe.**
It is a common practice ("eCH standard"?) to use `camelCase` identifiers for concepts. Currently, cube creator only allow lower case letters

**Describe the solution you'd like**
Relax the constraint on creating shared dimensions and terms

**Additional context**

@l00mi is there a documentation somewhere which recommends the use of `camelCase` in URIs?

**Comment by dabo505** [comment]
@tpluscode Please go ahead with this, we need it for the project with agroscope. Thank you!
