### ISSUE TITLE
Some metadata can't be set : <Initialising component>

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1390]
**Describe the bug**
Sometimes it's not possible to set a list related metadata at the cube level.
A click on the plus sign display the message "Initialising component" but the list is never displayed.

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [ ] Publishing
* [x] Designing

**Relevant links**
[Cube-Creator project OGD111](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bfeogd111gasnettoimport-xenrbd8jova/metadata/edit)

**To Reproduce**
1. Open the project in the Cube-Creator
2. Go to the designer
3. Try to insert "Category" or "License"

**Expected behavior**
The list of options for the metadata display the available options

**Screenshots**
![image](https://user-images.githubusercontent.com/35593772/223387077-8b7921b4-582f-456f-9696-c8991f4de4fa.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Edge, Firefox
 - Cube-Creator version 1.13.3 (4325eba)

**Additional context**
Not the only cube from Jana where it happens (OGD106, OGD101, etc.).
I think it's a general bug. It happens also in old cubes.

**Comment by tpluscode** [comment]
The components are populated directly from Lindas. The options are provided by a SPARQL query. I've just tried various browsers and operating system and the dropdowns loaded fine in every case.

It may be possible that this happens at times when Lindas is under high load? I can find these errors in monitoring logs but unfortunately the do not provide any additional details

**Comment by PDumasBAR** [comment]
Hi Tomasz,
It seems to work better. No more "Initialising component" or just a short time for long lists.

But the status list (draft or publish) is now empty. Tested on different cubes, in INT and PROD. 
![image](https://user-images.githubusercontent.com/35593772/224288259-f9566e31-3b11-4d84-8fd2-b7fd83fbd7d0.png)
The creativeWorkStatus property is still visible in the raw RDF of an existing cube.

**Comment by AFoletti** [comment]
A similar "empty dropdown" issue is present with the "publishing profile" when creating a new cube
![image](https://user-images.githubusercontent.com/691243/224607797-dfa45a59-0323-4ef5-b781-4ace27cde7c4.png)

This acually makes it impossible to create new cubes on both INT and PROD...

@aressera FYI

**Comment by AFoletti** [comment]
Both the issue last described by @PDumasBAR and the one in my comment above looks like to have "solved themselves". It is once again possible to correctly create a new cube on INT and PROD and the drop-down are being populated.

I would like to kindly point out that such instabilities are giving quite a blow to a possible wider use of the CubeCreator within our office...

**Comment by dabo505** [comment]
@AFoletti Thanks for reporting this. 
@tpluscode Any ideas where this came from?

**Comment by tpluscode** [comment]
Very sorry about this. While the direct cause was failure to authorise the API calls which retrieve data for the forms, the 
underlying issue can be traced to the build which was slightly random. That is why releasing some unrelated changes also fixed this and similar problems reported in other tickets.

I do not know exactly why this randomness occurs during build but I know the library which is the culprit and I have an idea how to prevent it from happening again.

**Comment by dabo505** [comment]
Thanks for the feedback!
