### ISSUE TITLE
Impossible to link shared dimension

### ISSUE THREAD

**Issue by AFoletti** [zazuko/cube-creator#1393]
**Describe the bug**
On both INT and PROD, it's impossible to correctly link a SharedDimension to an attribute because the search box does not return any result.

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [ ] Publishing
* [x] Other

**Relevant links**
[Cube project on INT](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bfeogd100kennzahlensharedmobility-ddablvrpknd)

**To Reproduce**
1. Go to the Cube Designer
2. Switch to DE if needed
3. Open the dialog to link the "Region" property to a SharedDimension
4. Try linking it to the "Agglomerationen BeSA" SD
5. The searchbox does nothing, making it actually impossible to link

**Expected behavior**
The searchbox actually works, allowing me to pick the needed SD for the project

**Screenshots**
![image](https://user-images.githubusercontent.com/691243/224607010-dccfe527-0641-4212-a43a-7a1253a2439e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**
Both on INT and PROD

Pinging @aresssera for her reference

**Comment by FabianCretton** [comment]
@AFoletti are you talking about the auto-fill functionality ?
If yes, did you wait that the Shared Dimension drop-down box is filled ?
When we open the window, there is this icon showing that the shared dimension are currently queried:
![image](https://user-images.githubusercontent.com/6167669/226277079-0a1a2f55-aed8-44c1-ae05-99ba34d30063.png)

Once this is done (a loop icon replace the circling arrows), when clicking in the field, the shared dimensions are displayed (strangely, not in an alphabetical order), and you can search for your 'agg':
![image](https://user-images.githubusercontent.com/6167669/226277358-f1ab4704-6b41-4b8b-ab1c-53ba790032d6.png)

I guess that when running the auto-fill, you might then encounter the bug I discribed in #1398

**Comment by AFoletti** [comment]
@FabianCretton actually, the searchbox was dead (without the spinning arrows). It was not about waiting or not ;).
However, this issues seems to have "resolved itself" in the same way it's once again possible to create new cubes (see this comment here https://github.com/zazuko/cube-creator/issues/1390#issuecomment-1465492121).

I am closing this one since it works once again. But the unrealibility of the CC is not funny at all
