### ISSUE TITLE
Auto-fill Shared Dimension Mapping INCOMPLETE

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1398]
**Describe the bug**

Running an auto-fill for municipalities, only part of the municipalities where mapped, not all.
This could be a follow-up of: https://github.com/zazuko/cube-creator/issues/1372

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [ ] Publishing
* [x] Other

**Relevant links**
 
See the project: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabdemosdmunicipality17032023-07pavj8mrj/metadata

**Comment by FabianCretton** [comment]
@tpluscode any timeline that we can expect a correction of this functionality ? 
Thanks for the update

**Comment by tpluscode** [comment]
While looking into this today I found a possible performance improvement but I also need to ask whether you unchecked the box labeled **Only current terms**?

I found that a lot of the municipalities in your cube are actually no longer current. That means that they have `schema:validThrough` property set to a past data and thus will be excluded from the default mapping. Example: https://s.zazuko.com/7622bK

**Comment by tpluscode** [comment]
That said, there are 2 values remaining which are not found in the municipalities dimension: `3112` and `5240`

**Comment by tpluscode** [comment]
Apparently these two municipalities are [present on PROD](https://s.zazuko.com/MbyPip) but [not on INT](https://s.zazuko.com/3qygBHy)

**Comment by FabianCretton** [comment]
Great, thank you, it also allows me to better understand how it works.
I guess we can then close this issue, but you did merge something, did you improve the performance ?

**Comment by tpluscode** [comment]
I merged on TEST but should go to INT soon, nothing against

But please keep your expectations on a reasonable level. In this process getting the unmapped values is the bottleneck and just worse the larger the cube or dimension.
