### ISSUE TITLE
Transformation timeout in PROD

### ISSUE THREAD

**Issue by AFoletti** [zazuko/cube-creator#1400]
**Describe the bug**
We configured the cube "bfe_ogd100_kennzahlensharedmobility" on INT and managed to publish it with a CSV containing arounf 500k lines (some 30Mb of data). Step 2 (transformation) took about 30 minutes.

This morning I exported the cube from INT, imported it into PROD and uploaded the very same data. I started the transformation but I get a timeout after 2h30 minutes or work.

Now: why does this cube/data combination work on INT and not on PROD?
Additionally: would it be possible to have a hint in the GUI that the process actually stopped because of a timeout (in the GUI was still "running" and I only got lucky to have someone show me the logs, otherwise I would have waited for another 4 hours...)

Thanks!

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ x] Transformation
* [ ] Publishing
* [ ] Other

**Relevant links**

- On [PROD](https://cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bfeogd100kennzahlensharedmobility-xpr57lnz4yo/materialize)
- On [INT](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bfeogd100kennzahlensharedmobility-ddablvrpknd/materialize)

**To Reproduce**
1. Go to either PROD or INT (see above) and try a transformation.
2. on PROD: enjoy the waiting...

**Expected behavior**
- I can transform the same data with the same cube configuration on both INT and PROD
- I get useful information if the transformation times out

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**
CC version 1.13.5 (16d1fae) on both INT and PROD

@PDumasBAR @aressera

**Comment by tpluscode** [comment]
Closing due to inactvity
