### ISSUE TITLE
Improve calendar fields

### ISSUE THREAD

**Issue by dabo505** [zazuko/cube-creator#1402]
It should be possible to add dates by typing them, not only by choosing them in the calendar

**Comment by tpluscode** [comment]
16h estimate is a bit of a worst-case because we use a 3rd party component and finding a replacement might not be as easy as it could be

**Comment by tpluscode** [comment]
Using the same calendar but now with the possibility to edit the selected value:


https://user-images.githubusercontent.com/588128/234010092-d927a954-485c-4ecf-9762-e98e46e99a4f.mp4
