### ISSUE TITLE
Show which fields are mandatory

### ISSUE THREAD

**Issue by dabo505** [zazuko/cube-creator#1405]
Missing language for title should make an error message (atm technical error **only** when publishing the data)
Have a precise message what is missing and where and prevent the data from publishing. 
Mark mandatory fields as such and prevent CC from doing the publication.

**Comment by tpluscode** [comment]
I would like to get more info about parts of this issue.

> Missing language for title should make an error message

This is already the case both for cube and dimension metadata. The form cannot be saved without selecting a language

> [...] and prevent the data from publishing.
> [...] and prevent CC from doing the publication.

Publication is already being prevented when metadata is incomplete
