### ISSUE TITLE
The "Swiss Franc" unit is no more there ?

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1412]
In the Cube Creator INT/PROD, when editing the metadata of a dimension, there is a drop-down list for the 'unit' (certainly QUDT), but the Swiss Franc that was there a few months ago seems to be missing.
The original value seems there: https://qudt.org/vocab/unit/SwissFranc

I had it in a Cube Created in summer 2022, and now when I save the dimension I have an error about the 'unit', and I also don't see it in the list.

Thank you for any explanation

**Comment by l00mi** [comment]
Thank you for reporting this, it seems there was a change in the QUDT file structure 15 days back. https://www.qudt.org/2.1/catalog/qudt-catalog.html

I did already adapt the imports, hopefully this is fixed later today. @tpluscode you can assign this to me.

**Comment by tpluscode** [comment]
Incidentally, I was working with the unit metadata today, and I can confirm that the Swiss Franc is available in the list of units. 

Here's a query from the same graph Cube Creator uses to find units: https://s.zazuko.com/6rMKsv

**Comment by l00mi** [comment]
@FabianCretton should be resolved, please close if so.
