### ISSUE TITLE
Cube Creator TEST - Cantons Shared Dimension problem or extremeley slow to load

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1432]
The Cantons shared dimension, on TEST, do not display for me:
![image](https://github.com/zazuko/cube-creator/assets/6167669/4ec44ada-99eb-471f-b29e-5f52bf0f1223)

Is there currently a known issue ?
It seems to work fine on INT.

**Comment by tpluscode** [comment]
I cannot exactly debug the issue but I think the query runs into some issue. Might be related to the work on the territorial pipeline. I will optimise the queries sent from Cube Creator

**Comment by tpluscode** [comment]
Fixed in current TEST deployment
