### ISSUE TITLE
Button "Update dimension metadata" not working on the "Edit raw RDF" page

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1436]
Cube Creator version 1.13.6, on FireForx 114

In the Cube Designer, when editing the metadata of a dimension, from the Hierarchy tab, the "Update dimension metadata" button does not work on the "Edit raw RDF" page. When clicking, nothing happens.
Note: if going back to "back to form (basic)" -> then the button works

**Comment by kronmar** [comment]
Similar issue in the Shared Dimensions Tab. Was trying to add `schema:hasPart` for the Ownership dimension by editing the raw RDF. Any changes won't be saved.

**Comment by Rdataflow** [comment]
@tpluscode can you fix this with prio? marco depends on this being fixed for a go live next wednesday. 
cc @ktk @claudiodigallo

**Comment by FabianCretton** [comment]
As a complement, it already happened a few months ago that a button's click was "lost", and I remember we had a talk about this with @tpluscode ...isn't there a way to make sure that this will not happen again ?

**Comment by tpluscode** [comment]
This appears to have slipped under the radar last time, never having been fixed properly when we last touched that subject @FabianCretton. 

Yes, a simple fix @Rdataflow, to be deployed ASAP
