### ISSUE TITLE
Auth token refresh

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#144]
For some reason, I have to re-authenticate every few minutes. I'm guessing it's caused by:
- a very short ttl for the auth token
- a broken refresh mechanism

@sandhose do you have any idea how we can fix that?

**Comment by sandhose** [comment]
There was the same problem in data-cube-curation, which was fixed by enabling the `automaticSilentRenew`: https://github.com/zazuko/data-cube-curation/pull/302/files

**Comment by martinmaillard** [comment]
Crap, I was sure it was enabled by default, sorry. Thanks, I'll try
