### ISSUE TITLE
Adding New Elements to Existing Shared Dimensions

### ISSUE THREAD

**Issue by tboeni** [zazuko/cube-creator#1450]
While trying to add new elements to the [BAQUA - Monitoring Program](https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!baqua) SD, I encountered that when I am going for a new entry for example dimension/bgdi/inlandwaters/bathingwater/CH25037 as a new dynamic "hasPart" property for BAQUA_GE the entry does not get saved. Although pressing the "save term" button shows a success the SD does not remember the new term that was just added.

Also the suggested "linkable" terms are not searchable in the dropdown and do not show all the possible entries for the given SD but only the first few in alphabethical order.

**Affected functionalities**
* [ ] CSV Mapping
* [ ] Transformation
* [ ] Publishing
* [x] Other
 

**To Reproduce**
1. Go to '[BAQUA - Monitoring Program](https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!baqua/terms/dimension!!baqua!!ge/edit)' 
2. Edit any entry and go to dynamic properties
3. Add any functioning term and press "save term"

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [Edge]

**Comment by tpluscode** [comment]
Maybe the issue with adding is a red herring. The real problem appears to be the lacking search functionality. Without the chose value appearing in the dropdown, it cannot be properly selected.

I will momentarily provide a fix which bring back the searchability of the dropdown, which should resolve the problem.

**Comment by tboeni** [comment]
Thanks for your reply @tpluscode. 
What I recognized as well, if you put in a URI directly instead of searching the dropdown for the equivalent object it does not remember the value after saving the term also. 
Additionally, deleting a term does not work either. As I tried to delete unused terms in the Shared Dimension as a test

**Comment by tpluscode** [comment]
> What I recognized as well, if you put in a URI directly instead of searching the dropdown for the equivalent object it does not remember the value after saving the term also.

Yes, they must be selected from the options. Search coming very soon now

> Additionally, deleting a term does not work either. As I tried to delete unused terms in the Shared Dimension as a test

I assume you mean removing term values from a dynamic property? I checked, and found no issue there
