### ISSUE TITLE
Error: Unkown error in Cube Designer

### ISSUE THREAD

**Issue by CDiGallo** [zazuko/cube-creator#1455]
**Describe the bug**
instead of the table in cube designer I get Error: unkown error

**Affected functionalities** (all that apply)
* [x] Transformation
* [x] Other

**Relevant links**
the problem:
![image](https://github.com/zazuko/cube-creator/assets/86839683/ad6c2ba3-67fb-4354-b796-29197b08f193)

link to the cube in question:
**https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!zweitwohnungen-2bgplmmk2lr/csv-mapping**

from there you can access visualize.
the data: https://s.zazuko.com/2NbgaYo
it might have to soemthing with this:
![image](https://github.com/zazuko/cube-creator/assets/86839683/62c3cd8e-6741-4cfe-9be7-b7e3a5761490)

**To Reproduce**

**Expected behavior**
either a clear error message or a table

**Desktop (please complete the following information):**
 - OS: [e.g. w10]
 - Browser [e.g. edge]

**Comment by tpluscode** [comment]
Can you check again? The cube loads fine now. I think it must have fallen victim of Lindas issues at the time of reporting

**Comment by tpluscode** [comment]
Not reproducible anymore. Let me close now until it comes back
