### ISSUE TITLE
URL to open a specified cube in visualize no longer works from Cube-Creator or opendata.swiss

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#1456]
**Describe the bug**
From cube creator ([here](https://cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-amt-lanw3m5kxq/publication/jobs/cube-project!!staatsrechnungen-amt-lanw3m5kxq!!jobs!!f32OkUh9MmIVNxAaCtLtb)) this kind of URL no longer works (on any environment):  
[State account office](https://visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Office)  
Same behaviour from opendata.swiss [(here)](https://opendata.swiss/dataset/staatsrechnungen-amt):  
[Gehe zur Ressource](https://visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Office)

**Affected functionalities** (all that apply)
* [ x] Publishing

**Expected behavior**
Visualize must open with the given cube selected.
These URL works:  
[Base cube](https://visualize.admin.ch/en/browse?dataset=https://culture.ld.admin.ch/sfa/StateAccounts_Office/5&dataSource=Prod)  
[Without version number](https://visualize.admin.ch/en/browse?dataset=https://culture.ld.admin.ch/sfa/StateAccounts_Office&dataSource=Prod)  
  
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : tested on Edge and Firefox (opendata.swiss only)

**Comment by ortnever** [comment]
Merci @PDumasBAR .
Ici le lien vers l'issue pour interactive.
