### ISSUE TITLE
Shared dimension "Municipalities" missing in INT and empty in TEST

### ISSUE THREAD

**Issue by CDiGallo** [zazuko/cube-creator#1457]
Why is the shared dimension "municipalities" empty in TEST?

https://test.cube-creator.lindas.admin.ch/app/shared-dimensions/https:!!!!ld.admin.ch!!dimension!!municipality

on INT it does not exist anymore. That means, I created "Municipalities_for_are" which can be delted

**Comment by tpluscode** [comment]
I believe this has been resolved.
