### ISSUE TITLE
mixed node kind in cube data

### ISSUE THREAD

**Issue by giacomociti** [zazuko/cube-creator#1469]
**Describe the bug**

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [x] Publishing
* [ ] Other

**Relevant links**
 
[query](https://s.zazuko.com/3pGR6yA) returning an example of inconsistent data (a dimension with
constraint `sh:nodeKind sh:IRI` but having both IRI and literal values).

**To Reproduce**
1. Create a new cube from CSV
2. Apply transformation
3. Edit metadata linking to a shared dimension some values of a dimension (but not all of them) 
4. Publish

**Expected behavior**

The constraint for the dimension should have `sh:nodeKind sh:IRIOrLiteral` instead of `sh:IRI`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome

**Additional context**

There is a [proposal ](https://github.com/zazuko/cube-link/issues/109) of disallowing mixed node kinds. If applied, cube creator should prevent publishing invalid data.

**Comment by tpluscode** [comment]
I the correct node kind set when you transform again after editing the metadata?

**Comment by giacomociti** [comment]
by "editing the metadata" you mean for example linking every value to some shared dimension term? Because the node kind is set by the [pipeline ](https://github.com/zazuko/cube-creator/blob/4a9a139effed1304dfa0991ccd9b1cca77ae624f/cli/lib/toCubeShape/Dimension.js#L81)(<#toCubeShape>) based on the actual observations (and does not cover `sh:IRIOrLiteral` unlike the new implementation in [barnard59](https://github.com/zazuko/barnard59/blob/f1caca5ebbab83efc83d79860ac6ef68351fc788/packages/cube/lib/cube/buildCubeShape/constraintBuilder/NodeKindConstraintBuilder.js#L12)). So the only chance to avoid the issue is to ensure all the values for  a dimension have the same node kind (either IRI or Literal)
