### ISSUE TITLE
minInclusive/maxInclusive constraints on optional dimension

### ISSUE THREAD

**Issue by giacomociti** [zazuko/cube-creator#1470]
**Describe the bug**

 `sh:minInclusive` and  `sh:maxInclusive` constraints on a property with `cube:Undefined` values make it impossible to validate the data.

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [ ] Publishing
* [x] Other

**Relevant links**
 
[query](https://s.zazuko.com/yDZVWX) showing an example of dimension having both `cube:Undefined` values and `sh:minInclusive` constraint

**To Reproduce**
1. create a cube from CSV with some empty fields in a numeric column
2. Apply transformation
3. Edit metadata
4. Publish
**Expected behavior**

The  `sh:minInclusive` and  `sh:maxInclusive` constraints should be omitted because there are undefined values.
Alternatively, they can be nested with the data type:

```turtle
sh:or (
            [ sh:datatype xsd:decimal ; sh:minInclusive "1"^^xsd:decimal ; sh:maxInclusive "5"^^xsd:decimal ] 
            [ sh:datatype cube:Undefined ]
         ) ;

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome

**Additional context**

**Comment by tpluscode** [comment]
This will no longer apply once we switch to cube.link shapes, right?

**Comment by giacomociti** [comment]
yes

**Comment by AdMSilvan** [comment]
@rdataflow created a query to highlight this error in action https://s.zazuko.com/LrBtqX
