### ISSUE TITLE
More Helpful Error Explanations During CSV Upload

### ISSUE THREAD

**Issue by bequrios** [zazuko/cube-creator#1476]
**Is your feature request related to a problem? Please describe.**
If there is an error in uploading CSV files, there is only stated, that an error happened without further explanations, what this error could be.

**Describe the solution you'd like**
Better explanations of what went wrong, two encountered problems:

- CSV file name has an "Umlaut" like ä, ö, ü
- upload a new CSV file with a name of an already uploaded CSV file (missed the possibility to update an existing file)

**Comment by Rdataflow** [comment]
@bequrios See manual https://github.com/zazuko/cube-creator/wiki/CSV-Preparation#basic-requirements on basic requirements utf8 etc

@MartinaElsawy irc should be linked in cube creator...

**Comment by bequrios** [comment]
hm, ok this manual page states something about the content of the CSV files and the encoding but as far as I understand nothing about the problems mentioned in the issue.

**Comment by MartinaElsawy** [comment]
@bequrios thanks for all the iputs, the topic of CSV upload user experience (including error messages, manuals etc.) is already part of the UX activities and will be covered in the outcoming activities/improvements. I will close this issue with link to the bigger UX activities to avoid redundancies. -> https://gitlab.ldbar.ch/bafu/visualize/-/issues/574
Can you use the official and central board for BAFU project: https://gitlab.ldbar.ch/bafu/visualize/-/boards/7 for all new issues? Thanks so much
