### ISSUE TITLE
Cube Designer: when preparing a mapping to a shared dimension, the 'search' by string does nothing

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1481]
**Describe the bug**
When doing a mapping to a Shared Dimension, we can enter a few characters to find the specific dimension in the long list.
However, nothing happens, the list simply displays, and we have to look for the dimension.

See the printscreen

**Screenshots**
The list displays just after entering "IUCN":
![image](https://github.com/zazuko/cube-creator/assets/6167669/de8cad4c-897e-441e-b4e4-a389bf31d016)

But we can see that a dimension does correspond to "IUCN":
![image](https://github.com/zazuko/cube-creator/assets/6167669/17fe12f7-f446-45d4-bfba-bae15f18c37f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Fire Fox 121

Cube Creator: version 1.13.7 (c7bc76b)

**Comment by JurekMueller** [comment]
I want to add to this:
Additionally to the search here (when fixed), a search to filter for shared dimensions in the Shared Dimension view would be very helpful:

![grafik](https://github.com/zazuko/cube-creator/assets/29106093/ae01bfc0-e341-4bda-8f5d-63a4525797a0)

**Comment by tpluscode** [comment]
Hey @AdMSilvan, I realised I forgot to reply. I did improve that. It's been on TEST since

**Comment by AdMSilvan** [comment]
I tested it again after my comment and noticed it is working better now, thank you!
