### ISSUE TITLE
Shared Dimension tab no more works on INT

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1489]
It seems that displaying the Shared Dimension on INT is just "cycling" indefinitely
![image](https://github.com/zazuko/cube-creator/assets/6167669/d7210f15-f68d-4f11-bd3c-83f25d46ccbb)

**Comment by tpluscode** [comment]
We are working on it. Related: https://control.vshn.net/tickets/SBAR-1101

**Comment by tpluscode** [comment]
The cause was a new version of trifid running the lindas SPARQL endpoint. The problem has been resolved
