### ISSUE TITLE
SD Municipalities : 2391 Staatswald Galm ?

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1491]
I have a problem with the mapping with SD Municipalities. At the end of 2023 I did a mapping with SD Municipalities for my cube https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd006601-bodenbelastung-durch-schwermetalle-r5zqggxxgl9/metadata.
 
At that time I mapped the Galmwald location in my dataset to the 2391 Staatswald Galm municipality in the SD Municipalities. Today this municipality no longer seems to exist. Is it normal to have to make this change manually in my Cube?
The situation of the municipality "Staatswald Galm" seems very particular. Have a look at the "Geb. ohne Gem." tab in the following file: https://www.bfs.admin.ch/bfs/de/home/grundlagen/agvch.assetdetail.31265302.html

On map.geo.admin.ch the municipality Staatswald Galm 2391 is displayed : https://s.geo.admin.ch/nieuzdglv3y3

**Comment by tpluscode** [comment]
This is not strictly related to Cube Creator. I would not expect a municipality to disappear either. That is the reason we have https://version.link which should preserve municipalities which existed in the past.

It needs to be investigated when this municipality no longer appears. The responsible pipeline is in https://gitlab.ldbar.ch/pipelines/fso-ech_0071-ld/

**Comment by ortnever** [comment]
Hi @ktk : Do you know who is responsible for this pipeline? I cannot open the link https://gitlab.ldbar.ch/pipelines/fso-ech_0071-ld/. I do not have enough rights.

**Comment by ktk** [comment]
@ortnever I granted you read-access

**Comment by ortnever** [comment]
@ktk : Could you tell me who is responsible for this pipeline and who should solve the problem. Thank you.

**Comment by Rdataflow** [comment]
@ortnever I guess you can close this?

**Comment by ortnever** [comment]
@Thank you @Rdataflow  @ktk , @CDiGallo for solving the problem. I could publish the Soil Dataset with all the measurement sites. I close the issue.
