### ISSUE TITLE
Cube Creator PROD : Publish doesn't work

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#1493]
![image](https://github.com/zazuko/cube-creator/assets/79834090/2d93f173-109b-4ce7-b742-ef9c1f26e368)

**Comment by CDiGallo** [comment]
@tpluscode @MartinaElsawy 
I am pretty sure, the pipeline is not even started.
Can you have a look at it. Maybe VSHN should be involved, but I fear they would not know where to look.
Thank you

**Comment by tpluscode** [comment]
https://control.vshn.net/tickets/SUPPORT-8555

**Comment by tpluscode** [comment]
I raised it to major too

**Comment by ortnever** [comment]
Thank you @tpluscode. On April 15, we must publish the updated cubes of the greenhouse gas inventory. The problem must be solved before 15.04. It's really important.

**Comment by tpluscode** [comment]
A new publishing token has been set up. Please try now @ortnever

**Comment by ortnever** [comment]
I tested just now, on PROD :
![image](https://github.com/zazuko/cube-creator/assets/79834090/46f62958-5a74-418d-b514-45b496437e40)

**Comment by tpluscode** [comment]
Ok, let me follow up

**Comment by tpluscode** [comment]
The has been resolved on GitLab
