### ISSUE TITLE
Empty line at end of file causes CSV transformation error

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#1495]
**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [x] Transformation
* [ ] Publishing
* [ ] Other

**To Reproduce**
1. Create a project
2. Upload a CSV with an empty line
3. Create a mapping
4. Transform
5. Job will fail with a message saying that column count does not match

**Expected behavior**

Empty line should be ignored. We could also ignore all empty lines throughout the CSV.

**Comment by Rdataflow** [comment]
@tpluscode this looks like related ... or is this yet another issue? https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd000503-anteile-der-treibhausgasemissionen-aus-treibstoffen-im-sektor-verkehr-ae3aa1720r8/materialize/jobs/cube-project!!ubd000503-anteile-der-treibhausgasemissionen-aus-treibstoffen-im-sektor-verkehr-ae3aa1720r8!!jobs!!JMcpEx8n4wR67npMG8Tu-

cc @ortnever
