### ISSUE TITLE
Unit terawatt-hours per year (TWh/yr)

### ISSUE THREAD

**Issue by JurekMueller** [zazuko/cube-creator#1497]
I need the Unit terawatt-hours per year (TWh/yr) for a data cube.

I am uncertain if I request it here or suggest it directly at QUDT following these guidelines: https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines.

Thank you for your feedback.

**Comment by tpluscode** [comment]
Hello @JurekMueller. Yes, the preferred way is to add a unit directly to qudt. If that won't work, maybe we could add custom units to Lindas but I don't know if that's something we've done. So far all unit may be sourced solely from QUDT

**Comment by l00mi** [comment]
@tpluscode we have custom units in LINDAS to be able to advance on implementation of datasets. The can be found here https://gitlab.ldbar.ch/pipelines/lindas-metadata/-/blob/develop/units/custom_units.ttl and shall follow as close as possible the QUDT schema.

And yes I propose to request to be added to UpStream in QUDT at the same time.

**Comment by JurekMueller** [comment]
I added it to QUDT and it is part of the new release from the 25.04. but I still do not find it in the cube creator. What is the update cycle there?

**Comment by Rdataflow** [comment]
@JurekMueller IIRC it's harvested every Thurday before noon
