### ISSUE TITLE
Access denied on shared dimensions

### ISSUE THREAD

**Issue by JurekMueller** [zazuko/cube-creator#1498]
The link to the resource of an entry in a shared dimension seems to behave differently if it is read-only and if it is not.
![grafik](https://github.com/zazuko/cube-creator/assets/29106093/c6f0266d-e789-4d21-821b-631eab683f9d)

* read only: working link to resource 
Dimension: https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/https:!!!!politics.ld.admin.ch!!popular-vote!!types
Resource: https://politics.ld.admin.ch/vocabulary/popular-vote/type/3

* not read only: link to cube creator: access denied
Dimension: https://int.cube-creator.lindas.admin.ch/app/shared-dimensions/dimension!!forest-zone-01
Resource: https://int.cube-creator.lindas.admin.ch/dimension/forest-zone-01/gr05 (Access Denied)

**Comment by tpluscode** [comment]
Thank you for reporting.

Of course, that button should lead to LINDAS, as is the case of external (read-only) dimensions. In this case it should be 
https://ld.admin.ch/cube/dimension/forest-zone-01/gr05 and not a URL from Cube Creator

**Comment by giacomociti** [comment]
I'm troubleshooting this issue and, so far, I noticed only that the issue happens when [here](https://github.com/zazuko/cube-creator/blob/4a9a139effed1304dfa0991ccd9b1cca77ae624f/ui/src/components/ExternalTermLink.vue#L29) we lack the canonical value

**Comment by giacomociti** [comment]
commit https://github.com/zazuko/cube-creator/commit/3d8cbec66c98d3f46d3b0847949634ca94f3293c fixes the issue for terms already saved (coming from the API). When a new term is created, the wrong URI is still shown, so there's still something to fix

**Comment by tpluscode** [comment]
Right, when a term is created the `oa:canonical` was not present at all. Added that to the `POST` handler
