### ISSUE TITLE
Setup authentication between UI and API

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#15]
The authentication process is as follows:
1. The UI authenticates with the OIDC provider
2. The OIDC provider provides an authentication token to the UI
3. The UI sends this token with each request to the API
4. The API verifies the token with the OIDC provider

Steps 1, 2 and 4(?) are already working. This issue is about step 3.

We are going to use [Alcaeus](https://github.com/wikibus/Alcaeus) (Hydra client) as API client. An example of how to send the token with each API request is available on https://github.com/zazuko/data-cube-curation/blob/master/ui/src/api/index.ts#L50

**Comment by tpluscode** [comment]
About Alcaeus, note the difference in 1.0 branch. Nothing too big and type declarations should guide you while the updated docs are a WIP
