### ISSUE TITLE
Root dimensions when creating hierarchies not loading on TEST

### ISSUE THREAD

**Issue by AdMSilvan** [zazuko/cube-creator#1530]
When attempting to create a hierarchy on TEST, the drop down list for the root dimension only displays ten results, instead of all the shared dimensions available on TEST. The same drop down menu on int and prod functions as intended.
Could this possibly be caused by a LIMIT on the query which retrieves the shared dimensions? 

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [ ] Publishing
* [x] Other

**Comment by tpluscode** [comment]
Well of course, the limit was added but the dropdown should also be made searchable like in other places. Will fix this immediately
