### ISSUE TITLE
error on publish: publishedRevision - multiple terms found

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#1547]
**Describe the bug**
on publish I get the following error message
![Image](https://github.com/user-attachments/assets/397bfbe5-4e77-4fb0-8b36-59820ad374f1)

**Affected functionalities** (all that apply)
* [ ] CSV Mapping
* [ ] Transformation
* [x] Publishing
* [ ] Other

**Relevant links**
failing publication
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!holzfluss-in-der-schweiz-oenmp1m9bpr/publication

**To Reproduce**
1. Go to https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!holzfluss-in-der-schweiz-oenmp1m9bpr/publication
2. Click on publish
3. See error

**Expected behavior**
flawless publication

cc  @tpluscode

**Comment by Rdataflow** [comment]
same here https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!bodenbelastung-durch-schwermetalle-test-galm-9jpzqw0aaey/publication

**Comment by tpluscode** [comment]
The issue is that for an undetermined reason some projects now have multiple values for an internal `cc:latestPublishedRevision` property. Hence the error.

I updated the CC database so that each affected project has only one value which matches the actual latest version found in Lindas.

<details>

```sparql
PREFIX cc: <https://cube-creator.zazuko.com/vocab#>
PREFIX schema: <http://schema.org/>
PREFIX cube: <https://cube.link/>

delete {
    graph ?project {
        ?project cc:latestPublishedRevision ?r
    }
}
WHERE {
    graph ?project {
        ?project cc:latestPublishedRevision ?r ; cc:cubeGraph ?dataset
    }

    graph ?dataset {
        ?cube a cube:Cube
    }

    SERVICE <https://int.lindas.admin.ch/query> {
        SELECT ?cube (MAX(?v) as ?latestVersion) WHERE {
          ?cube schema:hasPart/schema:version ?v .
        }
        group by ?cube
    }

    FILTER(?r != ?latestVersion)
}

```

</details>

I triggered a publishing pipeline in one project and the issue did not come back.

**Comment by Rdataflow** [comment]
@tpluscode thanks for the fix in the DB 🎉
