### ISSUE TITLE
Store also User Name of the Cube Project Creator

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#158]
Additionally to the Userid (already added) add also the Username sourced by the Auth Flow to the Cube Project on creation.

Background: Potentially we will need to filter by Names in a later point of the project.

**Comment by l00mi** [comment]
Somewhere in Express.. there over the rainbow.

**Comment by l00mi** [comment]
adding creator.

**Comment by lucafurrer** [comment]
We already use `dcterms.creator` to store the user identifier (url). What is the good predicate to store the user name on the Project?

**Comment by tpluscode** [comment]
> user name on the Project?

On the user itself. `schema:name`?

**Comment by l00mi** [comment]
@lucafurrer, @tpluscode can we also show the name on the cube projects list?

**Comment by tpluscode** [comment]
Isn't that already happening?

**Comment by l00mi** [comment]
Sorry, it is. Did not see as it only does it with newly "touched" projects obviously.
