### ISSUE TITLE
Add API CORS headers in local dev environment

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#17]

**Comment by martinmaillard** [comment]
I'm trying to query the API from the UI using #9, but I'm still getting a CORS error in the browser. Do I have to configure anything?

**Comment by martinmaillard** [comment]
Interesting: I think I only have CORS issues when my request doesn't have a valid authorization token

**Comment by martinmaillard** [comment]
I'm not getting a response, because the browser is blocking it. The `Allow-...` headers are missing. But when I add the `Authorization: Bearer...` header it works.

<img width="1116" alt="Screenshot 2020-09-16 at 15 45 42" src="https://user-images.githubusercontent.com/1334124/93345992-c4fa9b00-f833-11ea-8afb-d4dd50d85945.png">
<img width="1115" alt="Screenshot 2020-09-16 at 15 45 55" src="https://user-images.githubusercontent.com/1334124/93346002-c75cf500-f833-11ea-831d-ea363bbfd742.png">

By the way, there is also an error in the API, which is probably not right:
<img width="1270" alt="Screenshot 2020-09-16 at 15 47 20" src="https://user-images.githubusercontent.com/1334124/93346169-f7a49380-f833-11ea-8e67-515ff6fae156.png">

**Comment by martinmaillard** [comment]
The `authentication` middleware happens before hydra-box, so it's not really a surprise that CORS are not applied to failed authentication requests. CORS should probably not be handled in `labyrinth`.

**Comment by tpluscode** [comment]
Does it help to only add `app.use(cors())`?

**Comment by martinmaillard** [comment]
I'm trying that right now ;)

**Comment by martinmaillard** [comment]
Indeed it solves the problem

**Comment by tpluscode** [comment]
This one's appears fixed as of #18
