### ISSUE TITLE
Dimension metadata resources

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#187]
Any dimension (column mapping) added to the observation table must have a metadata resource added to the dimension metadata graph (#185)

**DoD**

* [x] when a column mapping is created on **Observation Table**, create a [minimal metadata resource](https://github.com/zazuko/cube-creator/blob/f8cfa737c6cdc017a9591ec9ee5d05110b5ab5f9/fuseki/sample-ubd.trig#L61-L63)
   * the `schema:about` points to the dimension property, to be calculated from mapping' `cc:namespace`+`cc:targetProperty` or concrete URL is `cc:targetProperty` is a named node
   * attach to the `cc:DimensionsMetadata` resource
* [x] when a column mapping is removed, remove the metadata resource
* [x] when a column mapping's `cc:targetProperty` changes, the mapping resource has to be updated
   * `schema:about` point to correct URI
   * the `?dimension={dimension}` resources renamed
* [x] when the CsvMapping's `cc:namespace` changes all dimension mapping resources have to be updated

**Considerations**

The template `/dimensions-metadata?dimension={dimension}` does not necessarily have to be constructed from the full URI. In case of column mappings (in contrast to imported cube) the `cc:targetProperty` could be used alone. For example

```turtle
<project/mapping>
  cc:namespace <http://example.com/cube/> .

<project/table/observation>
  a cc:ColumnMapping ;
  cc:targetProperty "year" .

<project/dimension-metadata?dimension=year>
  schema:about <http://example.com/cube/year> .
```

**Comment by lucafurrer** [comment]
>the ?dimension={dimension} resources renamed
Is this still relevant with the non-query naming?

**Comment by tpluscode** [comment]
Technically not, but unless they are truly unique you would still have to rename using some naming scheme
