### ISSUE TITLE
FeatureRequest: Allow editing of existing column mappings

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#206]
- [x] UI should allow editing and removal of an existing mapping
- [x] Identifier template should be editable too
- ~~[ ] Data type and language attribute should be visible in list of mappings~~ this is part or #333 

BTW: Adding language attribute or a default value is broken, probably linked with #205

**Comment by lucafurrer** [comment]
Links to #118 #117

**Comment by lucafurrer** [comment]
Edit function added with PR #223

**Comment by danielmittag** [comment]
All fixed or part of #333
