### ISSUE TITLE
Can't create new project on Firefox 68.5 

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#243]
- Véro can't create a new project with FFox 68.5
- Error is while initializing form (see screenshot)
- Edge and FFox 83.0 are OK

![ErrorNewProject_Vero](https://user-images.githubusercontent.com/17119538/100338811-5f681f00-2fd9-11eb-843b-1fa58aaa331a.jpg)

**Comment by tpluscode** [comment]
Any errors in the console?

**Comment by martinmaillard** [comment]
I have some errors in Sentry.

Firefox 68 was released in 2018. Do we need to support it? Is there no way to upgrade?

**Comment by martinmaillard** [comment]
@danielmittag Is there a list of browsers we need to support?
