### ISSUE TITLE
Conventions for cube design

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#246]
There are a number of conventions that sooner or later should be enforced by the application, in the meantime we need to define these and enter correct data manually (if possible).

- **Dataset Identifier**
  - In opendata.swiss the identifier for the udb28-Dataset is `UBD0028@bundesamt-fur-umwelt-bafu`
  - I suppose only "UBD0028" should be entered by the users, the rest must com from an internal organisation list
- **Identifier template**
  - Do we need a fully qualified URI, just an ID, some sort of path?
  - Is there a difference between dimension tables and observation tables?

**Comment by l00mi** [comment]
solved with https://github.com/zazuko/cube-creator/pull/379
