### ISSUE TITLE
Scale of measure: Comprehensive documentation needed

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#247]
- The dropdown for "Scale of measure" lacks description.
- The final implementation of these possibility depends a lot of wha IXT allow to display
- imo base classes shouldn't be available

Here's the actual hierarchy according to https://github.com/zazuko/rdf-cube-schema-viz/blob/master/vocab/scaleOfMeasure.ttl along with a couple of remarks

- `rdf:Class`
  - `<ScaleOfMeasure>`
    - `<Numerical>` should it really be available in the dropdown when its subclasses are?
      - `<Continuous>`
      - `<Discrete>` do we need to add information about step size (in case it's not 1)
      - `<Temporal>` Is that enough info? 
    - `<Categorical>` should it really be available in the dropdown when its subclasses are?
      - `<Ordinal>` will the pipeleine automatically create a value list in the shacl? Where is the order taken from?
      - `<Nominal>` will the pipeleine automatically create a value list in the shacl? 
      - `<Spatial>` Is that enough info? 

It also seems to me that there is no link from column datat type to dimension scaleOfMeasure, i.e. mapping a string to any `<Numerical>`  is possible

**Comment by l00mi** [comment]
inspiration: https://statistics.gov.scot/help/data_cubes

**Comment by l00mi** [comment]
https://github.com/zazuko/cube-creator/wiki/3.-Cube-Designer#scale-of-measure
