### ISSUE TITLE
Deleting the observation table should delete related dimensions

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#257]

**Comment by tpluscode** [comment]
Similar also applies to changing an observation table to an ordinary table and was part of #239.

But

Given multiple observation tables, any dimension could appear on more than one of them. I would expect them to not be removed.

**Comment by lucafurrer** [comment]
@tpluscode After my understanding, it is currently not possible to have two observation tables that point on the same dimension metadata (same targetproperty)

```typescript
    addDimensionMetadata(params: CreateColumnMetadata): DimensionMetadata.DimensionMetadata {
      const identifier = params.csvMapping.createIdentifier(params.columnMapping.targetProperty)

      if (this.hasPart.some((dimMeta) => dimMeta.about === identifier)) {
        throw new Error(`Dimension Metadata with identifier ${identifier.value} already exists`)
      }
```

**Comment by tpluscode** [comment]
Aha, I suppose this is code too strict then.

This can happen if you create a second observation table and use same target property. In such case the two tables should share the dimension metadata

Not to mention that there is a bug in that code 🤣 

Should be:

```diff
-      if (this.hasPart.some((dimMeta) => dimMeta.about === identifier)) {
+      if (this.hasPart.some((dimMeta) => dimMeta.about.equals(identifier))) {
```

**Comment by lucafurrer** [comment]
Ok, I think I know what to do

**Comment by lucafurrer** [comment]
Is this sufficient to check something like this to check that no other columnMapping uses the same dimension
```turtle
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cc: <https://cube-creator.zazuko.com/vocab#>

ASK
WHERE {
  GRAPH ?mapping {
  ?mapping rdf:type cc:ColumnMapping ;
           cc:targetProperty 'targetPropertyOfCurrent'
    
  }
  filter ( ?mapping = <currentMapping> )
}
```
