### ISSUE TITLE
Bug: Mapping broken after renaming Target Property

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#261]
Steps to reproduce:
- New Project
- Upload UDB0037 .csv ([UBD0037.zip](https://github.com/zazuko/cube-creator/files/5621822/UBD0037.zip))
- Run Pipeline (now cube preview is OK besides not mapping the 1st column, which is a known issue)
- In CSV Mapping, I enamed Target property "larmbelastete-einheit" to "Laembelastete-Einheit"
  - --> No more preview data for Laembelastete-Einheit 
- Re-run pipeline
  - --> Cube Designer UI gets stuck
- Example is here: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!demo-udb0037-20201201-emyq6o6xn8l/metadata

```
index.mjs:104 Uncaught (in promise) Error: observations: Multiple terms found where 0..1 was expected
    at a.get (index.mjs:104)
    at Object.get (proxy.mjs:28)
    at s.<anonymous> (CubePreview.vue:138)
    at d (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at i (asyncToGenerator.js:3)
    at a (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
```

**Comment by danielmittag** [comment]
Could be missing cleanup of target graph before publication

**Comment by martinmaillard** [comment]
`cube.observations` has multiple values. cc @tpluscode

**Comment by tpluscode** [comment]
@danielmittag Please try again with latest version. I followed the steps and did not reproduce

**Comment by tpluscode** [comment]
Checked again, works well. Please reopen if necessary
