### ISSUE TITLE
Feature Request: Overwriting the CSV data should be possible

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#275]
... if (and that will have to be checked) the data is compatible with the current mapping.

Currently the entire mapping must be remade if new data arrives or some updates have been made on the data.

**Comment by danielmittag** [comment]
There are the following possibilities on compatibility check:
- Minimal: Any CSV is accepted and the end user is responsible for not breaking the mapping
- Maximal: CSV header must be identical
- Smart (my recommendation): The new CSV must contain all columns that have been mapped in an output table

Additional Questions: 
- Is this case sensitive?
- As far as I know there are no other constraints than the existence of the column name (f. ex. there are no checks on data type and data integrity) - is this correct?

**Comment by l00mi** [comment]
A first minimal Implementation is prioritised.

* A CSV can be substituted if and only if the exact same structure is available, including the same header names.
* If no complications come up, a CSV which does add a new Column can be also implemented.

Out of Scope for now:
* Anything involving the missing of a before specified column.

**Comment by lucafurrer** [comment]
Must the existing CSV-file on S3 be kept or can it be deleted?

**Comment by l00mi** [comment]
If it is accepted (in regards of structure) the old file can be deleted.
