### ISSUE TITLE
CSV Mapping: Still can't create same Target Property with different languages on non-observation table

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#283]
```
Bad Request

Target property already mapped from column undefined 
```
- Steps to reproduce:
  - Load CSV (f.ex. [CH_yearly_air_immission_unit_id.zip](https://github.com/zazuko/cube-creator/files/5650900/CH_yearly_air_immission_unit_id.zip) )
  - map unit_name_de to Target Property = "name", Language = "de" --> OK
  - map unit_name_fr to Target Property = "name", Language = "fr" --> Error
- Test Project: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!zmoke-test-issue-283-p9k3kqnvkex/csv-mapping

BTW: Where is it stated the different languages must not occur on the observations table. I've heard that from Thomas but it wasn't confirmed by others.

**Comment by martinmaillard** [comment]
I can't reproduce this. Is it still the case?

**Comment by danielmittag** [comment]
True, can't reproduce either, works as expected.
