### ISSUE TITLE
CSV Mapping: UI doesn't update after "Update Column Mapping" (refresh needed)

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#284]
- Steps to reproduce
  - Create table from CSV
  - Update Column Mapping
    - After saving updated mapping the UI still displays the old name
    - Reloading the project os switching tabs fixes the problem
- Tested in FFox 83.0 and Edge Chromium

**Comment by martinmaillard** [comment]
I cannot reproduce this

**Comment by l00mi** [comment]
@danielmittag can you please check again and close if resolved?

**Comment by l00mi** [comment]
Okay i close for now. Please re-open if needed.
