### ISSUE TITLE
Linked dimensions are not deleted when deleting Table

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#288]
Steps to reproduce:
- Map any table (f.ex. [UBD0037.csv](https://github.com/zazuko/cube-creator/files/5652831/UBD0037.zip))
- Create Table with all columns
- Run transformation
- Remove Table
  - No more table in "Output tables" of "CSV Mapping"
  - Table still present in "Cube Designer"

**Comment by martinmaillard** [comment]
It does seem to be a bug. I'll reword the issue because the "Table" concept doesn't exist in "Cube Designer".

**Comment by martinmaillard** [comment]
Actually it's a duplicate of #257
