### ISSUE TITLE
CSV Mapping: Linking to table itself shouldn't be allowed

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#310]
Steps to reproduce:

- Create a new project
- add a CSV
- Create a table "Tabelle1"
- Try "Link to another table"
  - --> The "Link to table"-Dropdown will only contain "Tabelle1". This would be a recursion and I don't think this should be allowed

**Comment by martinmaillard** [comment]
Why not? It's not useful for the observation table, but I can see uses cases for other tables
