### ISSUE TITLE
Meaning and Behaviour of Dataset date and time Definition [WIP]

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#321]
We have multiple date(-times) added to each Dataset. I like to clarify the meaning and behaviour here.

Based on https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/wikis/Dataset-Metadata

*dct:issued* and *schema:dateCreated* (creation of the dataset)
* A value to be defined through the user. (Potentially propose the current date in the user interface if empty.)

*schema:datePublished*
* A value automatically added to the dataset first time a publishing is done, with the current date. (stays from then on for all versions the same)
* Can be changed by user if needed.

*dct:modified* and *schema:dateModified*
* A value automatically added on every publishing process. Not visible in the UI.
* Can not be changed by the user.

**Comment by tpluscode** [comment]
> (creation of the dataset)

maybe that should be the time when project is created in the app?

**Comment by l00mi** [comment]
> > (creation of the dataset)
> 
> maybe that should be the time when project is created in the app?

Ideally its the date when the input CSV was created (the actual time when the dataset was created, not the transformation). But I think often the user will use just the date when the project is created. That is why I see the best option to let the user choose the date, but already pre populate it with the date when the project is created.
