### ISSUE TITLE
"Value does not have shape Blank node b18056_b11" when saving Project Settings

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#329]
Steps to reproduce (INTEG, Edge)
- New Project (Publish Graph: "http://test")
- Go to `Project Settings`, save

```
The request payload does not conform to the SHACL description of this endpoint.

csvMapping
Value does not have shape Blank node b18236_b11
```

**Comment by martinmaillard** [comment]
This horrible error message happens when the `namespace` doesn't have a correct format (e.g. missing trailing "/"). I'll see what I can do to improve that.
