### ISSUE TITLE
Management of "Publish Graph" Setting by Application

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#331]
- Currently the `Publish Graph` is set in a text box that allows any URI. 
- By definition all BAFU cubes must have the graph uri `https://lindas.admin.ch/foen/cube` 

I therefore suggest replacing the text box by 
- A dropdown that contains all organisations involved in this project (BAFU, BAR, BFS?, ...?)
- A global configuration that defines `Publish Graph` (as well as other technically required properties) for all organisations

**Comment by martinmaillard** [comment]
We already have #317 and the related PR #325 for this. The decision was to just hide this field for now, but in the future it would be nice to have a dropdown.

**Comment by l00mi** [comment]
Solved by https://github.com/zazuko/cube-creator/pull/379
