### ISSUE TITLE
Management of Identifier Template by Application

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#332]
Currently the tool uses all columns of a CSV to construct the identifier template. In the real world this is almost always wrong:

- In a dimension table there is usually exactly one "key" or "code" column that is also used for references. Only this one will be used for the identifier template, and no labels
- In a observation table we'd expect all dimensions in the identifier template, but no measures and no attributes (terms according to https://www.w3.org/TR/vocab-data-cube/#cubes-model)

I suggest that the current text box might remain for special cases but that the choice and order of the columns used for the identidfier template should be managed by the apllication.

**Comment by danielmittag** [comment]
Original message by fabian

![GitHubIssue_332a](https://user-images.githubusercontent.com/17119538/101915972-9c7e0500-3bc6-11eb-91c7-804c260d3b5a.png)
![GitHubIssue_332b](https://user-images.githubusercontent.com/17119538/101915974-9d169b80-3bc6-11eb-834a-5606b192e89b.png)
![GitHubIssue_332c](https://user-images.githubusercontent.com/17119538/101915975-9daf3200-3bc6-11eb-8163-8850e7510205.png)

**Comment by danielmittag** [comment]
UI Proposition: The users will simply check which columns are used for the identifier, then the tool creates the identifier template

<img src="https://user-images.githubusercontent.com/17119538/102625829-55ec5580-4146-11eb-84fb-0e566d4fe8fa.png" width="50%" height="50%">

- The screen above would then create an identifier in the form of `{station_id}/{year}`
- Like this there is no more the risk of typos
- Problems
  - at least when we have a linked dimension (like "stations") we typically don't use the key ("station_id") anymore. The tool must then be smart enough to get it right
  - sort order of columns must be editable too

**Comment by l00mi** [comment]
closed in favor of https://github.com/zazuko/cube-creator/issues/619
