### ISSUE TITLE
CSV Mapping: Lack of visible Info for Output Tables

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#333]
Besides the target property there should at least be info on **language attribute** and **data type**. The best would be to display everything (also default value if there is one)

**Comment by danielmittag** [comment]
Original Input from Fabian

![GitHubIssue_333](https://user-images.githubusercontent.com/17119538/102055247-d7f91900-3dea-11eb-8d8b-14488e8c25ab.png)

**Comment by martinmaillard** [comment]
This is something we need to think about.

I'm not sure it's useful to show all the options of a column mapping directly in the table. There is potentially a lot more options that we could add in the future, and it doesn't really make sense to show them all.
