### ISSUE TITLE
Usability Improvements Cube Designer

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#342]
Fabian suggests the following improvments

- Button "Edit Metadata" should have a matching label
- Dimensions should be initialized with the target property name (at least in english)
  - alternatively the target property could be displayed if no name was defined - this would then apply to the columns **and** the "Edit Dimension Metadata" editor overlay

**Comment by danielmittag** [comment]
Original Report by Fabian

![GitHubIssue_342](https://user-images.githubusercontent.com/17119538/102083617-240c8380-3e14-11eb-97a3-f9af817d25da.png)

**Comment by l00mi** [comment]
Implemented.
