### ISSUE TITLE
Handling of blanks / usage of Default Value

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#345]
It started with the following Question by Fabian:

*Edit column mapping: What is the use/consequence of "default value", does it make it possible to generate valid cubes when some column values are missing for some observations ?*

According to Tom:
- missing values are allowed
-  the pipeline should fill in the blanks so that the cube has "NULL" values for dimensions where necessary

Remarks Daniel:
- To Fabian: The default value will replace blanks but the pipeline should be able to handle blanks / null values even without a default value. 
-  To Tom: As far as I remember every observation in a cube must have a position in all dimensions. So missing values on a dimension would need to be linked with a dummy/blank record on that dimension. Is that correct and if so:
   - Does the pipeline create a dummy entry when creating a dimension?
   - How is this handled if the dimension is only an attribute of the observsation table?

**Comment by tpluscode** [comment]
I think you're confusing some terms. An observation basically a key-value collection of dimensions. If any dimension lacks a value, a placeholder value is substituted with `NaN"^^xsd:double`. This is technical solution to ensure performant queries.

It is irrelevant if a dimension is a literal value or an IRI

**Comment by tpluscode** [comment]
See [here](https://github.com/zazuko/rdf-cube-schema/blob/master/best-practice.md#nullempty-values)

It is not that much different. In fact it is quite the same. While a cube observation must have all dimensions, actual data may not conform. Hence the pipeline plugs those holes with `NaN`

**Comment by danielmittag** [comment]
Attention: According to https://github.com/zazuko/rdf-cube-schema/blob/master/best-practice.md#nullempty-values NaN is only a valid substitute for measures of type `float `and `double`. So this is not a strategy to cope with blanks on dimension level or other data types.

**Comment by danielmittag** [comment]
Let's make an example to see things more clearly: We use UDB28 that contains all the complexity imo (BTW this pipeline actually stops at line 6 where value_remark is blank):

```
"station_id","pollutant_id","aggregation_id","limitvalue","year","value","unit_id","value_remark"
"blBAS","so2","annualmean",30,1984,31.9,"µg/m3","incomplete series"
"blBAS","so2","annualmean",30,1985,40.2,"µg/m3","incomplete series"
"blBAS","so2","annualmean",30,1986,33.6,"µg/m3","incomplete series"
"blBAS","so2","annualmean",30,1987,33,"µg/m3","incomplete series"
"blBAS","so2","annualmean",30,1988,17.4,"µg/m3",
"blBAS","so2","annualmean",30,1989,18.5,"µg/m3",

```

- According to the W3C wording we would state that
  - `station_id`, `pollutant_id`, `aggregation_id `and `year` are classic **dimensions** (and the building blocks of the identifier template in cube creator `{station_id}/{pollutant_id}/{aggregation_id}/{year}`)
  - `value` is the **measure**
  - `value_remark` is only an **attribute** but not a dimension
  - (`limitvalue` could be measure or attribute, `unit_id` dimension or attribute imo but that's another discussion)
- As far as I know W3C requires **(a)** an observation to have a value for every dimension, but not that **(b)** an observation must exist for every "cell" in the cube
- in https://github.com/zazuko/rdf-cube-schema/blob/master/best-practice.md#nullempty-values this is not entirely clear to me
  -  _In RDF Cube Schema, all dimensions are mandatory for a cube_ would be the same as **(a)** in W3C
  - _if a value could not be measured, it should be expressed as such_ could mean that **(b)** is mandatory too (but then it should be stated very clearly)
- These statements (if I got things right) lead to the following questions
  - **(a)**: According to https://github.com/zazuko/rdf-cube-schema#dimensions all columns are considered dimensions, so blanks are basically forbidden everywhere
    - Does the pipeline have a way to deal with blanks? And if so
      - Are blanks automatically replaced by `NaN` for `float` and `double`?
      - What are the rules and the behavior for other primitive types (`string`, `int`, `decimal`, `date` and `datetime`)
      - What are the rules and the behavior for linked dimensions (IRIs). (In classic data warehousing every dimension table has a dummy record to manage this case - is that an option?)
    - Having an observation `{station_id}/{pollutant_id}/{aggregation_id}/{year}` without a measure `value` would seem elegant to me but I can't tell the impact on querying and id still doesn't solve the "missing dimension" problem.
  - **(b)** imo it is close to impossible to check this prerequisite during import. What happens if the CSV isn't a perfect Cartesian product? Does the pipeline fill the gaps?

**Comment by tpluscode** [comment]
> Does the pipeline fill the gaps?

It is up to us. It is only really important that the published cube is "complete" according to spec. While in Cube Creator I would consider it a work in progress.

I would propose to split this problem in two (or three) stages

1. Import CSV, create mapping, run transformation
2. The resulting cube has gaps => inform the user via the UI
3. Make it possible to fill in missing values as the user sees fit for a current cube
   - this may mean inserting zeros, empty string, or other "default value" where missing for example

While the last step could technically be part of the pipeline, it would make unnecessarily complicated given the streaming nature. I'd rather the "post-transformation cleanup" step was a separate feature (itself possibly implemented as a pipeline though)

**Comment by l00mi** [comment]
@tpluscode what is the current behaviour here?

**Comment by danielmittag** [comment]
> 
> 
> @tpluscode what is the current behaviour here?

I did a retest today on INTE (2021-02-08) - no changes have been observed

**Comment by martinmaillard** [comment]
It turns out that the "default value" was completely ignored. It should work now (on test).

I'm pretty sure that the following sentence doesn't reflect reality though:
> If any dimension lacks a value, a placeholder value is substituted with NaN"^^xsd:double.

From what I could see, if a cell is empty and no default value is provided, the observation doesn't appear in the cube at all, which tells me that it probably doesn't fill the empty spot with `"NaN"^^xsd:double`.

**Comment by danielmittag** [comment]
In my example here: https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!case-study-blanks-oaz4ad2xwzy/metadata preview doesn't show the 3rd line. In the transformed cube the line is present nevertheless but without observation for the blank cell - see also #481 where I added all the details

Anyway I really don't think the blank should be replaced by NaN at all - this would be a very bad thing imho.

**Comment by l00mi** [comment]
Closing in favor of https://github.com/zazuko/cube-creator/issues/481
