### ISSUE TITLE
IRI of Dimensions wrong (?)

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#346]
- In my  UDB0028 case study https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!case-study-udb0028-6ymlzngqkar/metadata I have a dimension table named **pollutants**. 
- On my observation table I link to this table on the property **pollutant**.
- In Cube Designer Preview I get the following IRI for my linked pollutant "so2" `https://pipelines-integ.lindas.admin.ch/cube/case-study-udb0028-6ymlzngqkarso2`
- In the "old" tool the dimension table has the Identifier Template "pollutants/{pollutant_id}" ("pollutants" is the name of the output table), which seems fair
- As far as I can tell, the following points look wrong:
  - The project name shouldn't be part of the IRI (though probably it's just the `Cube namespace` which is by default the same as the project name, in this case that's OK)
  - the dimension name is missing
  - there must be a slash before the identifier

**Comment by tpluscode** [comment]
> The project name shouldn't be part of the IRI (though probably it's just the Cube namespace which is by default the same as the project name, in this case that's OK)

Correct

> the dimension name is missing

Missing where?

> there must be a slash before the identifier

Is this still the case? Should have been fixed so that the default namespace gets a slash. And it is also enforced when updating project

**Comment by l00mi** [comment]
resolved with new iri mgmt.
