### ISSUE TITLE
Documentation of built-in namespaces for Target Property (and their usage)

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#349]
The editor for Target Property suggests properties for same default namespaces like schema, skos, ... . 

![GitHubIssue_349](https://user-images.githubusercontent.com/17119538/102238473-18918900-3ef6-11eb-9f05-041b7b1d60d4.png)

This feature is currently undocumented and one that will add a lot of business value **if it's used (correcly) by the users**. We should create a comprehensive documentation about how and why to use it - for example in the [manual](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/wikis/Cube-Creator-Manual)

**Comment by danielmittag** [comment]
Additional Question: The UI allows selecting lots of predefined properties but there doesn't seem to be a link to datatype. I actually guess that some of these options cannot be represented by literals at all. Do we have an idea how to cope with these restrictions?

**Comment by l00mi** [comment]
Documented at https://github.com/zazuko/cube-creator/wiki/Technical-Addendum#preloaded-ontologies
