### ISSUE TITLE
Failed Transformation Agroscope_BIL_P_Duengung+Bilanz

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#351]
Transformation fails with error in the logs

- https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!agroscopebilpduengungbilanz-46r3bvlkvlw/pipeline
- https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/6015

Please analyze error cause

**Comment by tpluscode** [comment]
This should be obsolete now. It was reported literally 1 day before we merge #353 which drastically changed how we download csvs. Please check
