### ISSUE TITLE
Extract organisation settings

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#359]
We have been discussing ways to make it simpler for users to set up a project.

Currently we appear to have two setting which are per-organisation (BAR, BAFU), both of which are currently defined on every project:

1. Cube namespace
2. Publish graph

## Cube namespace

The cube namespace is a base URI for all cube identifiers (observations, dimension predicates). While a part of the namespace would remain project-specific, we would like to move the `http//` portion to a shared location for all projects within an organisation.

## Publish graph

This one is simpler, and could only be moved from the project to the organization.

## Before and after (proposal)

**Before**

```turtle
<project> a cc:CubeProject ;
  cc:publishGraph  <https://lindas.admin.ch/foen/cube> ;
  cc:csvMapping <project/csv-mapping> ;
.

<project/csv-mapping>
  a cc:CsvMapping ;
  cc:namespace <https://environment.ld.admin.ch/foen/ubd/28/> 
.
```

**After**

```diff
<project> a cc:CubeProject ;
- cc:publishGraph  <https://lindas.admin.ch/foen/cube> ;
  cc:csvMapping <project/csv-mapping> ;
+ schema:maintainer <organization/bafu> ;
+ cc:cubeIdentitifer "ubd/28/" ;
.

<project/csv-mapping>
  a cc:CsvMapping ;
- cc:namespace <https://environment.ld.admin.ch/foen/ubd/28/> ;
.

+<organization/bafu>
+ a schema:Organization ;
+ cc:publishGraph  <https://lindas.admin.ch/foen/cube> ;
+ cc:namespace <https://environment.ld.admin.ch/foen/> .
```

## Impact

Currently the `cc:namespace` is derived from the project URI (also created semi-randomly to ensure uniqueness). I think this does not really make sense and that that value should only ever be provided by the user.

Thus, for any given project, transformation would be impossible until the users set it through the UI. This will prevent "surprise cubes" with strange URIs.

---

The project creation/update form would change: namespace and publish graph (hidden field) would be replaced by an element (dropdown) to select an organisation from among the instances of `schema:Organization`

## Open questions

1. Would we allow any arbitrary URI as the cube identifier or should they always be rooted in the `cc:namespace`?

**Comment by tpluscode** [comment]
Upon further discussion here are the necessary steps to complete this issue:

* Structure
  * [ ] create a collection resource for organizations
  * [ ] move `cc:namespace` and `cc:publishGraph` to organization
  * [ ] introduce `cc:cubeIdentifier`
* Shapes
  * [ ] require `schema:maintainer` and `cc:cubeIdentifier` when creating project
* Mapping/transformation  
  * [ ] The base cube URI must be a concatenation of parent Org's `cc:namespace` and `cc:cubeIdentifier`
* Other
  * [ ] prepare migration SPARQL Update scripts

**Comment by lucafurrer** [comment]
Question: should there be any synchronization between `cc:cubeIdentifier` and `dcterms:identifier` in the Cube meta data. Same question arises to the meta data connected to the organisation and less to the cube itself.

**Comment by tpluscode** [comment]
Proposed update query

1. Assigns all existing projects to the BAFU organization
2. Renames all cubes as `BAFU namespace` + `md5(current cube URI)`
3. Rebases all those cube-derived identifiers for dimensions

```sparql
base <https://pipelines-test.lindas.admin.ch/>

prefix cc: <https://cube-creator.zazuko.com/vocab#>
prefix schema: <http://schema.org/>
prefix dct: <http://purl.org/dc/terms/>
prefix cube: <http://ns.bergnet.org/cube/>

DELETE {
    graph ?project {
        ?project cc:publishGraph ?pg .
    }

    graph ?csvMapping {
        ?csvMapping cc:namespace ?ns .
    }

    graph ?dataset {
        ?dataset schema:hasPart ?oldCube .
        ?oldCube ?cubeP ?cubeO .
    }

    graph ?metadata {
        ?property schema:about ?oldDimension .
    }
}
insert {
    GRAPH ?metadata {
        ?property schema:about ?newDimension.
    }

    graph ?dataset {
        ?dataset schema:hasPart ?newCube .
        ?newCube ?cubeP ?cubeO .
    }

    graph ?project {
        ?project schema:maintainer <organization/bafu> ;
                 dct:identifier ?cubeId ;
    }
}
where {

    graph ?project {
        ?project a cc:CubeProject ;
                 cc:publishGraph ?pg ;
                 cc:csvMapping ?csvMapping ;
                 cc:dataset ?dataset .
    }

    GRAPH ?csvMapping {
        ?csvMapping cc:namespace ?ns ;
    }

    graph ?dataset {
        ?dataset a schema:Dataset ;
                 schema:hasPart ?oldCube ;
                 cc:dimensionMetadata ?metadata .
        
        ?oldCube a cube:Cube ;
                ?cubeP ?cubeO .
    
        BIND ( md5(str(?oldCube)) as ?cubeId )
        BIND ( IRI(CONCAT('https://environment.ld.admin.ch/foen/', ?cubeId)) as ?newCube )
    }

    GRAPH ?metadata {
        ?metadata a cc:DimensionMetadataCollection ;
                  schema:hasPart ?property .
        
        ?property schema:about ?oldDimension .
    }

    BIND (IRI(replace(str(?oldDimension), str(?oldCube), str(?newCube)) )as ?newDimension)
}
```
