### ISSUE TITLE
Cube Metadata: Datepicker picks wrong date on 1st try + US-Format

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#369]
I actoually couldn't reproduce this one but got feedback from two sides:

Pierre: _La première fois qu’on saisit une date dans le sélecteur de date, elle est décalé d’un jour. La 2ème fois ça marche._
Jeremy: _Der Date-Picker wählt immer den vorherigen Tag aus – wahrscheinlich ein Zeitzonen-Issue (und ist generell mühsam zu verwenden ;))._

Besides that the picker should display swiss date format DD.MM.YYYY imo.

**Comment by martinmaillard** [comment]
This was already fixed this morning (#365)

The format is based on your browser's locale

**Comment by martinmaillard** [comment]
The bug is fixed. Please create another issue if using the browser locale's format is not acceptable.
