### ISSUE TITLE
Make it possible to add Links to the sh:description to point to external help.

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#387]
To provide in context information to the end-user on UX elements we should be able to provide medium sized texts, potentially with minimal Typography (Lists, Emphasises).

**Comment by martinmaillard** [comment]
We already have that on form fields: add a `sh:description` in the shape.

For buttons I used tooltips until now. But I'll think about other solutions if you give me examples where you would want to add more context.

**Comment by l00mi** [comment]
Specifically I think that the field "ScaleOfMeasures" might need an explanation what each entry does stand for. So I expect about 2 sentences per entry. It might be doable with sh:description already?

See also: https://github.com/zazuko/cube-creator/issues/247

**Comment by martinmaillard** [comment]
For the scale of measures I would add:

- A sh:description on the field itself to explain what the scale of measure is used for
- A link to some documentation
- Maybe a rdfs:comment on each scale of measure option and I'll check if I need to change something in the UI for it to appear. But I really think the first step should be to have documentation somewhere. It's not a simple subject that can be sumarized in one sentence.

**Comment by tpluscode** [comment]
Are `rdfs:description` displayed under a dropdown like in this case of project form?

![app cube-creator lndo site_cube-projects_cube-project!!ubd_metadata](https://user-images.githubusercontent.com/588128/104187745-89a25e80-5418-11eb-9ac7-ebb4c0a70a44.png)

**Comment by l00mi** [comment]
Can we have links in this descriptions? That would be pretty flexible?

**Comment by martinmaillard** [comment]
I can make it so that we can have links ;)

**Comment by tpluscode** [comment]
[zero-md](https://zerodevx.github.io/zero-md/) works great for displaying markdown

**Comment by l00mi** [comment]
@martinmaillard how can this be used finally?

**Comment by martinmaillard** [comment]
You can include markdown in any of the shapes' `sh:description` and it will be rendered in the UI.

e.g. `sh:description "This is [a link](http://example.org)"` or `sh:description "This **is bold** and *italic*"`

**Comment by l00mi** [comment]
@martinmaillard
The links are not opened in a new window/tab (missing target="_blank"). It seems the vue-markdown can be configured for that: https://github.com/miaolz123/vue-markdown/blob/master/example/webpack-simple/src/App.vue#L5.

Please add.
