### ISSUE TITLE
ScaleOfMeasures: Minimize choice from user.

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#388]
@herrstucki lets discuss the mentioned topic here.

Currently we allow the full spectrum defined here https://github.com/zazuko/rdf-cube-schema-viz/blob/master/vocab/scaleOfMeasure.ttl. And I like to keep this open from the pure ontology point of view.

But for the end-user of the cube-creator we should minimize the choice to currently used scales in visualize.admin.ch.

We have the following, indentation shows sub-classing:
* ${scale.Numerical}
   * ${scale.Continuous}
   * ${scale.Discrete}
   * ${scale.Temporal} 
* ${scale.Categorical}
   * ${scale.Nominal}
   * ${scale.Ordinal}
   * ${scale.Spatial}

In general I tend to remove Numerical, Categorical and only keep the more specific ones.

The following two questions:

* Is there a use to know if a numerical value is discrete or continuous? E.g Price vs. count of Sheep.
* Do you interpret somehow ordered categorical values? (E.g. "low", "medium", "high"?) Do you plan to?

**Comment by l00mi** [comment]
Compare also too the more global https://github.com/zazuko/cube-creator/issues/247

**Comment by martinmaillard** [comment]
For the scale of measures I would add:
- A `sh:description` on the field itself to explain what the scale of measure is used for
- A link to some documentation
- Maybe a `rdfs:comment` on each scale of measure option and I'll check if I need to change something in the UI for it to appear. But I really think the first step should be to have documentation somewhere. It's not a simple subject that can be sumarized in one sentence.

**Comment by herrstucki** [comment]
Thanks @l00mi!

I agree, there's no need to ever choose numerical/categorical when there's more specific types.

1. At the moment we don't differentiate continuous and discrete values … so the distinction is not very relevant (in practice, I don't remember that this ever had a significant impact on choosing a visualization type). If it's semantically relevant from the data owner/provider perspective, feel free to keep it.
2. Ordinal values are definitely important and we very much plan to use them.

P.S. A typo or intentional: shouldn't it be [«Scale of Measure**ment**»](https://en.wikipedia.org/wiki/Level_of_measurement)?

**Comment by l00mi** [comment]
> P.S. A typo or intentional: shouldn't it be «Scale of Measurement»?

@ktk I think it is a Noun here and Measurement [makes more sense](https://english.stackexchange.com/questions/56387/measure-vs-measurement#:~:text=In%20normal%20usage%2C%20%22measure%22,or%20the%20result%20of%20measuring.)... 

Any reason to not change it right now? Else I will make a PR to change it here https://github.com/zazuko/rdf-cube-schema-viz/blob/master/vocab/scaleOfMeasure.ttl

**Comment by ktk** [comment]
No idea, that's beyond my English language paygrade. I took it from Wikipedia: https://en.wikipedia.org/wiki/Level_of_measurement

**Comment by l00mi** [comment]
Option 1: Keep what is needed for VIZ
Numerical, Temporal, Nominal, Ordinal, Spatial

Option 2: Keep what allows to describe all cases Semantically correct.
Temporal, Discrete, Continuous, Nominal, Ordinal, Spatial

Let's shortly discuss with the customer tomorrow.

**Comment by l00mi** [comment]
> No idea, that's beyond my English language paygrade. I took it from Wikipedia: https://en.wikipedia.org/wiki/Level_of_measurement
> 
> > Level of measurement or scale of measure is a classification that describes the nature of information within the values assigned to variables.

Hm.. the Google Hits test is close. 

Scale of Measure -> 1’180’000’000
Scale of Measurement -> 1’870’000’000

**Comment by l00mi** [comment]
Option 2 nach Meeting BAFU
