### ISSUE TITLE
Make an override for TEST env to write published cubes to https://lindas.admin.ch/foen/cube-test

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#395]

**Comment by l00mi** [comment]
The new graph is available `https://lindas.admin.ch/foen/cube-test`, but currently TEST still deploys on the `https://lindas.admin.ch/foen/cube` on 
* https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!tomasz-4-no06ykxe4qp/edit

**Comment by tpluscode** [comment]
Oh, got it. The variable was not being forwarded to the pipeline container: https://gitlab.ldbar.ch/pipelines/cube-creator/-/commit/3c17c04af4b713026f5b79902825d89571d71416

Will be fixed now
