### ISSUE TITLE
In some cases, the /dataset endpoint crashes the container

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#402]
I don't know what causes that, but sometimes the API container crashes when visiting the Cube Designer page. The `/dataset` endpoint seems to be responsible.

Example https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!case-study-udb0028-rabmzrajjla/metadata

**Comment by l00mi** [comment]
I can confirm this behaviour.

**Comment by martinmaillard** [comment]
Reopening because I saw this happen again (although less frequently)

**Comment by tpluscode** [comment]
ugh. got a specific example?

**Comment by danielmittag** [comment]
On Test Environment it's https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!cube-creator-issues-402-mrvzkm9rbgl/ 

Steps to reproduce:
- Upload [UBD0066_Bodenbelastung.csv](https://github.com/zazuko/cube-creator/files/5836260/UBD0066_Bodenbelastung.zip)
- Map all columns to observation table (leave everything at default)
- transform
- switch to Cube Designer tab
  - UI freezes, new browser window will display **503 Service Temporarily Unavailable** nginx/1.17.10 for a while
