### ISSUE TITLE
Create sample managed dimension shape

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#419]
So that we can work on #417

**Comment by l00mi** [comment]
See https://github.com/zazuko/cube-creator/issues/376

**Comment by l00mi** [comment]
The plan is to create two manged dimensions for cantons and municipalities by extending by using https://github.com/zazuko/elcom-strompreis/blob/master/sparql/

**Comment by l00mi** [comment]
First Managed Dimension "Cantons" added to TEST env:

```
#CREATE a DefinedTermSet for Cantons

PREFIX  schema: <http://schema.org/>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>

INSERT { 
    GRAPH <https://lindas.admin.ch/cube/dimension> {        
    <https://ld.admin.ch/dimension/canton> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:DefinedTermSet .
    <https://ld.admin.ch/dimension/canton> schema:validFrom "2021-01-20T23:59:59Z"^^xsd:dateTime .
    <https://ld.admin.ch/dimension/canton> schema:name "Cantons"@en .
    <https://ld.admin.ch/dimension/canton> schema:name "Kantone"@de .
    <https://ld.admin.ch/dimension/canton> schema:name "Cantons"@fr .
    <https://ld.admin.ch/dimension/canton> schema:name "Cantoni"@it .
    ?canton <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> schema:DefinedTerm .
    ?canton schema:inDefinedTermSet <https://ld.admin.ch/dimension/canton> .
    ?canton schema:validFrom "2021-01-20T23:59:59Z"^^xsd:dateTime .
    ?canton schema:identifier ?alternateName .
    ?canton schema:identifier ?alternateNameLCASE .
  }}
WHERE
  { SERVICE <https://test.lindas.admin.ch/query>
      { ?canton  a                     <https://schema.ld.admin.ch/Canton> ;
                 schema:alternateName  ?alternateName
        BIND(lcase(?alternateName) AS ?alternateNameLCASE)
      }
  }
```

**Comment by l00mi** [comment]
To query:

```
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?value schema:inDefinedTermSet <https://ld.admin.ch/dimension/canton> .
    ?value ?pvalue ?ovalue .
}
WHERE {
    	?value schema:inDefinedTermSet <https://ld.admin.ch/dimension/canton> .
    	?value ?pvalue ?ovalue .
}
```

**Comment by tpluscode** [comment]
@l00mi please remind/answer

*storage*

All dimension will be in the same graph in Lindas?

*schema:validFrom*

Does this mean that we will want to keep multiple generations of the same managed dimension? Will there also be a `schema:validThrough` as with cubes?

*updates*

Related, will a similar query eventually be used to fetch an updated term set from the source?

*?alternateNameLCASE`

Why no `skos:prefLabel` + `skos:altLabel`? I actually find it weird that both labels use the same predicate. I think this is going to be awkward to use without the ability to tell them apart.

**Comment by l00mi** [comment]
**storage**: yes in https://lindas.admin.ch/cube/dimension

**schema:validFrom**: No I don't think that there will be multiple versions. It is more to be able to deprecate a managed dimension that it is not anymore available in the interface to choose from. The same is true for the DefinedTerms itself. Once a DefinedTerm has a valid:through it should not be available to choose in the interface. (For now I suggest to keep the mapping if it was selected in the past.)

**updates**: I am not sure if I understand the question. But a once mapped URI can stay until manually changed by the user.

**?alternateNameLCASE**: This is open for discussion, but also not a priority right now. Potentially one dimension might have x amount of identifier lists. So as long they are not overlapping its okay. And like this we only have to check for one predicate.

In the case of overlapping identifiers (e.g. ZIP Code and Statistics Office Number) we potentially would need to choose manually which to apply anyway, and here I would propose to use even more specific predicates like http://schema.org/postalCode ..

**Comment by tpluscode** [comment]
**update**
I meant if there would at some point be a feature to "recreate" a managed dimension from the original source.

**?alternateNameLCASE**
I think this one is quite important and I'm already confused. You use it like labels (original + lower case) but used the `schema:identifier`. I think this tries to achieve too much.

We do need a display label, which you SPARQL actually does not insert. 

What is the case for actual identifiers? Just meta? Search?

**Comment by l00mi** [comment]
**update**
The externaly created managed dimensions might be udpated, but for the manually created in the cube-creator there is no such feature planned.

**?alternateNameLCASE**
The schema:identifer shall only be a potential hint for the mapping to preselect the correct values. (If the data uses the same identiefers.
The SPARQL only does add this values to already existing triples in the store. Please run the second query.

**Comment by l00mi** [comment]
As discussed with @bergos we also want to be able to add a `cube:observationConstraint` to the `schema:DefinedTermSet which will be copied as template for the cube project own dimension description. (To allow to provide information units and scaleOfmeasure and potentially also hierarchical relations between dimensions.)

**Comment by l00mi** [comment]
```
<https://ld.admin.ch/dimension/canton> <http://www.w3.org/ns/shacl#property> [
    schema:name "Kanton"@de;
    schema:name "Canton"@fr;
    qudt:scaleType qudt:Nominal.
]
```

**Comment by l00mi** [comment]
@tpluscode i did update the current example online adding the "shape" with the queries here:
https://github.com/zazuko/cube-creator/issues/419#issuecomment-763889073

**Comment by tpluscode** [comment]
@l00mi let's update the sample above as we discussed. I propose as follows:

1. Add type `https://cube-creator.zazuko.com/managed-dimensions/vocab#ManagedDimension` in addition to `schema:DefinedTermSet`
2. I'd still remove the `LCASE` identifier and assume we do case-insensitive search for mapped keys?

**Comment by l00mi** [comment]
* remove the LCASE
* added the "https://cube-creator.zazuko.com/managed-dimensions/vocab#ManagedDimension" for now until settled on the final name

**Comment by l00mi** [comment]
change to correct meta namespace

**Comment by l00mi** [comment]
FYI  @tpluscode 
Adapted to last changes: https://s.zazuko.com/2gk4f6
