### ISSUE TITLE
Unauthorized redirect from the root

### ISSUE THREAD

**Issue by vhf** [zazuko/cube-creator#42]
When signed in, https://pipelines-test.lindas.admin.ch/ redirects to https://pipelines-test.lindas.admin.ch/app . When not, we get 

```
{"type":"about:blank","title":"Unauthorized","detail":"No authorization token was found","status":401}
```
 with no redirection or visible way of signing in.

**Comment by martinmaillard** [comment]
I noticed this as well. This is a priority for this sprint. Is anyone taking care of it already?
