### ISSUE TITLE
Deleting table linked by another table should delete the link

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#425]
When deleting a table that is linked by another table, the column-mapping that links to the deleted table should probably also be deleted.

**Comment by l00mi** [comment]
@lucafurrer this is solved, correct?

**Comment by lucafurrer** [comment]
Not sure, I have not done anything in this regard. I'll check

**Comment by l00mi** [comment]
Ah sorry, I might confuse it with https://github.com/zazuko/cube-creator/issues/438

**Comment by lucafurrer** [comment]
It is not exactly the same thing. But I can do it, however it is in progress, so I guess somebody already started it
