### ISSUE TITLE
Pipeline UDB0037: Only one row is imported

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#429]
- Test Data: [UBD0037.zip](https://github.com/zazuko/cube-creator/files/5835892/UBD0037.zip)
- Test Project: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!daniel-test-udb37-1ewokoy6bp

Result:
- Only the 1st row is displayed in Cube Designer

**Comment by tpluscode** [comment]
This has been fixed by #440. Please reopen if necessary

In projects where this happens it will be necessary to run the transformation
