### ISSUE TITLE
Deleting a property has no effect ...

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#438]
... if the target property is used twice in the mapping

Steps to reproduce
- Upload [AllDataTypes.csv](https://github.com/zazuko/cube-creator/files/5848223/AllDataTypes.zip) (or whatever you like)
- Map all columns to observation table
- Create a dimension table with the column "Date" (BTW: the default identifier template "Date/{Replace}" is blocking mapping)
- (you might set the dimension names in Cube Designer now in order to see the bug more easily)
- Map *also* the dimension date with the Date property
- Remove the "original" date-Property in CSV Mapper
  - in Cube Designer it's still there (although it isn't transformed)

Testproject: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!cube-creator-issues-438-75d1ykoggmb/

![GitHubIssue_438a](https://user-images.githubusercontent.com/17119538/105332375-d9c9af80-5bd4-11eb-8a23-cca33231360a.png)

![GitHubIssue_438b](https://user-images.githubusercontent.com/17119538/105332391-dcc4a000-5bd4-11eb-9447-9aeebca6cd18.png)

**Comment by l00mi** [comment]
That needs to be discussed. I like to argue that is "by design". Because it is not allowed to delete a dimension, at least once the cube was published.

Potentially we should make it clear in the UI that this dimension needs to be added again.
