### ISSUE TITLE
Add opendata.swiss Organizations to the Cube Metadata

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#448]
(Similar too the Opendata.swiss Themes), add the Organizations (e.g. https://register.ld.admin.ch/opendataswiss/org/bundesamt-fur-umwelt-bafu) as a field to the Cube Metadata.

The Field `dcterms:publisher` shall be used for this.

**Comment by lucafurrer** [comment]
@l00mi Should all orgs in (https://register.ld.admin.ch/opendataswiss/org/) be available

**Comment by l00mi** [comment]
yes
