### ISSUE TITLE
API endpoints to apply dimension mappings

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#457]
Part of #376

Add endpoint to fetch and save mappings for a given observation dimension.

**Requirements**

* [x] The mappings resource (`prov:Dictionary`) must be initialised when a dimension is set to `qudt:scaleType qudt:NominalScale` or `qudt:scaleType qudt:OrdinalScale`.
* [x] Each dimension has its own mappings, even if they map same managed dimension
* [x] Remove all mappings when selected managed dimension changes
* [ ] When a mapping pair is set, the original string values must be replaced in observations and `cube:ObservationConstraint` shape
   - when existing mapping is changed it would be necessary to rerun the transformation. might add a project `schema:Warning`

**Questions**

1. Remove mappings resource when `scale:scaleOfMeasure` is changed to anything else than `scale:Nominal`?

**Comment by martinmaillard** [comment]
@tpluscode Is this done?

**Comment by tpluscode** [comment]
Yes, not the "warning" but we don't do those right now so 🤷‍♂️
