### ISSUE TITLE
Trigger the cube preview refresh after a transform job changes to state "success".

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#478]
If the cube preview panel is active. Trigger a refresh once the transform job is done.

**Comment by martinmaillard** [comment]
One potentially stupid question: what if you want to compare the data before/after the transformation? If we do an auto-refresh, it won't be possible to have 2 tabs open, one with the old data, one with the new data.

**Comment by l00mi** [comment]
Good point, and minor importance.
