### ISSUE TITLE
"User is not defined" when creating a project

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#480]
I got this Error Message this morning when trying to creat a new project

![GitHubIssue_480](https://user-images.githubusercontent.com/17119538/106425989-14e5a180-6465-11eb-85ca-a6f31c5c6a8c.png)

- Happened after 1st logon to Cube Creator (INTE)
- Gets fixed by logging off and on again
- Had the same issue already last week but wasn't sure if that was just random

**Comment by danielmittag** [comment]
I got this Error Message this morning when trying to creat a new project

![GitHubIssue_480](https://user-images.githubusercontent.com/17119538/106425989-14e5a180-6465-11eb-85ca-a6f31c5c6a8c.png)

- Happened after 1st logon to Cube Creator (INTE)
- Gets fixed by logging off and on again

**Comment by l00mi** [comment]
Only if the session is valid, but no name is shown on top right corner.

**Comment by l00mi** [comment]
Its a BUG!

**Comment by danielmittag** [comment]
Observed this behavior again this morning:
- New browser / 1st cube creator session after reboot
- Log in to eIAM Abnahme: Name shows up in the top right corner
- Refresh browser window (F5) --> Name has disappeared
- Log off and on again, Name is stable from now on.

**Comment by l00mi** [comment]
@sandhose please ping me, we need to check this together.
