### ISSUE TITLE
Transformation operation performance (new VM configuration)

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#486]
Fabian:
> Now that VSHN enhanced the VM state, the transformation that was taking 3-4 minutes is now done in around 1 minute. I see this from my " Fabian Red List Test 1" project, which is a very small dataset.
But with my new test project " Fabian_Jahrbuch Wald & Holz 2020_Test 2", the transformation time is now 5-6 minutes. It is a 15MB csv (Originally a 70MB csv that I had to cut down to 15 MB because of upload limitation) – but I am sure that your tool can transform big datasets in seconds – as TARQL does.
It seems that the transformation process has 2 "phases",  a first phase and then the icon starts blinking in blue. This “blinking in blue” phase seems quite long.

**Comment by tpluscode** [comment]
Can Fabian provide a link to an example job? We can see what takes most time in Sentry.

I looked at a random job yesterday and a sizeable portion of the time it took was actually `PUT/POST` requests to Stardog Graph Store

**Comment by FabianCretton** [comment]
@tpluscode  Here is a log: https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/7412

**Comment by tpluscode** [comment]
Here's the [Sentry log](https://sentry.zazuko.com/organizations/zazuko/performance/cube-creator-cli:107215395fa74f468c0a2355ad036f84/?end=2021-02-02T23%3A59%3A59&environment=int&project=7&query=&showTransactions=recent&start=2021-02-02T00%3A00%3A00&transaction=Transform&unselectedSeries=p100%28%29&utc=true) of this execution.

Out of the overall time the process took, **235 seconds** were spent uploading to Stardog. While, the actual mapping would have been mostly been done in parallel, it only contributed a little to the total time.

**Comment by l00mi** [comment]
@FabianCretton can you check again if this still is a problem?
