### ISSUE TITLE
Decide on and add Licence

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#491]
The Visualize Project uses a BSD 3-Clause "New" or "Revised" License https://github.com/visualize-admin/visualization-tool/blob/main/LICENSE

@ktk do you have any input on this?

**Comment by ktk** [comment]
We had the standard license in https://github.com/zazuko/data-cube-curation/blob/master/LICENSE and I don't see why this would not be enough for our case. I understand the license for the viz tool but I don't see why this would matter for us.

**Comment by l00mi** [comment]
@RetoStoll so we have the two choices.. MIT or  BSD 3-Clause "New" or "Revised" License. Your choice? Any further questions.

**Comment by l00mi** [comment]
@RetoStoll if you have strong opinion we propose to go with the MIT licence?

**Comment by RetoStoll** [comment]
Das Visualisierungs-Tool ist wie folgt Lizenziert (analog geoadmin):

visualize-admin/visualization-tool is licensed under the
**BSD 3-Clause "New" or "Revised" License**
A permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the project or its contributors to promote derived products without written consent.

https://github.com/visualize-admin/visualization-tool/blob/main/LICENSE
https://github.com/visualize-admin/visualization-tool/blob/main/LICENSES.txt

Wenn möglich den cube-creator unter derselben Lizenz veröffentlichen

**Comment by ktk** [comment]
@RetoStoll beim Visualisierungs-Tool sehe ich den Sinn von anderem Namen, da es sehr stark auf den Bund bezogen ist aber viel generischer als "Cube-Creator" geht doch kaum nicht, ist da der Name wirklich ein Problem?
