### ISSUE TITLE
BNode clashes through Stardog

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#494]
We have BNode clashes on e.g. the shacl:properties of versioned cubes.

See on TEST.
```
PREFIX schema: <http://schema.org/>
PREFIX cube: <http://ns.bergnet.org/cube/>
select DISTINCT ?cube ?y WHERE {
    graph <https://lindas.admin.ch/foen/cube> {

        ?creativeWork schema:hasPart ?cube.
        ?cube a <http://ns.bergnet.org/cube/Cube>.
        ?cube schema:name ?cubeName.
        ?cube cube:observationConstraint ?const.
        ?const ?x ?y.
        ?y ?z ?t.

    }
}
```

**Comment by danielmittag** [comment]
On INTE in my latest cube in 

`DESCRIBE <https://environment.ld.admin.ch/foen/case-study-scale-of-measure/1/shape/>`

I get f. ex. _:b1_b113 which belongs to a very different mapping.

Is that the same issue?

**Comment by l00mi** [comment]
Absolutely.

**Comment by tpluscode** [comment]
Do we still want this plugged on our end nonetheless? (#501)

**Comment by l00mi** [comment]
yes please.
