### ISSUE TITLE
Document release process in README

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#500]
I forgot to mention that in the PR. But it would be nice to have a short explanation of how to create a new release.

**Comment by tpluscode** [comment]
Isn't #447 about that already? :)

**Comment by martinmaillard** [comment]
There are 2 sides to this:
1. Ops side: how is the app deployed (not related to this repo, but related to the specific BAFU project)
2. Developer side: how do I create a new release (directly related to this repo and to the PR you merged today)

This issue was about 2. But if you prefer to track it in the other issue that's fine.

**Comment by martinmaillard** [comment]
But I think I was again confused by the fact that your PR was merged into another branch than master. Nevermind ;)
