### ISSUE TITLE
Switch to cube.link namespace

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#510]
The Cube Ontology: https://github.com/zazuko/rdf-cube-schema changed the namespace.

Change the namespace in the necessary places:

- [x] Pipelines
- [x] GUI
- [x] API
- [x] `rdf-cube-view` library
- [x] Migrate data

**Comment by tpluscode** [comment]
Are we also changing the `http://ns.bergnet.org/cube-view/` NS? @bergos

**Comment by bergos** [comment]
Yes becomes [`https://cube.link/view/`](https://github.com/zazuko/rdf-cube-view-query/blob/master/lib/namespaces.js#L8)

**Comment by tpluscode** [comment]
To update database

```sparql
delete { 
    graph ?g {
      ?s ?p ?o
    }
}
insert {
    graph ?g {
      ?s ?newP ?o
    }
}
where {
    GRAPH ?g {
        ?s ?p ?o .
        
        # filter ( ?p = <http://ns.bergnet.org/cube/scale/scaleOfMeasure> )
        filter ( regex(str(?p), '^http://ns.bergnet.org/cube/') )

        BIND ( iri(REPLACE(str(?p), '^http://ns.bergnet.org/cube/', 'https://cube.view/' )) as ?newP)

    }
}
```

**Comment by bergos** [comment]
@tpluscode you also need to update the object to cover `rdf:type` for `Cube`, `ObservationSet`, `Observation`.

**Comment by tpluscode** [comment]
@bergos ah, you mean the SPARQL, right?

**Comment by tpluscode** [comment]
Done and deployed
