### ISSUE TITLE
Minor Problems in default query on https://test.lindas.admin.ch/sparql/#

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#522]
The URL https://s.zazuko.com/VbvXQ (the latest bookmark I have) opens the https://test.lindas.admin.ch/sparql/# GUI with the following Query:

```
SELECT ?cube ?title ?x ?y WHERE {
  graph <https://lindas.admin.ch/foen/cube> {
    ?cube a <http://ns.bergnet.org/cube/Cube>.
    OPTIONAL {
    ?cube <http://purl.org/dc/terms/title> ?title.
    }
  }
}
```

This query has 2 problems:
-  `?x` and `?y` are obsolete
- For example cube https://environment.ld.admin.ch/foen/bil-p-01/2/ shows up 4 times because the title is present in 4 languages

This is very cosmetic for sure but maybe also easy to fix for someone who knows SPARQL

**Comment by l00mi** [comment]
Solved by adding a link to publication screen automatically creating the query.
