### ISSUE TITLE
No preview data on INTEG

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#523]
I can't see any preview data on INTEG, neither old data nor after running transformation.
Output cubes are OK then again.

- Seems to apply to all projects
- Example https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!case-study-scale-of-measure-5ge3md717na/metadata

**Comment by martinmaillard** [comment]
I think it was fixed by #524. But it seems like all projects require re-running the transformation once before they can show observations. Is that correct @tpluscode?

**Comment by danielmittag** [comment]
re-running the transformation fixed preview in all my projects, thx!

**Comment by tpluscode** [comment]
Would be two unrelated matters. #524 was a problem but most projects would need to re-transform to update cubes to the new namespace
