### ISSUE TITLE
Cube Preview crashes container in int

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#526]
It seems that the Cube Preview page (not sure which API request yet) sometimes crashes the container again.

In the following project, try going through a few pages of the cube data and it should crash:
https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fabianjahrbuch-wald-holz-2020test-2-xm3v67vbpkp/metadata

**Comment by tpluscode** [comment]
Previously it was memory issues but I doubt that the `/observations` endpoint would do that. The cube query takes its time but the results are effectively limited

The `/dataset` on the other hand is more likely culprit. For this cube the Shape is some 6k triples. If they were to leak somewhere then maybe. 

Unless we have a leak somewhere else and this is just a red herring. The easiest way to tip the app off balance...

**Comment by martinmaillard** [comment]
This may be a duplicate of #488

**Comment by l00mi** [comment]
https://gitlab.ldbar.ch/vshn/gitops-prod/-/merge_requests/251

**Comment by l00mi** [comment]
Seems to be resolved with memory bumping.
