### ISSUE TITLE
Technical Problems with agroscope-bil-p-01 (not steadily reproducable)

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#532]
During our tests Pierre reported the following behavior on Feb-15 17:00

- Preview works for Page 1
- Preview displays "Unknown Error" on Page 2
- UI is blocked after some other manipulations

I was able to reproduce the same problems on Feb-16, 09:00. 
- However, while retesting the dataset I then could page through all 1184 records without getting an error and I haven't had an issue since then.
- Remark: The UI has a flashing blue transformation icon indicating that the job from 2/15/2021, 4:49:10 PM isn't finished yet, but the job log displays success

[Original E-Mail (pdf)](https://github.com/zazuko/cube-creator/files/5987280/GitHubIssue_532.pdf)

**Comment by martinmaillard** [comment]
Probably related to https://github.com/zazuko/cube-creator/issues/526

**Comment by l00mi** [comment]
Should be resolved, please reopen if still an issue.
