### ISSUE TITLE
Cube Designer: Pager active even if there is no next page

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#533]
I have this set with 6 records ( https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!case-study-all-data-types-dani-2021-01-27-ql5rovewox3/metadata ) and in preview the button for `Next page` is active nevertheless

![GitHubIssue_533a](https://user-images.githubusercontent.com/17119538/108045542-e01c4180-7043-11eb-8532-206bf12ccd84.png)

![GitHubIssue_533b](https://user-images.githubusercontent.com/17119538/108045559-e3afc880-7043-11eb-9c81-d69f108c5b22.png)

**Comment by martinmaillard** [comment]
Because I currently have no way to know how many records total we have ;)

**Comment by tpluscode** [comment]
Would depend on https://github.com/zazuko/rdf-cube-view-query/issues/20
