### ISSUE TITLE
eIAM auth doesn't work with some smartcards

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#56]
eIAM authentication via CH-Login works, but in some configurations it doesn't work with smartcards. It seems like the browser used affects this issue (e.g. MS Edge).

Epic: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/188

**Comment by martinmaillard** [comment]
This should be fixed now, right @sandhose ?

**Comment by danielmittag** [comment]
Never had complaints lately, issue closed
