### ISSUE TITLE
Cube "transformation" sometimes hang-up/never finishes

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#563]
(I told this to Martin a while ago, I do not know if an issue is needed for this or if it was already created)

It often happens that a transformation never finishes.
It happened again this morning 2021.03.03
See my project "Fabian_Jahrbuch Wald & Holz 2020_Test 2", open the history of transformation: a few transformations still have a blinking blue icon.

**Comment by tpluscode** [comment]
I check the mentioned log and apparently the stream ends abruptly and the job was never updated as "failed" although there was an actual error logged.

**Comment by FabianCretton** [comment]
Any update about this ?
I still have an issue transforming "Fabian_Jahrbuch Wald & Holz 2020_Test 2"
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/8797

You can see in the transform "history" that every day that I tried the transformation, the first transformed failed (and never ends in the GUI), the second succeeds
