### ISSUE TITLE
Cube published, but not found on SPARQL end-point

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#565]
I did publish the cube "Fabian_Jahrbuch Wald & Holz 2020_Test 2", the operation seems successful: green icon, no error in the logs.

However I can not find the cube on the end-point:
https://test.lindas.admin.ch/sparql/#
with end-point: "https://test.lindas.admin.ch/query"

My query that might be wrong or need adaptation (is the graph still correct): 
SELECT * WHERE {
  graph <https://lindas.admin.ch/foen/cube> {
    ?cube a <http://ns.bergnet.org/cube/Cube>.
    OPTIONAL {
    ?cube <http://purl.org/dc/terms/title> ?title.
      FILTER(lang(?title) = "en")
    }
 }
}

I would expect to find a cube with the URL:
https://environment.ld.admin.ch/foen/fab_tst_2
"fab_tst_2" being the cube identifier

**Comment by tpluscode** [comment]
Indeed, the publishing appears to work just fine :)

1. The published graph would be found in INT endpoint (https://int.lindas.admin.ch/sparql/)
2. The cube namespace changed to the final URL. The cube class is now `https://cube.link/Cube`

**Comment by FabianCretton** [comment]
Thank you for your reply.

A little remark: it seems that the title of the https://int.lindas.admin.ch/sparql/# html page is "test.lindas..." (what I see on my browser tab title)
