### ISSUE TITLE
Transformation operation fails - Forestry test with a 242 MB file

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#586]
I did prepare a new project "[Fab test Forestry - 242 MB](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-forestry-3xrvo6r60jo)".

The upload of the 242 MB .csv file worked fine.

The transformation failed, the icon turned red, and the log is here: https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/8419

I do not know what happened and why the transformation failed. 
To be noted: I was not on that "tab" when that operation failed (about 15 minutes after launching the transformation), was there any explicit error message at some ?

Two questions here:
- Is it normal that the transformation failed (problem with the .csv, or did I for instance use wrong types for the mapping, etc.) or is that a bug ?
- How can I know the reason of the failure, was there a popup message that I missed ? If so, how to display a more persistent message for long operations

**Comment by martinmaillard** [comment]
The logs mention an authorization issue when downloading the CSV. My guess is that the previous steps of the pipeline took so long that the token expired. Is this possible @tpluscode @sandhose ?

I also noticed that the job seems to download the same CSV file several times, once for every table. Is this still the case @tpluscode ?

**Comment by tpluscode** [comment]
Yes, the download link has an expiration so it is possible

Yes, the csv is downloaded separately for every output table

**Comment by sandhose** [comment]
Download link generation is done here: https://github.com/zazuko/cube-creator/blob/25f00fea07bb17a44d2d209da28c41896126884f/apis/core/lib/storage/s3.ts#L44-L49

This method accepts a `Expires` parameter, which is set to 900 (5min) by default: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

A "quick and dirty" fix would be to up that limit a bit

**Comment by tpluscode** [comment]
Other alternatives:

- download files to disk instead of going to s3 every time (low-to-medium effort)
- parallelise the output tables so that each input is concurrently transformed (medium-to-high effort)

**Comment by l00mi** [comment]
@tpluscode can you please just change the timeout to 30min for a test. If this does remedy this problem partially, we will close this ticket for #663.

@FabianCretton please test once @tpluscode has merged.

@rflowdata follow here.

**Comment by tpluscode** [comment]
We have since changed the pipeline so that every table gets a fresh download link. This should overcome the timeout problem

@FabianCretton could you try uploading that csv again? We might look into why that ran into problems while we're at it

**Comment by Rdataflow** [comment]
* [x] @tpluscode well done! transformation passes now successfully without hitting any timeout. token is renewed after 1800s. [job log](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/12497) 
* [ ] @l00mi cube-creator app fails in [step 2](https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!ch-bafu-wald-faostat-prod-test002-xxqnddvzz4b/metadata) with 'GET https://pipelines-test.lindas.admin.ch/cube-project/ch-bafu-wald-faostat-prod-test002-xxqnddvzz4b/dataset 504 (Gateway Time-out)' after 3min. seems there is some query ongoing serverside. how can we get this fixed?

**Comment by l00mi** [comment]
@Rdataflow as I promised you, its not a simple fix. So can we agree we look into it with properly redoing the whole thing with the "Big File" feature?

**Comment by tpluscode** [comment]
I have optimised the query which took so long in the `GET /dataset` request. The screen now loads successfully although loading the actual observation data also takes a bit long. We will look into that separately, as it uses an external library to navigate the cube
