### ISSUE TITLE
Replace CSV file - strange behavior

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#587]
I already had [this existing project](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-forestry-6gwyn7oe2zw/csv-mapping) with a small csv file.

I wanted to replace it with the real file of 242 MB.

During the "replace CSV file" operation, I got this error:
![image](https://user-images.githubusercontent.com/6167669/110601600-692b2200-8185-11eb-861b-9954a51e7e09.png)
![image](https://user-images.githubusercontent.com/6167669/110601883-b0b1ae00-8185-11eb-8fc0-aaad0f3184bb.png)

Then I did move to another project.
A while later, I opened up this project again, and now I see (what can still be seen currently):
![image](https://user-images.githubusercontent.com/6167669/110602033-db9c0200-8185-11eb-9f31-eb4354673e49.png)
So actually, it seems that the "replace" operation finally worked, or partially worked.
But why this error during the file replace, and why this error now ?
To be noted that the 242 MB file is the same file that I did upload without problem but for which the transformation failed as reported in this other issue: https://github.com/zazuko/cube-creator/issues/586

**Comment by martinmaillard** [comment]
Probably not relevant anymore since we changed the upload method
