### ISSUE TITLE
CSV Mapping - Map new column - Formular title

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#593]
First remark: I guess we will have a few request about modification in the texts, typos, etc. Should we wait to prepare one single issue with all those requests ?

Anyway, here is one:  
In "CSV Mapping", when clicking on the "+"  button at the bottome of a table (button labelled "Map column"), the formular displays with a title "Map column to literal value". See printscreen:

![image](https://user-images.githubusercontent.com/6167669/110747516-cafb9280-823e-11eb-94eb-3cd7b30325a8.png)

The title of the formula needs to be change, right ? maybe "Create column mapping", as when editing an existing mapping the title is "Edit column mapping"

**Comment by l00mi** [comment]
@FabianCretton can you create a PR with the changes in mind?

**Comment by martinmaillard** [comment]
The title makes sense to me. What triggered your request? Was it confusing for you?

**Comment by FabianCretton** [comment]
My meaning was that this form is used either to map a literal value (which is the title of the form), or to create a link to another table. 
i was thinking that "Map column to literal value" is not the correct title when we want to link to another table, no ?
Maybe I am wrong.
And once again, I guess we will have a single issue report for the different typos if needed.

**Comment by martinmaillard** [comment]
Oh but the title changes when you click on `Link to another table`
