### ISSUE TITLE
How to "know" that a modification was done after a transformation ?

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#597]
How does the user know that the current mapping settings on the screen correspond to the values he can see in the Cube Designer, or the cube that was published ?
Same question if a new version of the CSV was uploaded, how do we know that a transformation was done afterwards ?

Proposal: just show a time-stamp for the last modification, that could be compared to the timestamp of the last transformation and then publication ?

**Comment by l00mi** [comment]
Should be solved now with the new project details, if something is missing please reopen @FabianCretton ?
