### ISSUE TITLE
CSV: extract columns and sample data

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#62]
When uploading a new CSV, the backend should extract a list of columns and link them to the source. It should also probably extract a list of unique values for each column.

**DoD**

* [ ] for every column from the csv, create a `cc:CSVColumn` resource
* [ ] `cc:CSVColumn` resources should be stored in the source's graph
    * [ ] annotated sort order of columns
* [ ] if extracting fails, it should not prevent the request from succeeding (file saved to S3, source graph created)
* [ ] sample values stored with each `cc:CSVColumn`

**Example**

Given a `/source/employees.csv` `CSVSource` we should in its very graph create column resources when it is created:

```turtle
graph </source/employees.csv> {
  </source/employees.csv> 
    cc:csvColumn </source/employees.csv/column-id-slug> , 
              </source/employees.csv/column-name-slug> , 
              </source/employees.csv/column-salary-slug> .

  </source/employees.csv/column-id-slug>
    schema:name "id" ;
    cc:csvColumnSample "123", "456", "789" ;
    dtype:order 0 ;
  .

  </source/employees.csv/column-salary-slug>
    schema:name "salary" ;
    cc:csvColumnSample "5k EUR", "5000 AUD", "$6000" 
    dtype:order 1 ;
  .

  # the rest of </source/employees.csv> and its columns
}
```

**Comment by tpluscode** [comment]
Questions:

1. Do we assume unique column names?
2. Got any better ideas for `cc:CSVColumnSample`?

**Comment by martinmaillard** [comment]
Isn't it weird to have a capital letter at the beginning of `cc:CSVColumnSample`? Could we get away with `cc:sampleValue`?

About unique column names, it would be better if we didn't rely on that, but I don't think we really have a choice. I guess it's a reasonable requirement

**Comment by tpluscode** [comment]
Good catch 👌 . Capital would be for classes or datatypes. Let me change that

**Comment by tpluscode** [comment]
> Could we get away with `cc:sampleValue?`

Unless we have a sub namespace for CSV terms I propose to keep the `CSV`/`csv` prefix for term names

**Comment by martinmaillard** [comment]
May I ask why? It feels overly specific in this context. We are using `cc:column` and not `cc:csvColumn` after all.

**Comment by lucafurrer** [comment]
Do we need a hydra:Collection CSVColumnCollection containing the columns?

**Comment by lucafurrer** [comment]
I created a pull request (#70 ) with a first version. Since there are still some discussions about the schemas I let it in state draft

**Comment by lucafurrer** [comment]
Wondering if 20 sample values are too much for the UI? Should the number be reduced by Core or should the UI handle this?

**Comment by lucafurrer** [comment]
> May I ask why? It feels overly specific in this context. We are using `cc:column` and not `cc:csvColumn` after all.

I think `csvw:Column` and `csvw:column` might rather precise since we are talking about csv's.
