### ISSUE TITLE
Transformation job succeeded - no data in cube designer

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#621]
Project : UBD0001-Test-02
https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!udb0001-prtr-test-02-yayj6g6yk76/metadata

J'ai lancé plusieurs transformations.
La première a généré une erreur. J'avais utilisé le type de données boolean pour des valeurs 0 ou 1. J'ai corrigé en INT.
Les transformations suivantes ont réussi, mais aucune données n'apparaît dans le cube-designer.

J'ai remarqué aussi que pour 2 tables, j'obtenais une erreur avec "View generated CSVW" : la table d'observation "ubd0001" et la table "betrieb". Ces 2 tables ont un lien avec la table "haupttaetigkeit", le lien ce faisant avec le champ "Haupttätigkeit_id" qui contient un Umlaut. J'ai supprimé ces liens et la table "haupttaetigkeit" qui est devenu inutile et je peux accéder aux generated CSVW qui bloquaient. J'ai relancé une transformation qui dure encore, mais on dirait bien que le problème venait de cet Umlaut.

J'ai de la peine à dire si la transformation est terminée. L'icône est grise. Mais maintenant des données sont visibles dans le cube-designer.

**Comment by martinmaillard** [comment]
Umlauts in column names does seem to cause an issue when linking to another table. I tested locally and here's the error I saw:
```
labyrinth:request:error Request failed: [Error [SyntaxError]: Expected "(", "*", ",", ":", "}" or [a-zA-Z0-9_.%] but "%E4" found.] { expected: [ '"("', '"*"', '","', '":"', '"}"', '[a-zA-Z0-9_.%]' ], found: 'ä', offset: 11, line: 1, column: 12 }
```

**Comment by tpluscode** [comment]
That's strange. I'm pretty sure we've has non-ASCII chars in templates before 🤔

**Comment by martinmaillard** [comment]
Current status of debugging: the error is caused by the `uri-template` library.
