### ISSUE TITLE
CSV Upload error - hard to find the reason

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#629]
Bonjour, je suis en train de faire des tests avec un fichier .CSV qui me pose problème à l'import.
Je joins le fichier "Forestry_E_All_Data_(Normalized)_50000 rows.csv"
L'import m'indique simplement "Bad Request "
J'imagine que le fichier pose problème, mais comment trouver d'où cela vient ?
J'ai fait une quantité de tests:
- validé le CSV avec différents outils en ligne (dont celui de Zazuko), c'est tout bon
- import dans Excel, c'est tout bon
- puis j'ai commencé à découper le fichier en différentes tailles pour essayer d'identifier une ligne qui poserait problème:
    Un fichier avec les 40'000 première lignes est bien chargé par le Cube Creator.
    J'ai donc fait un fichier avec les lignes 40'000 à 50'000 -> cela passe aussi
Et donc je ne vois plus comment tester pour trouver le problème.
J'imagine que c'est une erreur bête, mais je ne sais pas comment l'identifier.

A noter que durant mes tests, l'issue https://github.com/zazuko/cube-creator/issues/587 est souvent revenu: en voulant remplacer un fichier A (qui avait été chargé correctement), par un autre fichier B, cela donnait le même problème que dans la copie d'écran. MAIS, en créant un nouveau projet et en chargeant ce fichier B -> il passe...il y a donc certainement un problème qui traine lors de ces remplacements de fichier.

Merci pour votre aide
[Forestry_E_All_Data_(Normalized)_50000 rows.zip](https://github.com/zazuko/cube-creator/files/6194700/Forestry_E_All_Data_.Normalized._50000.rows.zip)

**Comment by l00mi** [comment]
@FabianCretton can you please add the link to the project in question?

**Comment by FabianCretton** [comment]
It is just a new empty project, and I upload that first file.
For instance my "fab_tst_csv2": https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fabtstcsv2-vn39zopdayq/csv-mapping

**Comment by tpluscode** [comment]
Turns out the problem is spaces (and likely other character which need to be escaped in an URL).

The s3 service used does not return a correctly escaped link when csv is uploaded.
