### ISSUE TITLE
Missing Dimension in Cube Designer

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#631]
Project : [UBD0001 PRTR - Test 03](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!ubd0001-prtr-test-03-ar7ejbrmve/edit)

Je ne vois pas la dimension **Hauptaetigkeit** dans le cube designer.
Dans le [log](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/8945) du job de transformation, la table **Hauptaetigkeit** apparaît et semble être traitée comme les autres.

Dans un de mes précédents tests j'avais dû effacer cette dimensions qui s'appelait alors **Hauptätigkeit**, parce que l'Umlaut provoquait une erreur. Dans ce projet, j'ai renommé la dimension pour ne pas avoir ce problème. Je ne sais pas si ça peut avoir un rapport avec ça, j'imagine que non, mais on ne sait jamais.

Je contine à tester ce projet qui contient assez de dimension pour mes tests, mais si vous trouvez pourquoi cette dimension n'apparaît pas, j'en serai très content.

**Comment by martinmaillard** [comment]
J'ai supprimé et recréé la colonne et la dimension apparaît maintenant. Il faut que je fasse quelques tests pour voir dans quels cas ce problème peut se produire.

**Comment by PDumasBAR** [comment]
Merci Martin
J'aurais pu essayer moi-même.
Comme indiquer ci-dessus, j'ai eu des problèmes avec cette colonne, mais je suis quasi sûr que c'était dans le [projet 02](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!udb0001-prtr-test-02-yayj6g6yk76/csv-mapping)
Il y a encore les "Umlaut" dans cette colonne.
A+

**Comment by l00mi** [comment]
@PDumasBAR can you still produce this error?

**Comment by PDumasBAR** [comment]
I don't know how it happens.
So I can try, but I'm not sure. 
Perhaps with a new project.

**Comment by l00mi** [comment]
I have the feeling (not more) that it was related with an error we fixed, but this specific project still had an old value in the data. So it might not be able to be reproduced. If this is okay for you, please close the issue for now.
