### ISSUE TITLE
Dimension (e.g. xsd:int) with ""^cube:Undefined the output seems to be done like a nominal with sh:in

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#633]
See wert in : https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!ubd006-t3-k7orldamyq1/metadata

**Comment by tpluscode** [comment]
I think it's understandable. The value `""^^cubs:Undefined` does not really fit the `sh:min/max` range.

Should it be ignored in the generated property shape?

**Comment by l00mi** [comment]
Yes please.
