### ISSUE TITLE
Replace CSV file - 2 issues

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#639]
On my "Fabian Red List Test 1" project, I did a replace for all 3 files.

It worked well, except for "Status.csv" where I had an empty line at the bottom of the file.
I think this is why an error is thus correctly displayed (see printscreen - ON THE LEFT)

Issue 1: However, i did correct the file and upload it once again -> no error message this time, but the displayed error from the former "replace" is still there.
If I do a "download csv", the correct new one is downloaded.
As the new csv has some new columns, which is permitted, the problem is that I do not see the new columns and can not map the new columns.

Issue 2: Just to try, I did Adjust the CSV settings, changed nothing but pressed "Update CSV settings", and got the error that is visible on the same printscreen - ON THE RIGHT

![image](https://user-images.githubusercontent.com/6167669/112463291-59edcc00-8d62-11eb-8a1a-a711da3dd40b.png)

**Comment by FabianCretton** [comment]
I do not know if related, but launching a transform after that did give an error, see:
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/9008

**Comment by l00mi** [comment]
@lucafurrer not sure if you can again take this up regarding hours? I guess you would know it best here?

If not please assign to @tpluscode

**Comment by FabianCretton** [comment]
Today I made another test and I found a problem in the .csv file. 


@l00mi @lucafurrer 

> 
> 
> I do not know if related, but launching a transform after that did give an error, see:
> https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/9008

This was certainly coming from an error that I found in one file.
But the "issue 1" about csv replacing is still an issue.

**Comment by tpluscode** [comment]
@FabianCretton could you provide an example of original and updated csv files which have issues?

**Comment by martinmaillard** [comment]
I think "issue 2" throws an error because "Quote char" is mandatory. The field is empty because it could not be automatically detected, but the form can't be submitting without it.

**Comment by FabianCretton** [comment]
Yes, here are two files to do a simple test in a new project:
Add a csv: status.csv -> it is the correct file, everything works well
Replace csv: choose "Status_wrong.csv" -> the file is wrong, the error that is shown is certainly correct
Now, the problem: do a replace csv again, and choose the correct file -> the error from the former file stays
[Status.zip](https://github.com/zazuko/cube-creator/files/6227203/Status.zip)
