### ISSUE TITLE
Project "Fabian_Jahrbuch Wald & Holz 2020" - Publish job just hung up

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#643]
Today I had a nice experience with the "Fabian_Jahrbuch Wald & Holz 2020" cube.
I was able to replace the smaller "test" file with the original one, a 38 MB file with 400'000 lines.
Eventhough we spoke about not treating "huge" files, I think that this file is in the limit that should be possible to work with the tool. It only has 10 columns, easily loads up with Excel (and is far from the 1 million lines we talked about).

So I was able to transform the file, and this is the good new.
It was not so fast (18 minutes), but I understand that much of the time was certainly needed for the upload in the triple store.
My first question is thus about this transform time, to know what you will decide about the discussions in https://github.com/zazuko/cube-creator/issues/564

Main problem: 
After that I tried to publish. The job did start (as you can see "3/25/2021, 11:28:20 AM"), but I never got any "news" about this, no log file, etc.

**Comment by l00mi** [comment]
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/9066
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/9065

shows the same error as https://github.com/zazuko/cube-creator/issues/628 closing this in favor of the origin issue.
