### ISSUE TITLE
Designer not updated when dimension is saved

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#646]
Related or not, but still about editing dimension metadata:
I open another project "Fabian Jahrbuch Wald&Holz 2020". 
There is no dimension metadata yet.
I edit the first column, enter an english "Name", save -> the name shows-up in the table (see printscreen), but when I edit once again that dimension, the name do not appear (see printscreen)

![image](https://user-images.githubusercontent.com/6167669/112592937-15683c00-8e07-11eb-8c1f-72ed59229d8d.png)

_Originally posted by @FabianCretton in https://github.com/zazuko/cube-creator/issues/644#issuecomment-807980439_

**Comment by tpluscode** [comment]
Doing a full page reload (or navigating to and fro the Cube Designer screen) force a full reload.

This should be reloaded without the need for additional steps

**Comment by l00mi** [comment]
@tpluscode can you please do a smoke test in test before deploying.
