### ISSUE TITLE
Transformation runs endlessly - Project can't be deleted

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#647]
The transformation of project UBD0113_Hochwasser (id: ubd0113/old) runs endlessly. I can't delete the project (Internal Server error). What is the cause? Could you please delete the project for me (NOT Hochwasser-new).
https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!ubd0113hochwasser-zroljrlrma6/csv-mapping

**Comment by tpluscode** [comment]
I can remove the broken project but it's a little weird nonetheless as some resources are simply missing from the mappings.

@ortnever could you explain what you actions you performed leading to the error?

**Comment by ortnever** [comment]
no idee waht I've done. We can just delete my project and close the bug, unless you think it's important to find the cause...to prevent it from happening again.

**Comment by tpluscode** [comment]
Removed.

We'll investigate if this ever happens again
