### ISSUE TITLE
Cube Metadata : time coverage Request validation error

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#649]
Cube Metadata : I have entered the time coverage but I get the error message that the start and end are missing.
e.g Project UBD0104 Badegewässer : Cube ubd0104bis
![image](https://user-images.githubusercontent.com/79834090/112807089-cb39c180-9077-11eb-9f4a-47a98e267b79.png)
![image](https://user-images.githubusercontent.com/79834090/112807152-e0165500-9077-11eb-9c7c-f1a3ad426960.png)

**Comment by ortnever** [comment]
It's strange that I got this message because Data coverage isn't mandatory in Dcat.
Because of this error I couldn't save the metadata so the error is maybe difficult to reproduce.

**Comment by tpluscode** [comment]
> It's strange that I got this message because Data coverage isn't mandatory in Dcat.

The "**Data Period**" is handled as a whole. Thus, both start and end time are required when added. You can remove with the "**-**" icon on the right.

Otherwise, I found no issue with this: added the period fields, selected the start and end dates, validation was successful...

**Comment by l00mi** [comment]
@ortnever I can show you how it behaves if you like.

**Comment by ortnever** [comment]
@l00mi 
Thank you. I did it again and it worked well.
This morning I entered Start date AND end Date, but I got always the same error message.  Also when I removed the fields with  the "-" icon. I can't reproduce the error, so it must be ok.

**Comment by l00mi** [comment]
If everything is fine for now please feel free to "close" the issue! Thank you.
