### ISSUE TITLE
Additional information to show in the Publication List

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#651]
- Last upload of a CSV (date and file name)
- Last modification of mapping (general and for each table)
- Last modification of Cube design

**Comment by l00mi** [comment]
@ortnever please add the description here.

**Comment by ortnever** [comment]
Here the information that should be displayed about the publication, in addition to the date
- cube version (will be taken over by visualize)
- status Publish / Draft
- where the cube is published. For the moment: "opendata.swiss" and/or "visualize".

Information about other stages of the work (not for the Publication List). 
- Last upload of a CSV (date and file name)
- Last modification of mapping (general and for each table)
- Last modification of Cube design

**Comment by l00mi** [comment]
@tpluscode can you please extend the publication list with the upper part. That we see in the list of publications what was the metadata of the publication run. I guess you do not have any structure to describe that yet?

Can we add as a metadata triple the JobId from gitlab? So we can query directly on Lindas to get this infos?

**Comment by l00mi** [comment]
I move this ticket back to back-log for the still open parts, which are less prio:

- Last upload of a CSV (date and file name)
- Last modification of mapping (general and for each table)
- Last modification of Cube design

**Comment by ortnever** [comment]
Parfait. Merci.

**Comment by ortnever** [comment]
@Michael, @pierre : We should discuss next Wednesday if the second part of this issue can be done in the next sprint.

**Comment by ortnever** [comment]
oups, I guess i didn't use the good Email-Adresse, Sorry Michael and Pierre !

**Comment by l00mi** [comment]
@ortnever nono all good lets discuss wednesday.
