### ISSUE TITLE
Undefined values as named nodes?

### ISSUE THREAD

**Issue by herrstucki** [zazuko/cube-creator#657]
More of a question than a request: Would undefined values not better be represented as a **value** `<https://cube.link/Undefined>` than an empty string with **datatype** `""^^<https://cube.link/Undefined>`.

I think it would make them more straightforward to handle and represent in systems/formats that don't support these datatypes (like CSV) where there it's ambiguous what empty strings mean. "Seeing" the IRI https://cube.link/Undefined in those cases would remove this ambiguity.

Compare to NaN and INF which are values of [float/double](https://www.w3.org/TR/xmlschema11-2/#float) instead of special datatypes.

Also: this way they would not "pollute" the datatypes of dimensions like it's described in https://github.com/zazuko/rdf-cube-view-query/issues/45

I'm actually not quite sure if this would be *better* but maybe it's worth considering (if it hasn't been already).

**Comment by l00mi** [comment]
We studied this a while and actually went through more work to have it separate.. the definition for it is here: https://github.com/zazuko/rdf-cube-schema/blob/master/best-practice.md#nullempty-values

**Comment by herrstucki** [comment]
Thanks for the explanation. I wasn't aware of that best practices document!

The distinction between named dimensions -> undefined as value (haven't seen that in the wild yet 😉) and literals -> undefined datatype makes more sense now.
