### ISSUE TITLE
Should generated values not be versioned?

### ISSUE THREAD

**Issue by herrstucki** [zazuko/cube-creator#658]
I ran into an interesting issue. We implemented a feature to let published graphics of visualize.admin.ch use the latest (preferably published) version of a cube, even after publication. As discussed with BAFU and @l00mi.

Now, a published graphic stores the IRI of the original cube (which we can use to find the newest suitable version of it). However, it also stores any values used to filter data. Which generates queries like:
```
FILTER (
    (?dimension5 = <https://environment.ld.admin.ch/foen/ubd0066_t3/22/Station/42>)
  )
```

But this only works as long as the cube `<https://environment.ld.admin.ch/foen/ubd0066_t3/22/>` is used! When we "upgrade" to a newer version such as `<https://environment.ld.admin.ch/foen/ubd0066_t3/23/>` suddenly no data is returned because the value used for the filter does not exist in the newer cube.

I see two possible solutions:
1. We try to replace the version used in the filter values, hoping that using the cube IRI as prefix for the values is used consistently, turning `<https://environment.ld.admin.ch/foen/ubd0066_t3/22/Station/42>` into `<https://environment.ld.admin.ch/foen/ubd0066_t3/23/Station/42>` on the fly.
  👉  This seems like a brittle workaround to me and I would like to avoid it if possible.
2. Generated values omit the version, so they stay consistent across cube versions. In this case: `<https://environment.ld.admin.ch/foen/ubd0066_t3/Station/42>`
  👉  This seems non-trivial to handle on your end because you'd need to ensure that older instances of `<https://environment.ld.admin.ch/foen/ubd0066_t3/Station/42>` are replaced instead of new ones just being added with each cube publish.

For now, I will rather disable the auto-upgrade.

**Comment by tpluscode** [comment]
Definite 👎 for solution 1.

The second option is certainly possible already in two ways:

- Mapping a table to an absolute URI template such as `https://environment.ld.admin.ch/foen/ubd0066_t3/Station/{STATION_ID}` in this case
- possibly Managed Dimensions but additional properties of mapped concepts would not be easily possible

That said, we might reconsider the URI pattern of non-observation tables so that like you say, they are not versioned alongside the cube. 

@l00mi do we really need to version all resources mapped from all tables?

**Comment by tpluscode** [comment]
Forget that other reply.

That's not trivial to figure out. But, given that the URIs are hierarchical, how 'bout the queries use relative identifiers?

```sparql
BASE <https://environment.ld.admin.ch/foen/ubd0066_t3/22/>

SELECT DISTINCT ?dimension5 WHERE {
  GRAPH ?irrelevant {
    <> cube:observationSet ?observationSet ;
    ?observationSet <http://ns.bergnet.org/cube/observation> ?observation .
    ?observation <https://environment.ld.admin.ch/foen/ubd0066_t3/station> ?dimension5 .
  }

  filter (
    (?dimension5 = <Station/42>)
  )
}
```

This way, to upgrade all which needs doing it so change the `BASE`, which happens to be the cube identifier.

**Comment by herrstucki** [comment]
Hmm yes … but isn't this essentially solution 1) 😄 

The issue with this is: I'll initially still get the full IRI of the station (either from the cube shape or when querying observations for it). Because adding BASE to the query doesn't affect the query *result* … dimension5 will be <https://environment.ld.admin.ch/foen/ubd0066_t3/22/Station/42>

So I would need to *make* it relative by stripping the cube IRI before saving and using it as filter, in order to use BASE in subsequent queries.

And: using BASE is not even possible at the moment with rdf-cube-view-query … so instead of using BASE I might as well prefix the relative identifiers again.

**Comment by tpluscode** [comment]
Haha, yes, I suppose it's a variation of the same idea.

Of course, where the fix would happen is debatable. I too think that the responsibility for creating relative URLs would have to be on the query library but @bergos might not like that as a case-specific approach.

**Comment by herrstucki** [comment]
I guess the whole versioning topic will have some more surprises in the future. E.g. when values go missing from future versions etc.

So … I think since we implement the version-upgrade logic on our end, it would make sense to make sure that we also take care of these versioned value IRIs. If Cube Creator switches to generating non-versioned IRIs that shouldn't break anything in the future since the cube IRI won't match those anymore and we keep them as absolute. Meanwhile you can decide if creating versioned IRIs in the first place even is desirable.

**Comment by l00mi** [comment]
I am pretty sure we don't get around to have a URI per Version. We saw some month ago what happened with clashing BNODEs already.  As @herrstucki already mentioned, we might have values missing in future cubes, and also we basically couldn't have multiple versions published. (E.g. published and draft at the same time).

I think the most elegant solution would be to define an unique identifier which is always added to `<https://environment.ld.admin.ch/foen/ubd0066_t3/23/Station/42` .. e.g. `schema:identifier` and then actually filter on the identifier instead of the URI.

In general it is never a good idea to base any query on the semantics of the URI itself.

```sparql
SELECT DISTINCT ?dimension5 WHERE {
  GRAPH ?irrelevant {
    <> cube:observationSet ?observationSet ;
    ?observationSet <http://ns.bergnet.org/cube/observation> ?observation .
    ?observation <https://environment.ld.admin.ch/foen/ubd0066_t3/station> ?dim5.
    ?dim5 <http://schema.org/identifier> ?dimension5 .
  }

  filter (
    (?dimension5 = "42")
  )
}
```

**Comment by herrstucki** [comment]
@l00mi I like the idea of using the `schema:identifier` … which would basically be the identifier used in the identifier template (i.e. the actual column value in the CSV)?

Those are not yet generated, right?

**Comment by herrstucki** [comment]
I *think* I could get it to work in the query library by creating a new lookup dimension for each dimension I'm filtering on. If using schema:identifier becomes the standard way of identifying values for filtering, then of course I'd be happy if there were a shortcut for this 😉 

I wouldn't use schema:name for filters because they are most likely localized and that won't end well 😅 

So … for me the easiest thing right now is to disable upgrading cube versions until we find a proper solution for this.

**Comment by l00mi** [comment]
I just realized that we already have `schema:identifiers` in the schwermetalle. So we can also make it a necessary step on the side of the end-user for now. And later try to automatise. So I would circle back on this to the client and see what is prefered?

**Comment by herrstucki** [comment]
The Station table (where it actually matters) does not have a schema:identifier.

Shouldn't they just follow the same logic that is used to generate the IRIs in the first place, i.e. use the interpolated part of identifier pattern? I don't think it's a good idea to leave this up to the user. What do we do if they forget to add it or do it incorrectly?

Also, I might be wrong but I'm pretty sure it would be possible to create duplicate schema:names from a table like this:

| id | name |
|----|------|
| 1 | oops |
| 2 | oops |

… so filtering on names definitely sounds bad to me 😄

**Comment by l00mi** [comment]
Agreed on the names. And yes I agree we might add the id by default.

**Comment by bergos** [comment]
I'm not so happy with the `schema:identifier` solution.

- One would expect the triple contains the identifier used in the source system. That means cube creator is not the authority of this id and the value could change from one version to the next one.
- It's a poor man's, non-Linked Data solution for `schema:sameAs`.

I would propose to use `schema:sameAs`. The IRI would be a base IRI + a sequence. If the data structure of the CSV changes between versions, the application could use the IRI to store the information required to identify the column in all versions of the CSV. That could be one or more `schema:identifier`, but also an index.

I don't want to add this feature to the query library. Versioned properties are somehow an indicator that the cube is still in progress until it uses 100% managed dimensions. Adding all kinds of "in progress to possible final structure" mappings will end up in a mess in the API of the library and the code. I would propose to use a `@rdfjs/term-map` and a simple SPARQL query to fill the map.

**Comment by l00mi** [comment]
* We did not specify where schema:identifier comes from, I would think it should be created by the cube creator exactly.
* Can you make an example like above how the schema:sameAs could be used here?
* I am not sure if I understand, this issue does not touch the problem of changing structure? The versions are of cubes which evolve in adding new data, that makes the IRI change because of the version number.

**Comment by l00mi** [comment]
Okay final solution is the same as proposed but with an IRI instead a literal.

```sparql
SELECT DISTINCT ?dimension5 WHERE {
  GRAPH ?irrelevant {
    <> cube:observationSet ?observationSet ;
    ?observationSet <http://ns.bergnet.org/cube/observation> ?observation .
    ?observation <https://environment.ld.admin.ch/foen/ubd0066_t3/station> ?dim5.
    ?dim5 <http://schema.org/sameAs> ?dimension5 .
  }

  filter (
    (?dimension5 = <https://environment.ld.admin.ch/foen/ubd0066_t3/Station/42>)
  )
}
```

**Comment by l00mi** [comment]
Will be Implemented though #666

**Comment by l00mi** [comment]
@herrstucki Addendum,

So you will be able to use the `sameAs` to filter without the version problem. One caveat, if we have "shared dimensions", they will be already, non versioned to start with, and thus need a slightly different filter strategy.

**Comment by herrstucki** [comment]
@l00mi To make sure I understand the change that we need to implement:

- We cannot use the IRIs from `sh:in` directly anymore (because they stay versioned) but need to use them to look up the `sameAs` unversioned IRIs
  - But *if* there is no `sameAs`, we fall back to the original IRIs because the assumption is that these are managed and not versioned
- Reversely, when we filter, we need to lookup `sameAs` if the dimension was versioned in the first place
  - But if it's unversioned, we filter directly

So we need to a) figure out which dimensions are versioned and b) track this information somewhere, so we apply filters correctly.

Or is it better to do this in the query itself and filter like this:

```sparql
SELECT DISTINCT ?dimension5 WHERE {
  GRAPH ?irrelevant {
    <> cube:observationSet ?observationSet ;
    ?observationSet cube:observation ?observation .
    ?observation <https://environment.ld.admin.ch/foen/ubd0066_t3/station> ?dim5.
    ?dim5 <http://schema.org/sameAs> ?dim5same .
  }

  filter (
    (?dim5same = <https://environment.ld.admin.ch/foen/ubd0066_t3/Station/42>) ||
    (?dim5 = <https://environment.ld.admin.ch/foen/ubd0066_t3/Station/42>)
  )
}
```

**Comment by herrstucki** [comment]
Yes, adding a hint to the shape should make it easier … but not simpler I guess because we rely on the shape adding new special semantics for something expressed with a pretty generic relationship (`schema:sameAs`) in the data itself that doesn't describe the versioning aspect.

Also, I still wonder a bit if we're approaching this from the right angle. Shouldn't the cubes point to _unversioned_ values directly that themselves can reference versions? Similar to [swisstopo municipalities](https://ld.geo.admin.ch/boundaries/municipality/2553?format=html)?

**Comment by l00mi** [comment]
That was the discussion we had. The problem is that the values e.g. schema:name for a e.g. Station can change with time.On 7 Apr 2021 13:41, Jeremy Stucki ***@***.***> wrote:

Yes, adding a hint to the shape should make it easier … but not simpler I guess because we rely on the shape adding new special semantics for something expressed with a pretty generic relationship (schema:sameAs) in the data itself that doesn't describe the versioning aspect.

Also, I still wonder a bit if we're approaching this from the right angle. Shouldn't the cubes point to unversioned values directly that themselves can reference versions? Similar to swisstopo municipalities?
