### ISSUE TITLE
Version 1.0.2 - A specific project can not be deleted, "internal server error"

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#660]
I can not delete my project "Fab test Forestry - Less than 1 Mio Lines - corrupted", it gives an "internal server error"
Might be related to: https://github.com/zazuko/cube-creator/issues/647

**Comment by l00mi** [comment]
This seems to be migration related during development. Shall we delete this manually?

**Comment by l00mi** [comment]
@tpluscode will kill this project.

**Comment by FabianCretton** [comment]
The situation is still the same. If it is not a bug to correct in Cube Creator, yes, you can delete that project.
