### ISSUE TITLE
Designer: Show labels for shared terms

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#689]
Right now the cube preview only shows `schema:name` of terms generated by the transformation pipeline. A shared dimension term will always show as the URI and needs a click to load the preview panel

A proposed improvement is to try dereferencing URIs if no label is found in the cube query response.

If dereferenced but on `schema:name` in the selected language is found - keep the URL.

**Comment by l00mi** [comment]
Its perfect, check with @martinmaillard who is better to take a look at it.
