### ISSUE TITLE
Error uploading multiple CSVs

### ISSUE THREAD

**Issue by mbch** [zazuko/cube-creator#693]
I had to split an Excel File into 9 csv files and used the dragged all 9 at once into the CSV file box.
![Upload_Error](https://user-images.githubusercontent.com/20608869/116092017-ba479480-a6a5-11eb-8fff-d8e360f9903f.png)

The files are very small - each one is below 10 KB.
I got the above "Internal Server Error" - but when I closed the windows, refreshed the page 6 out of 9 files were uploaded correctly. I could upload the missing three one by one afterwards - so it's nothing related to the files. 
Is this a known problem?

**Comment by tpluscode** [comment]
I found the error in logs and it appears to originate from the SPARQL endpoint. 

Not strictly related to upload, and a transient problem. It appears occasionally in various locations in the application. We'll keep monitoring it in a #699
