### ISSUE TITLE
Default values do not have data type

### ISSUE THREAD

**Issue by magdasalatka** [zazuko/cube-creator#717]
This setup:
![image](https://user-images.githubusercontent.com/48995317/118654272-adbbe500-b7e8-11eb-9de4-aeed5cd365cc.png)

Results in "0", as default. One would expect it to be  `"0"^^<http://www.w3.org/2001/XMLSchema#integer>` 

Reproducible example: https://cube-creator.zazuko.com/app/cube-projects/cube-project!!animalpest-ogdyd2oqvm0/csv-mapping

**Comment by tpluscode** [comment]
I think it should use the same type selected right above, would you agree?

**Comment by magdasalatka** [comment]
yes, makes sense

**Comment by tpluscode** [comment]
Depends on https://github.com/rdf-ext/rdf-parser-csvw/issues/33
