### ISSUE TITLE
Duplicate entries in shared dimension table

### ISSUE THREAD

**Issue by herrstucki** [zazuko/cube-creator#719]
I noticed that for example in the https://environment.ld.admin.ch/foen/ubd0104bis/10/ cube, some of the entries in the https://environment.ld.admin.ch/foen/ubd0104bis/station dimension have multiple labels, therefore they will show up multiple times in a query result. E.g.

```json
{
  "value": "https://environment.ld.admin.ch/foen/ubd0104bis/10/Station/CH21040",
  "label": "Albergo Rivabella"
},
{
  "value": "https://environment.ld.admin.ch/foen/ubd0104bis/10/Station/CH21040",
  "label": "Hotel Ristorante Arbostora"
},
```

I think this should be prevented since there is no way of knowing _when_ which of those labels should be used.

(A workaround on our end could be to combine them into one label)

CC @ortnever

**Comment by l00mi** [comment]
I think it might be an error in the Input data?

If not longterm we might see multiple labels like this, the way to deal with it might be exactly that the consumer decides to concatenate these labels automatically @herrstucki.

**Comment by ortnever** [comment]
I confirm this is a problem in the original data. Sorry about that. The station CH21040 has apparently changed its name in 2018 (same Coordinates).  I need to check with the data provider how we should handle these cases in the data.

**Comment by herrstucki** [comment]
@l00mi might also be something consider for data validation in the future? Or is there a scenario where multiple labels (in the same language) ever make sense?

**Comment by l00mi** [comment]
Yes and yes.

First of all that would be one of the first checks in the data validation we would need to do.

Also there might be multiple Labels in one Language per Thing. That is reality, and it would be better to allow this fact, then to make a *work around* of just putting it together. I know as a data consumer this is cumbersome, but it is a smart move to always expect multiple labels.

@ortnever what I don't like in the dataset and in general is the use of the Title to put in the unit (CFU/100ml) we need to add this as a unit, if the unit is missing, we can add it.

**Comment by ortnever** [comment]
@l00mi 
There is already Colony Froming Unit in the list. Could please add CFU/100 mL. Thank you.
![image](https://user-images.githubusercontent.com/79834090/118799252-cab2ef80-b89e-11eb-9765-f0c52f46e025.png)
