### ISSUE TITLE
When Stardog is not available, Cube Creator displays no error but hangs-on

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#723]
This should not happen very often (hopefully), but the Cube Creator screen was just displaying the hourglass for a while without any response (see printscreen).
I then realized that Stardog seemed down, but to discover that I had to launch Stardog Studio or the Sparql end-point. 
Should there be a time-out, or a way to tell the user that there is a problem with the Stardog back-end ?

![image](https://user-images.githubusercontent.com/6167669/118953283-f694aa80-b95c-11eb-9170-4d785cf9e4ca.png)

**Comment by l00mi** [comment]
We prefer to report to the development actively instead of showing an error. Is this okay?
