### ISSUE TITLE
Import: enforce cube URI rules for imported cubes

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#724]
When creating/updating an import project:

1. Cube identifier must be based in the owning organisation's namespace
2. No two projects (CSV. **and** import**) should publish the same cube

The latter means that given existing projects:

```turtle
<org> 
  cc:namespace <http://example.cubes.org/base/> .

<csv-project>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  dcterms.identifier "cube/one" ;
.

<import-project>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  CubeProject:sourceCube <http://example.cubes.org/base/cube/two> ;
.
```

It should be impossible to store any of the following

```turtle
# identifier clashes with existing CSV project 
# (this check we already have)
<>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  dcterms:identifier "cube/one" ;
.

# identifier clashes with existing import project
<>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  dcterms:identifier "cube/two" ;
.

# imported cube clashes with existing CSV project
<>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  CubeProject:sourceCube <http://example.cubes.org/base/cube/one> ;

# imported cube clashes with existing import project
<>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  CubeProject:sourceCube <http://example.cubes.org/base/cube/two> ;

# imported cube does not match org namespace
<>
  a cc:CubeProject ;
  schema:maintainer <org> ;
  CubeProject:sourceCube <http://example.cubes.org/cube/three> ;
```

**Comment by l00mi** [comment]
I see, the interaction with a given dc:identifier for CSV projects and full namespace is non-trivial. But I think you covered all the points. Might it make sense to also add at the time creating `dcterm:identifiers` or importing an existing cube directly a `CubeProject:targetCube` to make the checks simpler?

@martinmaillard can you also have a look to double check me.

**Comment by martinmaillard** [comment]
The first rule reduces the possibilities of the tool quite a bit, but if we agree that it's a good idea, the checks look good 👍

**Comment by tpluscode** [comment]
Reduces how?

**Comment by martinmaillard** [comment]
Forcing all cubes to be in the maintainer org namespace sounds very customer-specific to me. I may be wrong 🤷

**Comment by tpluscode** [comment]
It is a possibility but not so easy right now. We expect Organisation to have a a single namespace, which is the base for cube URI

With multiple, we'd need to have a second property to also list the valid bases for imported cubes

**Comment by l00mi** [comment]
yes yes, the "organisation" is in my mind more a "profile". meaning we could have multiple profiles for one organisation with different namespaces.

**Comment by tpluscode** [comment]
Simple as it may sound, you actually added an additional indirection. I propose that for now we either keep this open, or do as said above, only allowing the configured namespace.
