### ISSUE TITLE
Project can become wrongly saved with two values for identifier template - blocks UI

### ISSUE THREAD

**Issue by ortnever** [zazuko/cube-creator#727]
Concerning Project UBD0037 Laermbelastung: When I deleted a dimension in my Observation table to replace it by a link to another table, the "CSV Mapping" page froze. I tried to close and re-open the project and to refresh the page several times. I tried also to start the transformation. 
Could you "unblock" this project ? I would like to use it. And find the reason of the error of course...if possible!

**Comment by tpluscode** [comment]
Looks like somehow the **Observation** table got saved with two identifier templates: `{Referenzjahr}/{Gemeindetyp}/{Verkehrsart}/{Lärmbelastete Einheit}/{Beurteilung}/{Periode}/{Wert}/{Bemerkung}` and `{Referenzjahr}/{Gemeindetyp}/{Verkehrsart}/{Lärmbelastete Einheit}/{Beurteilung}/{Periode}Referenzjahr}`

I removed the second, which is actually invalid.

We have not had this before. Hard to tell how exactly this happened without exact steps to reproduce.

**Comment by ortnever** [comment]
Thanks Tomas for your very quick reaction. I remember generating the ID automatically and then deleting Werte and Bemerkung which aren't needed for the ID. Maybe I introduced the error at this moment? I will try to reproduce it, if I find time. In any case, if there's the reason, the project shouldn't crash but we should get a message.
