### ISSUE TITLE
Only english label of Shared Dimension is "resolved" in cube viewer

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#731]
In https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!ubd006-t3-k7orldamyq1/metadata/resource/https:%2F%2Fld.admin.ch%2Fcube%2Fdimension%2Fel01%2Fcr we see multiple labels also for FR and DE in the shared dimension, but the listing only works in EN.

**Comment by l00mi** [comment]
<img width="2837" alt="Screenshot 2021-05-22 at 00 21 57" src="https://user-images.githubusercontent.com/502518/119203715-04991700-ba94-11eb-80a7-42e4fbfda08e.png">

**Comment by tpluscode** [comment]
I think I noticed that and problem is a little more subtle. The language dropdown only changes the headers but not the data

However, if you change the page, the correct language will be displayed
