### ISSUE TITLE
Cube Designer - Data kind do not show up

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#740]
I did set a data kind for year, the icon is displayed in the column header, but when editing the metadata the data kind and time precision are not displayed.

I do not really understand those values, just reporting this "edition" behavior

![image](https://user-images.githubusercontent.com/6167669/119525844-24278c80-bd7f-11eb-8a64-8a72ade502fb.png)

**Comment by tpluscode** [comment]
Thank you @FabianCretton 

Small issue, we can already fix in next release
