### ISSUE TITLE
Cube dimensions, in shacl, seems not queryable on the SPARQL end-point

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#757]
I report this issue here and assign @tpluscode, as requested by @l00mi   
Michael suspects a problem on Yasgui.

I wanted to query about the dimensions of a cube, but do not get any result for such a [query](https://s.zazuko.com/UKutX) 
The shape is there, as for instance:  
`<https://environment.ld.admin.ch/foen/fab_tst_2/5/> <https://cube.link/observationConstraint> <https://environment.ld.admin.ch/foen/fab_tst_2/5/shape/> .
`  

The "shacl#property" are found, and this query
`<https://environment.ld.admin.ch/foen/fab_tst_2/5/shape/> <http://www.w3.org/ns/shacl#property> ?prop .`
gives for instance :
```
genid-e6e3456fb29f4066a3a7846d5aa25198-1BD40DF65B7D1A81B847E75D496F32D1
genid-e6e3456fb29f4066a3a7846d5aa25198-908263B2D99C63CDF319B53E0C7FB784
genid-e6e3456fb29f4066a3a7846d5aa25198-1ED4E52DA0FAE880B4C24D35D1C787FD
```
But then no data seems available about each property (i would look for schema:name, sh:path, etc.), see my query link here above.

**Comment by tpluscode** [comment]
Very strange. Not only the latest version 5 but also version 2 do not have the details about their shape properties. These appear to be the only such cubes in Lindas.

They are not new, right? They were complete before?

**Comment by FabianCretton** [comment]
Yes, they are older cubes. We might just disregard this problem if it is not happening anymore.  
At least I know that I was looking for the information at the right place and I will try with other cubes.
Thanks
