### ISSUE TITLE
Error in Pipeline

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#758]
On this project : [UBD0001 PRTR - Test 03](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!ubd0001-prtr-test-03-ar7ejbrmve/metadata)

I've made an initial mapping and transformation with an extract (10%) of the whole dataset (12000 observations)
With this version I can see the dataset in Visualize and make graphics, but of course incomplete.

I've made some little changes to the mapping, defining Key Dimensions and Data Kind, and I replace the observations CSV with the full version on Tuesday. The transformation works, but Visualize can't load the dataset ???

As I need at least something to do the tests in Visualize, I've reloaded the extract and tried to transform it, but each time the result is a blue icon and an error in the [pipeline](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/11617) :

> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> FetchError: request to https://stardog-int.cluster.ldbar.ch/cube-creator?graph=https%3A%2F%2Fpipelines-integ.lindas.admin.ch%2Fcube-project%2Fubd0001-prtr-test-03-ar7ejbrmve%2Fcube-data failed, reason: read ECONNRESET
>     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
>     at ClientRequest.emit (events.js:388:22)
>     at ClientRequest.emit (domain.js:470:12)
>     at TLSSocket.socketErrorListener (_http_client.js:475:9)
>     at TLSSocket.emit (events.js:376:20)
>     at TLSSocket.emit (domain.js:470:12)
>     at emitErrorNT (internal/streams/destroy.js:106:8)
>     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21)

I've made several tries with different CSV adapted to the new mapping (key dimensions) but always with the same result.
Can someone take a look on this project and give me a clue to solve the problem.

**Comment by FabianCretton** [comment]
Could be related to https://github.com/zazuko/cube-creator/issues/756 ?

**Comment by l00mi** [comment]
@FabianCretton yes, i close this one in favoer of #756
