### ISSUE TITLE
PXCube - Create Project "Request validation error" message

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#765]
It did happen once or twice that one pressing the "create project" button, that error message was displayed:
![image](https://user-images.githubusercontent.com/6167669/122002230-c43a6980-cdb1-11eb-8466-dbaec02f49d6.png)

**Comment by martinmaillard** [comment]
I was not able to reproduce yet.

**Comment by l00mi** [comment]
@FabianCretton does this still not work for you? If it works please close the issue.
