### ISSUE TITLE
PXCube - Long name push the tabs and "import" button out of the screen

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#766]
When the name of the cube is long, we no more see neither the tabs nor the 'import' button.

![image](https://user-images.githubusercontent.com/6167669/122002395-f6e46200-cdb1-11eb-97c6-ce9cded475bf.png)

Of course, such a long name is not something we might want, but there still seems to be a "design" issue.

**Comment by martinmaillard** [comment]
This should be fixed now (https://github.com/zazuko/cube-creator/pull/761)
