### ISSUE TITLE
Add missing Dimension metadata for PX-Cubes

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#776]
From @herrstucki 

> I just checked the cube https://environment.ld.admin.ch/foen/px/0703030000_124/2/
>  
> It appears that there are quite a few issues with the dimensions in the shape (see https://s.zazuko.com/2aPtCZ).
>  
> No shacl:datatype
> No shacl:minInclusive, shacl:maxInclusive for measures and the year dimension (this shouldn’t have a shacl:in list of values)
> No qudt:scaleType
> No schema:version
> …?

**Comment by l00mi** [comment]
@tpluscode see also https://github.com/visualize-admin/visualization-tool/issues/126

**Comment by l00mi** [comment]
@rdataflow follow here

**Comment by bergos** [comment]
The [buildCubeShape](https://github.com/zazuko/barnard59-rdf/blob/master/manifest.ttl#L13) operation should be part of the pipeline. It adds min, max, in, datatype, ... to the cube shape.

**Comment by tpluscode** [comment]
That would be [here](https://gitlab.ldbar.ch/pipelines/foen-px-pipeline/-/blob/master/pipelines/pipeline.ttl)?
