### ISSUE TITLE
Pipeline fails as successfull

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#782]
These pipelines should be red: https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/12718

**Comment by Rdataflow** [comment]
@l00mi should this pipelines be red as well?
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/12982

**Comment by l00mi** [comment]
@Rdataflow they are read, they just take over 1h.. i put the limit to 2h now.

**Comment by Rdataflow** [comment]
thanks for increasing, I'll rerun.
I guess they should be indicated as red here: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!ch-bafu-wald-faostat-prod-test002-xxqnddvzz4b/publication top right next the _transform_ button

**Comment by l00mi** [comment]
@Rdataflow can you please open a issue on https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning to revamp this indicator to stay in sync with the gitlab pipelines?

**Comment by Rdataflow** [comment]
it looks like failing pipelines under certain conditions (see above) end up with _schema:CompletedActionStatus_ instead of _schema:FailedActionStatus_

**Comment by tpluscode** [comment]
Well that's odd. You would see a log message that the pipeline updates the status. Obviously it's not there so it's surprising that the job is green

**Comment by Rdataflow** [comment]
that's exactly what surprised me most.
