### ISSUE TITLE
If the ID of an auxiliary table is the empty string, add a cube:Undefined

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#789]
In the case where an ID is empty, e.g. https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!umweltausgaben-rxy46wgppv5/csv-mapping

<img width="1111" alt="Screenshot 2021-07-06 at 19 56 06" src="https://user-images.githubusercontent.com/502518/124645919-4dfec380-de94-11eb-9e8d-fc05a3704746.png">

{Remarqe} is the empty string, add a 'cube:Undefined`.

**Comment by l00mi** [comment]
No, instead of creating the entity on the observation itself only https://cube.link/Undefined shall be added.

**Comment by tpluscode** [comment]
OK, that makes sense be might be tricky.

The [spec](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#uri-template-properties) says

> ```
>EXAMPLE 9: definition of aboutUrl using column titles
>    "aboutUrl": "http://example.org/tree/{on_street}/{GID}"
> ```
>
>If the value of the `on_street` or `GID` column were `null`, the URL would still be generated with the null value generating an empty string in the URL. For example if `on_street` were `null` and `GID` were `3`, the generated URL would be `http://example.org/tree//3`.

We will need a way to reliably recognise URIs resulting from `null` cells and filter them out in the transformation pipeline.

This is actually a bummer and I wish CSVW worked like R2RML where null cells in fact produced null URIs
