### ISSUE TITLE
Import an existing cube

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#79]
Start a new project from an existing cube

A lot of things need to be clarified. There are some infos in #11

**Comment by lucafurrer** [comment]
I think #135 solves this as well, no?

**Comment by martinmaillard** [comment]
What's missing to get this feature is the ability to import an existing cube. I'll rename the issue.

**Comment by l00mi** [comment]
Pre-requirement: Cube produced by our pipeline.

Steps todo:
* Pipeline to copy the external cube: currently data.zazuko.com -> cube-creator on lindas
  * Make sure to not have cubes reimported in the same namespaces in a new project.
* We assume final URIs which are published.
* Metadata:
  * Copy already present metadata to the graph which is editable?
  * Publish is mostly the same.

**Comment by l00mi** [comment]
Input RAW Cubes from PX for testing: https://github.com/zazuko/rdf-parser-px

**Comment by l00mi** [comment]
@tpluscode and @martinmaillard please keep the overall effort below 8 days of work.

**Comment by l00mi** [comment]
please update status every second week at https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/280
