### ISSUE TITLE
Switch TermsOfUse and CreativeWorkStatus to new URI

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#793]
TermsOfUse and CreativeWorkStatus change location from 

https://ld.admin.ch/definedTerm/CreativeWorkStatus
to
https://ld.admin.ch/vocabulary/CreativeWorkStatus

(also add Unlisted)

and 

https://ld.admin.ch/definedTerm/TermsOfUse
to
https://ld.admin.ch/vocabulary/TermsOfUse

Change accordingly to use new resource URIs.

**Comment by martinmaillard** [comment]
Set both for now
