### ISSUE TITLE
Apply the S3 CORS policy on start

### ISSUE THREAD

**Issue by sandhose** [zazuko/cube-creator#797]
Because since #794 the UI directly uploads to S3, the bucket needs to have proper CORS policy configuration. The current configuration was manually applied using `s3cmd`, but it would be better to have it applied on application start.

The current applied configuration looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
 <CORSRule>
   <AllowedOrigin>https://pipelines-test.lindas.admin.ch</AllowedOrigin>

   <AllowedMethod>GET</AllowedMethod>
   <AllowedMethod>PUT</AllowedMethod>
   <AllowedMethod>POST</AllowedMethod>

   <MaxAgeSeconds>3000</MaxAgeSeconds>

   <ExposeHeader>ETag</ExposeHeader>

   <AllowedHeader>Authorization</AllowedHeader>
   <AllowedHeader>x-amz-date</AllowedHeader>
   <AllowedHeader>x-amz-content-sha256</AllowedHeader>
   <AllowedHeader>content-type</AllowedHeader>
 </CORSRule>
 <CORSRule>
   <AllowedOrigin>*</AllowedOrigin>
   <AllowedMethod>GET</AllowedMethod>
   <MaxAgeSeconds>3000</MaxAgeSeconds>
 </CORSRule>
</CORSConfiguration>
```

Note that CORS policy isn't implemented by Minio (used in dev environments), so this should only warn and not crash if applying the policy fails.

Relevant S3 SDK docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketCors-property

**Comment by l00mi** [comment]
@ludovicm67 can you extract the necessary infos from @sandhose and try a solution?

**Comment by sandhose** [comment]
The CORS policy was already manually applied ; now it would be best if it was applied on startup via the S3 SDK methods I pointed above. It would be probably more relevant if someone from the dev team was assigned to this instead of having @ludovicm67 dig into this codebase

**Comment by l00mi** [comment]
@martinmaillard @tpluscode comments?

**Comment by martinmaillard** [comment]
If it needs to be done by us I would say: back to the backlog
