### ISSUE TITLE
Tiny error in sample dataset

### ISSUE THREAD

**Issue by lapidus** [zazuko/cube-creator#802]
Small note:

I tried importing this .trig file but the dateTime (in 2 instances) seems invalid (70 seconds is out of bounds): 
https://github.com/zazuko/cube-creator/blob/8817b1f6668c1438b974511b8eb5af50a81c6109/fuseki/sample-ubd.trig#L699

**Comment by tpluscode** [comment]
That's an interesting catch.

Local environment uses Fuseki and it does not complain about the lexical structure of dates. What store are you using?
