### ISSUE TITLE
Export Cube Project

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#811]
Part of https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/277

It should be possible to export all project resources so that a project can later be imported in a second instance.

### DoD

A trig file is downloaded containing all RDF of project and its related resources

### Details

To provide the export, it should be sufficient to offer a link to `GET /project/test/export`. If necessary, in the future we might change that resource to (also) allow a `POST` with additional export options.

The RDF would ideally be serialised as relative URIs, so that the destination instance parses with its base. So, for a project `https://example.creator.cube/project/test` the output would be something like

```turtle
# No base directive so it can be parsed easily using destination's base URI
# like, BASE <https://destination.instance/project/test/>

# by making URIs relative to project identifier, 
# we can create a new project on the destination system and use it as base
graph <> {
   <> a cc:Project .
}

graph <source/foo> {
   <source/foo> a cc:CSVSource .
}

graph <source/bar> {
   <source/bar> a cc:CSVSource .
}
```

It is important that we exclude the graph with transformed/imported cube data

#### How to retrieve resource graphs?

The query could simply select all graphs which share a common project's base by filtering with `STRSTARTS`. This appears well indexed and the query is very efficient

#### Is there anything we want to exclude from export?

In addition to the observation data, what else would we possibly exclude from the export? Of all the resources we have, I suppose that the transform jobs maybe? But not publish jobs?

**Comment by l00mi** [comment]
I like the overall description and the proposed attack vector. 

Please make sure that it is clear for future developments what is necessary that the new functionality is also in the export/import relatively.

**Comment by tpluscode** [comment]
Right. This can work because all identifiers within a project space share its identifier as base namespace. This would be the only requirement

**Comment by tpluscode** [comment]
By quick experimentation I find that it's most efficient to first `SELECT DISTINCT ?g` of all graphs and then use the result to retrieve the data

```sparql
PREFIX cc: <https://cube-creator.zazuko.com/vocab#>

# Avoid CONSTRUCT { GRAPH {} }, which is Stardog-specific
select ?s ?p ?o ?g 
WHERE {
    {
        select distinct ?g {
            GRAPH <${projectId}> {
                <${projectId}> cc:cubeGraph ?cubeData
            }
            GRAPH ?g { ?s1 ?p1 ?o1 }
            
            FILTER ( ?g != ?cubeData )
            FILTER (
                STRSTARTS(STR(?g), '${projectId}' )
            )
        }
    }

    GRAPH ?g { ?s ?p ?o }
}
```

**Comment by Rdataflow** [comment]
@tpluscode can you look at #829 export returns 404?
