### ISSUE TITLE
Unlist a published Cube

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#821]
https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/285

- [ ] Use `schema:expires` instead of `schema:validThrough` (migration path?)
- [ ] Unlisting a cube sets `schema:expires` on all previous versions of the cube
- The cube library should ignore all expired cubes by default

To be able to unlist we further need to tweak how we `expire` current Cubes. The rule set should be:
* Publishing a "Published" cube does expire all former cubes.
* Publishing a "Draft" does `expire` all former "Draft" cubes and does not touch the "Published" cube.
* Unlisting will add `expire` to all cubes.

**Comment by l00mi** [comment]
Also documented in https://github.com/zazuko/rdf-cube-schema-viz/blob/master/README.md#version-history-of-cubes and https://github.com/zazuko/rdf-cube-schema-viz/issues/1. 

@herrstucki our proposition is to add `schema:expires` additionally and stop doing it once you have added the change on your side. Can you provide us an issue to track this?

**Comment by l00mi** [comment]
After reflecting how it works on your side, you do not take `schema:validThrough` in consideration at all correct?
