### ISSUE TITLE
Transform of large dataset does timeout (takes longer than 2 hours)

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#827]
I tried a transform of [Fabian_Jahrbuch Wald & Holz 2020](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fabianjahrbuch-wald-holz-2020test-2-xm3v67vbpkp/csv-mapping)
Which starts with a time out of 2 hours, and failed "ERROR: Job failed: execution took longer than 2h0m0s seconds"
Here is the [log](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/14597).

Question:
- Should the time-out be increased ?
- Why did [another project](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/13709) run in august during 143 minutes, was it another setting ?

**Comment by l00mi** [comment]
Current Issue https://control.vshn.net/tickets/SBAR-480

**Comment by FabianCretton** [comment]
On 22.09, transformation of the same cube was successful and took 22 minutes.

**Comment by FabianCretton** [comment]
But the publication of that cube failed - time-out after 2 hours

**Comment by l00mi** [comment]
transformation is now reliable.. publication is handled in other tickets.
