### ISSUE TITLE
Cube designer seems slow to display 10 lines of a big dataset

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#828]
Projet [Fab test Forestry - 242 MB](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-forestry-3xrvo6r60jo/csv-mapping)
A pretty large dataset, the .csv is 242 MB and 2 millions lines (i give the CSV size, I did not check about the number of triples).

But to display the Cube Designer, it takes 25-30 seconds for the 10 lines display (each paging takes 25-30 seconds).

Remark: for another big dataset, but smaller, the display takes 4-5 seconds:
"Fabian_Jahrbuch Wald & Holz 2020", csv of 40MB, 400'000 lines

Question:
- Why is it so slow, is it a slowness of the SPARQL query, can it be improved or is it just a special case ?

**Comment by FabianCretton** [comment]
Hi, any news about this ?
Today I see that the Forestry cube given as example still takes 25-30 seconds to display 10 lines (out of 2 millions).
Is it the best that can be expected ?
I coud try some queries, but as we can still not publish those big datasets (ECONNRESET), I do not have access to those cubes.
Thank you for any update

**Comment by tpluscode** [comment]
Here's the generated query and it took the bulk of the time to show your data.

```sparql
SELECT DISTINCT ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 ?dimension6 ?dimension7 WHERE {
  GRAPH <https://int.cube-creator.lindas.admin.ch/cube-project/fabforestrynormalized-5ljx6a5axdk/cube-data> {
     <https://environment.ld.admin.ch/foen/fab_forestry_normalized> <https://cube.link/observationSet> ?observationSet0 .
    ?observationSet0 <https://cube.link/observation> ?source0 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/year> ?dimension0 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/unit> ?dimension1 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/value> ?dimension2 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/area> ?dimension3 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/item> ?dimension4 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/element> ?dimension5 .
    ?source0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?dimension6 .
    ?source0 <https://cube.link/observedBy> ?dimension7 . 
  }
}
GROUP BY ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 ?dimension6 ?dimension7
ORDER BY ASC(?dimension0) LIMIT 10 OFFSET 0
```

We'll see what can be done to optimise it

**Comment by l00mi** [comment]
Why DISTINCT?On 25 Nov 2021 10:09, Tomasz Pluskiewicz ***@***.***> wrote:
Here's the generated query and it took the bulk of the time to show your data.
SELECT DISTINCT ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 ?dimension6 ?dimension7 WHERE {
  GRAPH <https://int.cube-creator.lindas.admin.ch/cube-project/fabforestrynormalized-5ljx6a5axdk/cube-data> {
     <https://environment.ld.admin.ch/foen/fab_forestry_normalized> <https://cube.link/observationSet> ?observationSet0 .
    ?observationSet0 <https://cube.link/observation> ?source0 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/year> ?dimension0 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/unit> ?dimension1 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/value> ?dimension2 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/area> ?dimension3 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/item> ?dimension4 .
    ?source0 <https://environment.ld.admin.ch/foen/fab_forestry_normalized/element> ?dimension5 .
    ?source0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?dimension6 .
    ?source0 <https://cube.link/observedBy> ?dimension7 . 
  }
}
GROUP BY ?dimension0 ?dimension1 ?dimension2 ?dimension3 ?dimension4 ?dimension5 ?dimension6 ?dimension7
ORDER BY ASC(?dimension0) LIMIT 10 OFFSET 0
We'll see what can be done to optimise it

**Comment by l00mi** [comment]
@bergos This query is created by the cube-query-view-library. Why does it make a DISTINCT and a GROUP BY? (This seems to force the Database to look at every datapoint before giving an answer.)

**Comment by bergos** [comment]
Otherwise you get duplicated lines if you skip a dimension.

**Comment by l00mi** [comment]
Blocked by https://github.com/zazuko/rdf-cube-view-query/issues/64

**Comment by FabianCretton** [comment]
Hi all, do you have any news about this ?
I see that the it was "Blocked by [zazuko/rdf-cube-view-query#64](zazuko/rdf-cube-view-query#64)", but that #64 is now closed and solved I guess ?

**Comment by l00mi** [comment]
fixed with https://github.com/zazuko/cube-creator/pull/1060
