### ISSUE TITLE
Exporting project returns 404

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#829]
steps to reproduce:
1. open https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!ch-bafu-wald-faostat-prod-test002-xxqnddvzz4b/edit
2. click export

actual result: 404

expected: exported file

**Comment by Rdataflow** [comment]
same behaviour here:
https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!fab-test-forestry-3xrvo6r60jo/edit

**Comment by tpluscode** [comment]
Sorry about that, we missed a step to update the existing projects.

It is working now

**Comment by Rdataflow** [comment]
I confirm, it works well now. 👍
