### ISSUE TITLE
Opendata.swiss keywords need a language

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#836]
And they should be input one by one. We should make that clear in the description.

**Comment by l00mi** [comment]
That is what we call "tags" inside cube-creator right now?

**Comment by martinmaillard** [comment]
Yeah, I actually renamed that to "keywords" because I saw that opendata.swiss was using the term "keywords". Can revert this change in the PR if there's a reason to keep "tags", I don't know where this term is originally coming from.

**Comment by l00mi** [comment]
No it is better to allign.
