### ISSUE TITLE
Authorizing the CLI

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#84]
Similarly to data-cube-curation, we need an OIDC setup for machine-to-machine authentication so that the pipelines can access the API

I moved the token refresh code already

**Comment by sandhose** [comment]
Keycloak should be setup for the `ref` env. Client ID is `cube-creator-runner` and client secret can be retrieved here: https://auth.lindas.admin.ch/admin/master/console/#/realms/ref/clients/2dbc5207-109c-497f-afb5-98f6fda6c3c5/credentials (keycloak creds in keycloak)

For dev environment (zazukoians instance), client ID is `cube-creator-runner` and client secret can be retrieved here: https://keycloak.zazukoians.org/admin/master/console/#/realms/zazuko-dev/clients/64f92868-71e3-48e1-9d8b-7bfaf5fac2bd/credentials (behind auth0 login)

@tpluscode Tell me if you want me to work on the actual login logic (if so I might need some pointers) or if you have what you need to implement that.

**Comment by tpluscode** [comment]
Thank you @sandhose. I think the code should be the same you implemented last time. I'll confirm this works and close

**Comment by tpluscode** [comment]
@sandhose I get this error:

```
Error: Public client not allowed to retrieve service account
```

**Comment by tpluscode** [comment]
It's working. Thanks
