### ISSUE TITLE
Import project fail, asking the CSV file to be uploaded after importing the projet ???

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#843]
This my first import test. Having successfully tested the upload functionality, I decide to export the project initiated in INT in TEST. Not the usual path, but it should work also. The export works fine. The import display this error :

![image](https://user-images.githubusercontent.com/35593772/133644275-d808bb7a-1c80-4f40-b19b-4eb24eef4092.png)

The exported project from INT : [Test import CSV from URL](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!test-import-csv-from-url-w629nyz4dq1/edit)
The imported project in TEST : [Test import CSV from URL](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!test-import-csv-from-url-jdwng3y0rbn/csv-mapping)

The project file as exported : [Test_import_CSV_from_URL.trig](http://www.sfa-laboratory.ch/OGD/Test_import_CSV_from_URL.trig)

Following the suggestion, I've replaced the CSV file, given the same URL for the file and the problem is solved. A little transformation and the project is migrated from INT to TEST. Next time I'll test just a transformation without replace.

**Comment by l00mi** [comment]
Should be solved by now.
