### ISSUE TITLE
changing cubeIdentifier sometimes fails with odd error: multiple project names provided?

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#848]
steps to reproduce 
change cubeIdentifier to new value and repeateadly *save project*

actual results (cycling)
![image](https://user-images.githubusercontent.com/26090254/134020605-4224a146-9eb0-465a-a1cf-47600b27a220.png)
or
![image](https://user-images.githubusercontent.com/26090254/134021352-06cbdcca-df9f-4ece-b485-f1f6f8c16ba0.png)
or
![image](https://user-images.githubusercontent.com/26090254/134021555-cdd1da3c-3c0b-4545-a75a-6c0ed338615f.png)

**Comment by tpluscode** [comment]
This is the same problem you reported in #845 

Likely caused by when changing the namespace from `pipelines-xyz` to `xyz.pipelines`, some resources seems to have duplicate values for certain blank nodes.

I'll see to clean that up

**Comment by Rdataflow** [comment]
reloading gives 
![image](https://user-images.githubusercontent.com/26090254/134022221-621c2b00-9b48-46b9-b03a-f6f50e3c31b3.png)

**Comment by Rdataflow** [comment]
@tpluscode you better see if there is a common root cause for the sometimes duplicate entries that happen for several resources i.e.
- dcterms:cubeIdentifier
- csvw:dialect
- meta:dataKind
- schema:contactPoint
- dcat:contactPoint
- schema:associatedMedia
... maybe more?

**Comment by tpluscode** [comment]
The root cause was exactly my mistake when switching the domain from `https://pipelines-integ.lindas.admin.ch/` to `https://int.cube-creator.lindas.admin.ch/`

I messed up the script and duplicated values for any property which had blank node objects. We reverted and reapplied that migration.

Everything is back in order now
