### ISSUE TITLE
cannot update CSV on TEST

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/cube-creator#854]
![image](https://user-images.githubusercontent.com/26090254/134325926-8d71365f-01de-45eb-9139-d168f5ad3eb0.png)

This CSV update did work yesterday. What happened in the meantime?

**Comment by Rdataflow** [comment]
hmm, maybe the errormsg is misleading... is it that authorized session did timeout?

**Comment by l00mi** [comment]
@tpluscode is this still relevant?

**Comment by l00mi** [comment]
Should be solved, please open if appearing again @Rdataflow

**Comment by Rdataflow** [comment]
works now, thank you
