### ISSUE TITLE
Edit dimension metadata display each field twice (version 1.4.0)

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#855]
When editing the metada of [Fabian_Jahrbuch Wald & Holz 2020](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabianjahrbuch-wald-holz-2020test-2-xm3v67vbpkp/metadata), each field is displayed twice (see print screen).

It is not always happening, but I can reproduce:
- seems more often when selecting "de" language
- sometimes happening on one column, and not on the other

![image](https://user-images.githubusercontent.com/6167669/134481908-46255809-7839-486b-a76b-9312c54d9c90.png)

**Comment by PDumasBAR** [comment]
Same behavior in formular Edit Project :
![image](https://user-images.githubusercontent.com/35593772/134548401-f54875ca-ab05-4655-8e25-86a109438820.png)

Refresh the browser does not correct the display, but going to another tab and back correct the display.

**Comment by tpluscode** [comment]
Thank you for reporting. This appears to have been some inconsistency in the Stardog cluster. 

I recreated the static resources (including the shapes which run the forms) and the problem should now be gone

**Comment by FabianCretton** [comment]
I still see this problem with version 1.5

**Comment by l00mi** [comment]
Should be solved again with the deploy of today.

**Comment by l00mi** [comment]
This was an error which came through some problems in the DB, we did not actively fix it. Please report if seen again.
