### ISSUE TITLE
Organisations appear twice in the list for field "Owner of the published cube dataset"

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#856]
In INT only. 
In TEST Every organization appears only once.

Maybe related to https://github.com/zazuko/cube-creator/issues/855. Veronique also tell me about a similar behavior in the Cube Designer, where all fields in the edit Dimension and the edit Cube Metadata formular appear twice (twice the **Name**, twice the **Description**, etc.)

![image](https://user-images.githubusercontent.com/35593772/134544057-71a930cd-cf22-4fed-ab71-2710a3552511.png)

**Comment by tpluscode** [comment]
Sorry about that. I cleaned up the duplicates
