### ISSUE TITLE
Validation fails on editing the metadata of a project (formular Edit Project)

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#857]
Now we have other organizations available in the tool.
I've try to change the organization owner of our cube in INT, but the validation fails:

![image](https://user-images.githubusercontent.com/35593772/134548970-168af45c-7640-4ce3-9d4b-9609bd203793.png)

It works on TEST, but I must make more tests with published cubes.

The validation fails also if I only change the project title, so the problem is not the organization.
![image](https://user-images.githubusercontent.com/35593772/134548115-80b17659-40ec-4581-83f8-d2c8bb01364e.png)

No problem changing the title of a project in TEST.
The validation only fails in INT.

**Comment by tpluscode** [comment]
Same as #839. Will be fixed on next deployment
