### ISSUE TITLE
Import/Export problem ? Transformation successful but no data in the Cube Designer in TEST

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#858]
Project : [Staatsrechnungen - Amt](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-amt-w5jeoeg3gxg/edit)

I've exported this project from INT and reimported it in TEST.
I must reload the CSVs as expected (see https://github.com/zazuko/cube-creator/issues/843).
The 3 CSV and the corresponding mapping tables have been generated, all the parameters in both the CSV Mapping and the Cube Designer seems correct.

The transformation runs successfully but there is no data visible in the Cube Designer.
The only difference between the cube in INT and the cube in TEST is the owner, ofen in INT and sfa in TEST.
The CSV files are the same, uploaded from the file system in INT, uploaded from an URL in TEST.

There are 3 more cubes in the same data project Staatsrechnungen, I will try to export/reimport another one to see if the transformation fails the same way.

**Comment by tpluscode** [comment]
Hi @PDumasBAR, that's quite interesting

The problem appears to have been that once you changed the organisation the cube remained based in the BAFU namespace (`https://environment.ld.admin.ch/`). That is, only the lookup identifier was wrong. The actual transformed cube was correct but the mismatch caused to not show any oberservations.

So I switched your project to FOEN and the back to SFA and the identifiers got corrected. The observations now load correctly.

I'm curious what series of actions led to this so that we could possibly prevent such occurrence in the future

**Comment by PDumasBAR** [comment]
Hi Tomasz,
I just discuss this issue with Fabian and Véronique and we come to the same conclusion. 
There is a problem in importing an exported project in an other organization than the original organization.
You can test the 2 other projects I've exported from Staatsrechnungen  in INT and reimported in TEST:
- [Staatsrechnungen - Bereich](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-bereich-3ya3dwbnp6k/edit). Export from foen, reimport in sfa. Relaod the CSVs. Transform. No error, but no data.
- [Staatsrechnungen - Funktion](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-funktion-6g2dpl902ko/edit). Export from foen, reimport in foen. Relaod the CSVs. Transform. No error, data ok.

There is another consideration that come in the discussion. We think it's not a good idea to have the possibility to change this identifier (and also the organization) at any time, as that can make some problems in the store. Yet we have the export/import functionalities so the user : 
- must define an identifier and organization at cube creation 
- and must export and reimport to change these parameters (in the same or another environment)

I've already made the test. The data are lost when I change the organization. I must retransform, not really a problem. But what happens if I delete the project ? Are the old data also deleted ?
We can discuss that at the next meeting.

Thank for the debugging this issue and others.

**Comment by FabianCretton** [comment]
It seems that I have the same problem with
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabubd0104-qualitat-der-badegewasser-z0vnvjmqpzw/csv-mapping

That is an import from and where the organization is set to the same as the original one.

Transformation succeeds, but no data in Cube Designer

**Comment by tpluscode** [comment]
Closing in favour of #910
