### ISSUE TITLE
Login on test.cube-creator, from Chrome, does not work for me

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#860]
When I do the login on https://test.cube-creator.lindas.admin.ch, from my Chrome browser, I get the following error after entering the received code:

![image](https://user-images.githubusercontent.com/6167669/134886710-19836363-d8af-46de-acdb-aff31c89b4d3.png)

on int.cube-creator, it works fine.

Is it a problem on my side ?

**Comment by l00mi** [comment]
That can happen and be solved by removing all cookies.
