### ISSUE TITLE
Publication - FetchError: Cannot follow redirect with body being a readable stream

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#866]
This morning I did test a new publication of this cube, and it seems I have a new kind of error:
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabforestrynormalized-5ljx6a5axdk/publication
Log: https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/15092

**Comment by tpluscode** [comment]
Hello Fabian. My fault sorry, I made a mistake in the gitlab settings which I reverted when I noticed the job failures. Please try again

**Comment by FabianCretton** [comment]
Seems to work as before, thanks
