### ISSUE TITLE
Create Delete API Handlers

### ISSUE THREAD

**Issue by lucafurrer** [zazuko/cube-creator#88]
The following Delete Handlers should be treated by the API

- [x] API handler to delete a project
- [x] API handler to delete a source
- [ ] API handler to delete a table

Open questions: 
- Can a source be deleted if it has associated tables?
- Do we want to hard delete or soft delete? (22.10)
  - hard delete: delete all triples
  - ~~soft delete: flag as deleted~~
- How do we handle cascade delete of associated resources?

**Comment by lucafurrer** [comment]
Discussion on Zulip on Thursday 22.10.2020: 

**We go for hard delete**

**Comment by lucafurrer** [comment]
Open question: 
How to exactly implement the cascade delete?
For the moment @tpluscode and I would go for an approach which every delete code handles the cascade itself. Up to see if it is possible to call the delete on the linked resources itself.

**Comment by lucafurrer** [comment]
@martinmaillard  what do you think about the delete if it has associated tables?
- Not possible
- With warning?

**Comment by tpluscode** [comment]
> How to exactly implement the cascade delete?

Just a not that this side effect on other resources does not have to be delete.

For example, we might allow deleting a source and mark the tables so that they need user's attention. Smth like

```diff
<table>
  cc:source <source> #might keep this, no instant harm in broken links
  schema:error "Source gone. Please update the table"
```

**Comment by martinmaillard** [comment]
Closing this one. I created #121 for table deletion
