### ISSUE TITLE
When displaying the list of projects, the ordering seems sometimes wrong

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#888]
It seems that when working on a project, or creating a project (i am not sure), when going back to the list of projects, that project comes first in the list.

![image](https://user-images.githubusercontent.com/6167669/136982793-ec4d7f1d-9aff-4d67-9518-acf034f2db05.png)

I saw this behavior a long while ago, and personally I can find it disturbing not to find the project in the alphabetical order as I would expect.
Is it a wanted behavior, and if so, can you explain it ?

**Comment by l00mi** [comment]
Do order alphabetically for now.
