### ISSUE TITLE
When creating a new project from exported project, if a first "create project" correctly fails on existing identifier and the .trig is modified, a second "create project" causes "unknown error"

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#889]
I did export a project and import it.
I correctly got the error on the existing identifier:
![image](https://user-images.githubusercontent.com/6167669/136984271-4cc94e73-5587-44e9-b994-7a39c7f90f4c.png)

Then I did edit the .trig and change the identifier.
On the interface, I pressed once again on "Create Project" without changing anything in the interface (as the modification was in the file), and I got:
![image](https://user-images.githubusercontent.com/6167669/136984457-08c09db3-bf62-4488-a89d-892ef85e6909.png)

**Comment by l00mi** [comment]
This is obsolete now with the new import. In general we should never manually change the TRIG files.
