### ISSUE TITLE
Something wrong in the cube configuration

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#895]
Maybe related to https://github.com/zazuko/cube-creator/issues/870

3 cubes out of the 4 **StateAccounts** work now fine on INT and PROD.
I cannot transform the last one (**Category**) on INT : [Cub Project on INT](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-ognm0oomx61/edit)
I've made a lot of tests, changing the organization, reuploading the CSV, nothing to do.

I decide to export the project and reimport on TEST and see what happens. 
Export/Import work fine but I the transformation still fails. [New Project on Test](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!staatsrechnungen-kategorie-8jylb9kb0kp/edit)
The log [15779](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/15779) says : .../dimension-mapping/category-ydbnxbbnndg not loaded
I remove everything related to the Category (CSV, Table) and recreate it.
The next log [15784](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/15784) says  : ...dimension-mapping/operationcharacter-17ywnlkzx86 not loaded
I remove the OperationCharacter and next [15785](https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/15785) the ReportType.

When all the tables (except the observation table) have been removed and recreated the transformation succeeded.

I've exported the project on Test and compare with the export of the same project on Int.
There are some little differences, but the main differences are in the associatedMedia configuration. In Int there is a schema:contentUrl with an Url, in test there is only cc:sourceKind cc:MediaLocal.

I hope it can help to find why some transformations fail.

[Staatsrechnungen - Kategorie (Int).trig.txt](https://github.com/zazuko/cube-creator/files/7347536/Staatsrechnungen.-.Kategorie.Int.trig.txt)
[Staatsrechnungen - Kategorie (Test).trig.txt](https://github.com/zazuko/cube-creator/files/7347547/Staatsrechnungen.-.Kategorie.Test.trig.txt)

**Comment by tpluscode** [comment]
I'm sorry @PDumasBAR. The issues appears to have resulted from some dimension identifiers not being updated when the organisation/identifier was changed fo a cube. Specifically, affected were properties mapped to shared dimensions

This has been fixed already but projects needed manual correction. It should be fine now
