### ISSUE TITLE
Export project from INT and import in TEST: pending display of the CSV Mapping page

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#902]
I have exported my [red lists project](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabian-red-list-test-1-b7aqog24r6n/edit) from INT, to import it on TEST.
I have created the new project on Test, from exported project, but after pressing the "Create project" button, the CSV Mapping page opens with a pending hourglass.
Even after closing/reopening that project on TEST, the same pending happens, see printscreen:
![image](https://user-images.githubusercontent.com/6167669/137858705-682658cd-4397-40f3-996b-9f55ac1177ac.png)

**Comment by tpluscode** [comment]
Fixed with 1.5.5
