### ISSUE TITLE
New project from exported one - empty error message when no file is selected

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#903]
I wanted to create a new project from an exported one, and I pressed on "Create project" before choosing the file.
There was an error message, but empty:
![image](https://user-images.githubusercontent.com/6167669/137859638-4fda4973-3123-4ea2-a07b-ff070a54ae32.png)

**Comment by tpluscode** [comment]
RE https://github.com/zazuko/rdf-validate-shacl/issues/67

The shape used is an alternative (`sh:xone`) of the 3 variants for creating project: mapping, external, import (excerpt)

```turtle
</shape/cube-project/create>
  sh:xone (
    [
       sh:property [
         sh:path cc:projectSourceKind ;
         dash:hidden true ;
         sh:hasValue <https://cube-creator.zazuko.com/vocab#projectSourceKind/ExportedProject> ;
       ], [
         sh:name "Project data" ;
         sh:path cc:export ;
         sh:minCount 1 ;
         sh:maxCount 1 ;
         dash:editor cc:dashFileUpload ;
      ]
    ]
  ) ;
.
```

The error is not correctly communicated from the nested shape and it's an issue in multiple places

**Comment by l00mi** [comment]
Will be solved with https://github.com/zazuko/cube-creator/issues/947, closing this one for now.
