### ISSUE TITLE
Additinoal informations to show on projects list (modificaitons, upload csv)

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#908]
In a future release an abstract of these informations should be visible in the projects list:

- [x] Last modification (any update or csv upload)
- [x] Last version numbers (draft and/or published)
- [x] targets (opendata, visualise)
- [x] special status (published, unlisted, deprecated)

_Originally posted by @PDumasBAR in https://github.com/zazuko/cube-creator/issues/651#issuecomment-938648005_

**Comment by l00mi** [comment]
moved to new issue https://github.com/zazuko/cube-creator/issues/994
