### ISSUE TITLE
Shared Dimension export -> import ERROR

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#912]
The "heavy metal" shared dimension was exported from INT to a .trig file.
When trying to create a shared dimension on PROD or TEST, from that file, the following error occurs:
![image](https://user-images.githubusercontent.com/6167669/138280990-29d9872e-9aaa-4cbf-98b3-5a2fc0e91439.png)

**Comment by l00mi** [comment]
@tpluscode should this not have been closed with the merge?
