### ISSUE TITLE
Cube Designer - Dimension meta-data - Removing Dimension Type is not 'saved'

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#920]
If a dimension is marked as "key dimension", shouldn't it be possible to remove that using the "-" (minus) button ?
![image](https://user-images.githubusercontent.com/6167669/139396260-7cca09e5-f3ab-47c2-bb1c-c3f8f535a0d1.png)

I tried to remove that, the information was correctly removed in the edition form, and I saved -> but the columns kept its name in "bold", and when re-opening the metadata of that dimension, the former dimension type was still there.

I do not know if this always happening or not, I tried in two projects and it was the case.

**Comment by tpluscode** [comment]
The dimension is preselected to match the same selection made in the CSV Mapping tab for the input column

**Comment by FabianCretton** [comment]
As discussed in a [Zulip ](https://zulip.zazuko.com/#narrow/pm-with/4,34,51-group/near/218180)with Adrian/Martin, the link between the "Dimension type" on the CSV Mapping and on the Cube Designer should be clearly explained in the user guide, right @l00mi  ?

**Comment by l00mi** [comment]
add a description explaining that if its set in the mapper it is fix.

**Comment by l00mi** [comment]
* Stated in UI https://github.com/zazuko/cube-creator/commit/c13f5ffc29c8c9638fb3bbddfc539d66020b9ef2
* Improvement Feature in backlog #955
