### ISSUE TITLE
Cube Creator - Publish job started, but not listed

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#921]
I did press the "start publication" button, the popup saying that job job was starting appeared, but then the job was not added in the list of "Previous publications":
![image](https://user-images.githubusercontent.com/6167669/139411811-a0aa7bd3-b083-4374-b699-9b6dc7db8461.png)

I tried a second time, and it was the same.

I went to the pipelines, and I saw the jobs, that did finish successfully:
![image](https://user-images.githubusercontent.com/6167669/139412260-51726208-ba13-47b3-aa74-c63277893b3f.png)

Project:
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabtest20211029-qe1gb8n98ew/publication
One of the jobs:
https://gitlab.ldbar.ch/pipelines/cube-creator/-/jobs/16530

**Comment by l00mi** [comment]
This seems to be based on the DB reliability issues for now. We keep it in the backlog to check later on if its still an issue.

**Comment by l00mi** [comment]
@FabianCretton this seems to be solved. If you still see the issue please re-open the issue.
