### ISSUE TITLE
Delete project seems to always fail - Cube Creator INT

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#932]
These days I am trying to "clean-up" my test projects, with the "Delete Project" button, but I always get a "Internal Server Error":
![image](https://user-images.githubusercontent.com/6167669/140021472-460f7121-8b8b-4c15-8151-218168cfa4dc.png)

For instance on the following projects:
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabian-red-list-test-to-test-import-with-new-id-2bdpnbbwkep/edit
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabian-red-list-test-import-lz4z2jne6rn/edit

**Comment by martinmaillard** [comment]
From what I gather from the error reports, this is due to a timeout of the stardog query (@tpluscode https://sentry.zazuko.com/organizations/zazuko/issues/1210/)

**Comment by martinmaillard** [comment]
Should be fixed
