### ISSUE TITLE
Shared Dimension are not using the proper deployed URI in Cube when published.

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#941]
The following cube seems to publish the wrong links for Shared Dimensions: https://s.zazuko.com/Rdja6.

It uses : 
https://cube-creator.lindas.admin.ch/dimension/el01/cd

Instead expected correct:
https://ld.admin.ch/cube/dimension/el01/cd

**Comment by tpluscode** [comment]
The problem here was that transformation in PROD would run from an older version of `cube-creator-cli`. Needed an update in [GitLab config](https://gitlab.ldbar.ch/pipelines/cube-creator/-/settings/ci_cd) (variable `IMAGE_TAG`)
