### ISSUE TITLE
Impossible de créer un nouveau projet en INT - unknown error

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#943]
version 1.6.1 (04a63f2) en INT  
Pas d'autres information sur le problème. J'essaie en TEST.
![image](https://user-images.githubusercontent.com/35593772/140502886-4dcd767e-9754-4b6b-9c32-a518b0d680b5.png)

**Comment by PDumasBAR** [comment]
ça passe en TEST, avec les mêmes paramètres, sans problème.

**Comment by l00mi** [comment]
still the same, please follow https://control.vshn.net/tickets/SBAR-534
