### ISSUE TITLE
Hierarchies of shared dimension terms

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#945]
https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/314

The question is how to connect the terms to for a hierarchy.

Maybe `skos:broader`?

**Comment by l00mi** [comment]
This is defined already in https://github.com/zazuko/rdf-cube-schema-viz/blob/master/README.md#nested-hierarchies and the necessary functionality will be done through https://github.com/zazuko/cube-creator/issues/939.
