### ISSUE TITLE
Warning should be issued if data is missing (cube:Undefined) at least for key dimensions

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#948]
There should be a warning, or a list created, for any observation where we have no value. Especially for key dimensions which will create wrong cubes.

**Comment by tpluscode** [comment]
I'd propose to handle this similarly to #949, calculating the problems when the transformation completes and then showing on the Cube Designer screen.

Now, if we'd want to actually display observations with missing key dimensions, maybe this could be an optional filter when retrieving the observations on said screen
