### ISSUE TITLE
Replace "transform" button with a step between mapping and designer

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/cube-creator#954]
Epic: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/307

It is currently impossible for users to understand when the "transform" button should be clicked. Moving it as a tab on the left of "Cube designer" should make it clearer.

Two things to keep in mind:
- The "CSV mapping" step doesn't always exist. Sometimes, "transform" is actually "import".
- Some changes (i.e. shared dimension mapping) in the Cube Designer may require re-running a transformation. This should be made very clear in the UI.

**Comment by PDumasBAR** [comment]
Previous transformations should be visible the same way previous publication are shown in the publication step.
