### ISSUE TITLE
Error when changing CSV Settings for the delimiter

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#968]
In "CSV Mapping"
I did upload a .csv which was not correct, and the separator was the ','
Then I have corrected the .csv, and I changed the separator to ';'

I thus wanted to change the separator on the CSV Settings and got that error:

![image](https://user-images.githubusercontent.com/6167669/142426847-8e4eb209-bbd7-402f-ab05-b2872568a983.png)

**Comment by martinmaillard** [comment]
The error is caused by the fact that "quote char" is mandatory.

We should add a default value (i.e. `"`) for this field.
