### ISSUE TITLE
Publish CKAN in production.

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#984]
Make necessary changes to deploy CKAN in production.

**Comment by martinmaillard** [comment]
The [MR](https://gitlab.ldbar.ch/vshn/gitops-prod/-/merge_requests/474) is merged, but the endpoint doesn't seem to be deployed. Can you please check @ludovicm67 ?

**Comment by ludovicm67** [comment]
As I can see in other environments, ingress for the Trifid instance is disabled in the chart values and a specific ingress is created aside. We will need to replicate this pattern in the prod environment. I can take care of this.

**Comment by ludovicm67** [comment]
Opened a [MR](https://gitlab.ldbar.ch/vshn/gitops-prod/-/merge_requests/475) for that.

**Comment by ludovicm67** [comment]
The MR was merged.

**Comment by martinmaillard** [comment]
Great thanks!
