### ISSUE TITLE
Integrate with GitLab for running transformation pipeline

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-creator#99]
The app should be able to trigger a pipeline job to run a transformation (on GitLab?)

**DoD**

* [x] The UI has a "trigger" button to start a transformation job
* [x] The API has a hander for this "trigger" request
   - a `Job` resource is created in the data store
   - `Job` should link to the CSVW resources to transform, output graph URI, etc; 
   - `Job collection` resource created as child of `csv mapping`
* [x] GitLab is triggered (Job URI as parameter)
* [x] GitLab starts running the CLI (depends on #98) 
* [x] When done, the pipeline runner updates the `Job` resource 
   - success or not
   - something else?
* [x] All data get overwritten in the cube's observations graph
   - I propose to keep observation separated to avoid overwriting the cube itself

**Comment by lucafurrer** [comment]
What information does the trigger button provide?

CSV-Mapping is given from the context. 
- Tables?
- Target Graph?

**Comment by tpluscode** [comment]
The "trigger button" does not really provide any information.

The tables you'd get from the table collection `<csv-mapper> cc:tables <csv-mapper/tables>`
The target graph you'd get from the project `<project> cc:cubeGraph <whatever>`

**Comment by tpluscode** [comment]
In fact, for the `Job` resource I propose a structure like

```
graph <csv-mapping/jobs/xyz> {
  <csv-mapping/jobs/xyz> a cc:Job ;
    cc:csvw <table-1/csvw> , <table-2/csvw> , <table-3/csvw> ;
    cc:cubeGraph <from-project>
}
```

`cc:csvw` would be a property of `Table`

`xyz` could be a short string like generated by [nanoid](https://npm.im/nanoid)

**Comment by lucafurrer** [comment]
After discussion we would have

```
graph <csv-mapping/jobs/xyz> {
  <csv-mapping/jobs/xyz> a cc:Job ;
    cc:tables <csv-mapping/tables> ;
    cc:cubeGraph <from-project>
}
```
Correct?

**Comment by tpluscode** [comment]
Agree @lucafurrer 👌

**Comment by lucafurrer** [comment]
Just thinking aloud, I think a indication when a job was created could be useful for debugging etc.
`schema:dateCreated` or `dcterms:created`

**Comment by lucafurrer** [comment]
@tpluscode you agree that this is done

**Comment by tpluscode** [comment]
Definitely. Thanks!
